### ISSUE TITLE
Possibility of having config as two panes similar to vscode

### ISSUE THREAD

**Issue by Rafi993** [onivim/oni#1002]
Oni config by default is empty now. But it would be better if it is divided into two panels similar way it is listed in vscode. This would allow users to know things that they can configure and play around with it.

**Comment by bryphe** [comment]
Thanks for logging the issue, @Rafi993 !

Yes, discoverability of the configuration settings is definitely a problem.

Some related issues:
#976 
#837 
#704 

It'd be great to have a cohesive story for this that addresses these concerns holistically, as configuration is so important.

**Comment by CrossR** [comment]
This was actually implemented in #1795! 

I'll close this out for now, and if there is any specific improvements we need to make to it, its probably better in a targetted issue.
