### ISSUE TITLE
Hover dialog shouldn't show upon switching tabs.

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#1006]
If you have your cursor over an item, a hover dialog will show (describing the type or something).
If you switch tabs using `:tabnext`, and then switch back using `:tabprev`, the cursor is still where it was originally, but the hover dialog pops up again unexpectedly, and it's kind of distracting. I feel the act of switching to another tab should trigger the dismissal of the original hover dialog, and switching to a tab should not trigger the creation of a hover dialog. I think an explicit cursor movement to a location (or mousein) should trigger such a dialog.
(Btw, I love that using the keyboard to move the cursor to a token triggers the dialog).

**Comment by bryphe** [comment]
Great feedback, thanks @jordwalke !

> I think an explicit cursor movement to a location (or mousein) should trigger such a dialog.

Agreed - that would handle the tab navigation case implicitly.

**Comment by jordwalke** [comment]
> This is good to hear - I wasn't sure if it is too distracting (and it certainly can be intrusive if it is common up too aggressively, like this case).

I did find that it can become distracting after some extended use. The most important thing to me is being able to never touch the mouse, and so having an explicit keyboard shortcut to trigger the info dialog would probably be a better long term setting for me. However, for the "out of the box" configuration, it might make sense to keep the cursor tracked auto-popup just so that it shows off Oni's features. It wouldn't be as easily discoverable with a keyboard shortcut - though that keyboard driven setting could be encouraged for serious users.

**Comment by bryphe** [comment]
Great feedback! I've cleaned up some of the state management for the hover UX (there were several cases where it could flicker, or bounce in if the request to the LS took a long time), and also added an `editor.quickInfo.show` command, which can be used even if `editor.quickInfo.enabled` is set to `false`.

**Comment by bryphe** [comment]
This was fixed with PR #1044 and is available in the latest release (0.2.18)-
