### ISSUE TITLE
Make buffer tab text not selectable by the OS:

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#1010]
<img width="541" alt="screen shot 2017-11-23 at 3 01 37 am" src="https://user-images.githubusercontent.com/977348/33169772-aed96e0a-cffa-11e7-8942-d2ca5079b2f8.png">

By dragging the mouse just right I was able to select the text in the buffer tabs.

I think the intention was that this would be disabled.

**Comment by bryphe** [comment]
Ah yes, this is a pretty glaring fit-and-finish bug - definitely should be disabled - thanks for catching it and logging an issue, @jordwalke !

**Comment by bryphe** [comment]
Thanks for the fix, @Akin909 !
