### ISSUE TITLE
Add configuration for font smoothing (antialiasing)

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1012]
From @benjamin-rood 's feedback on gitter - would be helpful to have a configuration setting for setting / changing: `webkit-font-smoothing`  on the body.

Perhaps `ui.fontSmoothing` with options of `none`, `antialiased` and `subpixel-antialiased`, and then just directly set the `webkit-font-smoothing` property from there.

**Comment by benjamin-rood** [comment]
Would also be worthwhile cf. how VS Code / Atom are implementing it.
Is this a feature anyone can fix via PR?

**Comment by bryphe** [comment]
FYI, looks like VSCode directly sets the `-webkit-font-smoothing` property with the `workbench.fontAliasing` config: https://github.com/Microsoft/vscode/blob/e27288074e0287a42d6752e20873c668526e8c4d/src/vs/workbench/electron-browser/workbench.ts#L935

**Comment by bryphe** [comment]
This is now available via `ui.fontSmoothing` configuration in `master` - some details here: https://github.com/onivim/oni/wiki/Configuration#ui

I'm planning on including this as part of the the 0.2.18 release tomorrow.

**Comment by benjamin-rood** [comment]
Merci Beaucoup!
