### ISSUE TITLE
Tooltip continuously resizing when oni less than fullscreen

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1020]
When less than fullscreen and hovering over a word with a long type signature or a lot of information the tooltip generated if oni is at less than full screen, especially if at half width continuously resizes creating a 'shuddering' effect, making the text in the tooltip hard to read.

![tooltip-bug](https://user-images.githubusercontent.com/22454918/33239396-5e5fbc8a-d299-11e7-857d-a6a32a6b4bfe.gif)

I've had a look and I think this bug is coming from `CursorPositioner.tsx` specifically [here](https://github.com/onivim/oni/blob/6c5f054a5f028c88aa35ab275ff8110573948a88/browser/src/UI/components/CursorPositioner.tsx#L151-L156),

![details-tooltip](https://user-images.githubusercontent.com/22454918/33239484-9753196e-d29a-11e7-9f4b-20bdc900e339.gif)

The `this.state.isFullWidth` value is constantly flipping from true to false because the clientRect() is changing from in my specific case from 1000 to 300, as a test, on setting the left and right position to 0 the flickering stops.

A solution would be to set position right to a value and not have it vary? this seems to stop the flickering whilst allowing for space on full screen and split screen although it leaves the tooltip I'm not sure if this would impact something else or not be what you had in mind there.

EDIT: A static px value unfortunately sticks the tooltip in the right regardless of cursor position :( and a percentage value whilst working a bit better seems like a slightly messy solution

**Comment by bryphe** [comment]
Ah yes this is messed up! Thanks for logging the issue, @Akin909 . I'm able to repro it in our `ContextMenuComponent` here:

![image](https://user-images.githubusercontent.com/13532591/33333935-2abe8cbe-d41d-11e7-9610-d372a806520a.png)

The `<CursorPositioner />` component is responsible for this sizing (it decides whether to open upward or downward, based on the contents and the position). Seems like there is some feedback loop here unfortunately.

**Comment by Akin909** [comment]
@bryphe , I've tried removing the right option, setting it to a static value or a percentage, as well as creating a less file and sizing it based on a media query unfortunately as it is being styled dynamically in the react component it seems not to pick up any less styles or override them, I think that it likely needs a max width (as a guess re solution) because what seems to be happening is that the element is less than full with then 8px is added to its right forcing it to change width which causes the `this.state.isFullWidth` boolean to flip as it is no longer full width and the cycle continues. I think that if the width was static in some way when at less than full screen then it wouldn't flip?
