### ISSUE TITLE
Theming: Add solarized-dark and solarized-light as out-of-box themes

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1050]
#[Solarized](https://github.com/altercation/vim-colors-solarized) is a very popular colorscheme that would make sense to be bundled with Oni.

In addition to bundling the Vim colorscheme, we should also define a [Theme](https://github.com/onivim/oni/wiki/Theming) to have a high-fidelity set of colors for our enhanced UI elements, for Solarized.

The [theme-onedark](https://github.com/onivim/oni/tree/master/extensions/them`e-onedark) that we include would be a good reference point for this!

**Comment by Akin909** [comment]
@bryphe left this for a bit to see if anyone else wanted to have a go, but I'm happy to do this seeing as there haven't been any other takers, two quick questions though.
1. vim solarized by altercation no longer looks to be maintained, meaning its styles haven't been updated with new highlight groups that exist in nvim? would you still like to use that knowing that or perhaps use a maintained fork like `lifepillar/vim-solarized` 

2. in the `theme-solarized.json` how did you populate those colors did you get them from the vim theme i.e. find the color used for bg in the vimscript then enter that etc. ?

**Comment by bryphe** [comment]
Awesome, would be great to have your help here, @Akin909 ! Doesn't look like anyone else is checking this out at the moment.

> vim solarized by altercation no longer looks to be maintained, meaning its styles haven't been updated with new highlight groups that exist in nvim? would you still like to use that knowing that or perhaps use a maintained fork like lifepillar/vim-solarized

The lifepillar fork sounds good to me: https://github.com/lifepillar/vim-solarized8

> in the theme-onedark.json how did you populate those colors did you get them from the vim theme i.e. find the color used for bg in the vimscript then enter that etc. ?

Ah yes, I opened up the `onedark.vim` and grabbed the color values. Luckily, they are in hex so it was just copy-and-paste over.

Thanks for your help! Let me know if you have any other questions.

**Comment by CrossR** [comment]
@Akin909 if I'm not mistaken you've added this now in #1122, so I'll close this ticket.
