### ISSUE TITLE
How can I hidden the titlebar on 0.2.18 ?

### ISSUE THREAD

**Issue by duanjun** [onivim/oni#1067]
How can I hidden the titlebar on 0.2.18 ?

**Comment by bryphe** [comment]
Hi @duanjun , thanks for the issue! Can you please clarify what the behavior you expect is? For example, do you not want the filename in the title?

**Comment by duanjun** [comment]
yes， I want a fullscreen just likes terminal does  ，so i think title should be configurable

**Comment by CrossR** [comment]
Have you tried setting `editor.fullScreenOnStart` to `true`?
You can also set `oni.hideMenu` to `true` to hide the File/Edit/Split bars.

**Comment by badosu** [comment]
Also, `maximizeScreeOnStart` is a good option.

**Comment by bryphe** [comment]
Ah I think that in OSX, where we now show a titlebar with #68 , we don't hide it on fullscreen - so maybe we don't need a new setting, but just need to hide it in the case where we are fullscreen (which I believe is consistent with how other OSX apps behave).

**Comment by bryphe** [comment]
This should be fixed now in the latest release with #1064 - once we're full screen, we hide the titlebar on OSX (like other apps).
