### ISSUE TITLE
Custom colors are gone

### ISSUE THREAD

**Issue by MikaAK** [onivim/oni#1069]
Just updated to newest version of Oni and my custom color theme seem to be gone!

**Comment by CrossR** [comment]
There was a breaking change in the latest release:

Colorschemes - colorschemes must now be specified via `ui.colorscheme` in your `config.js`, as opposed to in the `init.vim`.

Could that be the reason?

**Comment by MikaAK** [comment]
That was totally it. Even thought it was the first breaking change somehow I missed it! Thanks
