### ISSUE TITLE
Golang completion

### ISSUE THREAD

**Issue by vbauerster** [onivim/oni#1080]
First of all, thank you for oni!

I wasn't able to turn on auto-completion for golang, in spite of I've `go-langserver` available in my `$PATH` and have tried following settings.
```
"golang.langServerCommand": "/my_full_path_to/go-langserver",
"language.go.languageServer.command": "/my_full_path_to/go-langserver",
"language.golang.languageServer.command": "/my_full_path_to/go-langserver",
```

What I did wrong?
PS: I'm using mac version.

**Comment by CrossR** [comment]
Are you building from master or using the latest release (0.2.18)?
If its the latest release, its possible you are having the same issue as #1061, which should now be fixed on master.

**Comment by Contextualist** [comment]
`go-langserver` does not support completion yet (see sourcegraph/go-langserver#201). For now, you may use [gocode](https://github.com/nsf/gocode) for completion.

**Comment by josemarluedke** [comment]
I recommend using https://github.com/fatih/vim-go which has integration with auto complete using deoplete (with `deoplete-go`, which uses gocode). I have been using that and works great.

**Comment by vbauerster** [comment]
I used latest release (0.2.18). Thanks for recommendations.

**Comment by saibing** [comment]
@vbauerster 

[go-langserver](https://github.com/sourcegraph/go-langserver/) support completion now.

Thanks Contextualist's outstanding job

**Comment by bryphe** [comment]
Looks like this is working now. I'll close this out - feel free to open a new issue if there are still problems here.
