### ISSUE TITLE
set tabstop=2 no available

### ISSUE THREAD

**Issue by DemonCloud** [onivim/oni#1084]
```vimL
set tabstop=2 "4
set shiftwidth=2 "4
set softtabstop=0 "4
```

no available

and how to custom VerticalSplitLine Color

**Comment by badosu** [comment]
You need to configure oni to not load init.vim, see: 

- https://github.com/onivim/oni/issues/929#issuecomment-343993252

**Comment by DemonCloud** [comment]
@badosu  Thanks~

**Comment by bryphe** [comment]
Thanks @badosu ! I'll close this out - we'll track in #929 (and #973 to improve this story in general).
