### ISSUE TITLE
Cannot open multiple windows

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1100]
This is very likely to be due to a misunderstanding on my part but it seems I can't open multiple windows with Oni. Is that supposed to be the case, do I need to set a config option or is that a known bug or future feature. 

I couldn't find an issue relating to that, except #1008 which isn't quite what I mean. I'm running oni on a mac and using `cmd-n` or double clicking the `Oni` icon does not allow me to open a new window, I know that there's something about handling windows in `main.ts` with electron but I'm not sure if that currently should be permitting multiple windows or not.

**Comment by bryphe** [comment]
Hmm, I just tried the same with Atom and VSCode - here's how they work:
- `cmd+n` creates a new file, not a new window. We don't have a binding for that today, but would make sense to have it. 
- None of the apps I tried supported double-clicking on the dock icon to open a new window, but some supported right-click and then 'New Window'. Oni doesn't have that today, but we could look at adding that as an enhancement. This API would be a good starting point: https://github.com/electron/electron/blob/master/docs/api/app.md#appdocksetmenumenu-macos

There's also an issue where if you close Oni, and then try and go to a menu item, you hit #484 .

Would adding a 'New Window' option to the dock menu + command palette work for you to accomplish this? Seems like that would fit well with how other apps work on OS X

**Comment by Akin909** [comment]
@bryphe apologies seems I got my mac shortcuts confused. You're quite right re cmd n and the double clicking. Essentially any mechanism which leads to having multiple Oni windows (one project open in one instance another in the second) is what I was alluding too so a new window option would be excellent with the potential to bind this to a key, would a new window result in issues I noted there is an array in `main.ts` to keep track of open windows but also some code which seems to be aimed at maintaining a single instance?

**Comment by Akin909** [comment]
fixed by #1111
