### ISSUE TITLE
Status Bar: Investigate better handling of overflow scenarios

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1105]
Following from @Akin909 's notes in #1098:

> This is likely something for another issue/PR but I was working on trying to truncate the length of this component however there are a couple of issues I've run into. I'd want to do this inside of a media query and as It stands I tried creating a less file for the component and passing it a className which doesn't seem to work, I'm not sure how plugins are bundled aka if the less is read.

> Another approach which did work is I passed the component a prop in the plugin's index.js and in Oni's status bar item component where it is rendered I look for the prop and if present apply a truncation class (to add text-overflow ellipsis inside a media query which isn't possible with inline styles). I thought of adding the truncate option to the createStatusBarItem but this would require changing oni-api to take another argument.

> It's a minor point and not something I'm necessarily wanting to include here but as I often work with a split view or at least alternate frequently I noticed that the statusbar could get cluttered in which case I think plugin makers (future 😄 ) might find it difficult to apply styles to their components.

We should think about ways to handle overflow in the status bar. There are two cases that are problematic:
- __Too many items__ (clutter) - if the status bar is filled up with lots of different pieces, it won't look good.
- __Too small space__ - If the window is small, even with a few status bar items, we don't gracefully handle that - and you end up with overflow problems (like the line, column here):

![image](https://user-images.githubusercontent.com/13532591/33856957-b0e4df12-de7e-11e7-95dc-b869450cb436.png)

There are a few different possible solutions:
- Leave the sizing/styling up to the owner of the status bar item. This is the least work for Oni, as it defers the problem to whoever creates the status bar item. However, it means that there is potentially duplicate work across status bar items, and each plugin might have a different way of solving this.
- Let Oni manage the set of status bar items. VSCode does something similiar to this strategy - each statusbar item has a priority, and then depending on how much space is available, some status bar items may be hidden, based on priority.

**Comment by Akin909** [comment]
@bryphe thanks for opening the issue. When working on #1098 I added a text-overflow: ellipsis to the component but in order for that to kick in I'd also have to add a max-width which I was avoiding given that at full screen it'd be a shame to truncate a branch name if there was space on a fullscreen desktop and the max width was hard coded to 120px or something arbitrary. 

Though inside a query however we could make sure the truncation only happened on small viewports or another solution I tried was applying a class based on component priority aka in `statusBarItem` I added a class to the general item class if the item had a low priority except at the moment they all have pretty similar priority but I could reduce the priority of the component and then use the method there then apply a max width and text-overflow.

Perhaps based on priority you could add a truncation class based on 1) number of status bar items 2) width of the screen, and by default all status bar icons are given a width based on priority for example if the priority of the filename is given 1 or something then it has a width of 200px (for example) and at small viewports or with 5 or more items that is reduced to 150 and text overflow is added to it

**Comment by Akin909** [comment]
Or considering your comment re how vscode handles this, you could have certain priorities relate to levels of truncation/display for example `1 - always show never truncate`, `2- always show but set  max-width and truncate`, `3-always set to max-width, hide when necessary`, the numbers are just for example, this way you could have class priority classes and in the component you'd have 
```js
  <SomeStatusBarComponent className={`status-bar-item priority-${props.priority}`} />
```
One problem I can forsee though is that ideally we would get the information re max width from the plugin ahead of time its wouldn't be clear what a good max width would be for each for example setting a max width of 100px for line number would be a waste of space, one way round that could be allowing an extra argument of size in the `Oni.ui.createItem(<- extraSizeArg)` these can relate to sizes oni controls like large = 150px medium 90px etc.

**Comment by bryphe** [comment]
We now have first-class handling of visibility in our StatusBar! 💯 Will close this out - thanks @Akin909 !
