### ISSUE TITLE
Oni can not recognize the .ts  file type

### ISSUE THREAD

**Issue by saibing** [onivim/oni#1116]
I use the Oni that build from latest source code.

It treats typescript file as xml file, with no syntax highlighting.

![image](https://user-images.githubusercontent.com/5676390/33916563-6ba4ae48-dfe4-11e7-88b8-e614128e3188.png)

**Comment by bryphe** [comment]
Hi @saibing ,

Did you happen to run this command: `git submodule update --init --recursive` after checking out the repo?

We recently moved some of our plugins (including the typescript one) into submodules. I'd recommend running that command, and rebuilding - see if that fixes it for you. Let me know how it goes!

**Comment by saibing** [comment]
@bryphe 

Thank you. It solved the problem for me :+1:

**Comment by bryphe** [comment]
Awesome! 👍 Thanks for letting me know! I'll close this out.
