### ISSUE TITLE
Helping out

### ISSUE THREAD

**Issue by samvv** [onivim/oni#1120]
Hi there!

A while ago I tried developing [my own editor](https://github.com/AthenaHQ/Pencil), which is highly similar in design to this one. I've abandoned it a while ago and recently wanted to start again, until I noticed this project. It's absurd to maintain two editors that basically want to accomplish the same thing, so I'm wondering ... how can I help out? Are there any issues that I could help with?

One of the things I was personally thinking of that would be pretty cool is a plugin browser and plugin installer. Not sure what it would take because I'm not yet acquainted with the code base, but I would be very happy implementing this in a distant future.

Regards,
Sam

**Comment by bryphe** [comment]
Hi @samvv ,

Thanks for getting in touch, it's great to hear from you! I just checked out Pencil and you're right - our tools are very similiar across the tech stack, architecture, and goals. Definitely makes sense to join forces and build together! 😄 

> how can I help out? Are there any issues that I could help with?

Feel free to jump into any issue that is unassigned, we could use the help across the board. It's awesome that your project used a similiar tech stack (TypeScript/React/Webpack), so hopefully that helps in terms of getting started.

We have some bugs tagged as "help wanted", so some of those may offer a good introduction to the code:
https://github.com/onivim/oni/issues?q=is%3Aopen+is%3Aissue+label%3Abug+label%3A%22help+wanted%22

In addition, there are instructions for a first build here: [Development](https://github.com/onivim/oni/wiki/Development)

The plugin browser / plugin installer would be an excellent place to contribute. It's been on the backlog for a long time, but would be a tremendous step forward in improving the Vim/Neovim ramp-up (along with providing a consistent interface to adding both 'viml' plugins and the new javascript API plugins).

There's even a placeholder for it in the (experimental) sidebar - just no work on implementing it yet:
![image](https://user-images.githubusercontent.com/13532591/33960300-2a5a2970-dfff-11e7-8955-596971ccd5a5.png)

We had an issue tracking it here: #186 but it's old so it may need some updating.

A few places to look in the code:

Our `PluginManager`:
https://github.com/onivim/oni/blob/be9254679cca8bcfd8c7a184bae56f82b265d268/browser/src/Plugins/PluginManager.ts#L22

And `Plugin`:
https://github.com/onivim/oni/blob/be9254679cca8bcfd8c7a184bae56f82b265d268/browser/src/Plugins/Plugin.ts#L11

Our plugin stories look quite similiar, comparing to the plugins in Pencil: https://github.com/AthenaHQ/Pencil/blob/master/src/plugins.ts 👍 I like that you have a story for enabling / disabling plugins - that would be a cool thing to bring over as part of the plugin management story.

Let me know if you have any questions or need any help getting started - feel free to reach out on twitter (bryphe) or on our gitter: https://gitter.im/onivim/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Thanks again for getting in touch, @samvv . Would be great to have your help - look forward to collaborating!

**Comment by samvv** [comment]
Thank you so much for the information! I'm looking forward to it as well. I have some time to look into it today, I'll keep you updated.
