### ISSUE TITLE
Performance: Typing is painting entire row

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1129]
I was doing some benchmarking of the pre-release 0.2.19 build, and saw there is still one issue with the typing performance:
![paint-performance](https://user-images.githubusercontent.com/13532591/34013294-b5ed3d2a-e0cb-11e7-9acc-f0d6c65a0b07.gif)

(You can reproduce this by using the 'Rendering' -> 'Paint Flashing' tool in the dev tools).

As we type, the _entire row_ gets repainted - this is not ideal and is a cause for unnecessary latency in the typing operation.

It looks like there are two contributing factors:
- The `<KeyboardInput>` we use to manage IME is causing paint, even though its opacity is 0. It looks like promoting it to a layer (`transform: translateZ(0px)`) solves this. It's strange that it's painting with opacity 0, though.
- The canvas seems to be redrawing the entire string of tokens, instead of just the last one (as would be expected). Need to investigate further.

In addition, as part of this issue, we should investigate a proactive strategy to prevent this from regressing build-over-build. The `webContents` actually exposes a `paint` event: https://github.com/electron/electron/blob/master/docs/api/web-contents.md

A reasonable test case might be to validate that the paint rectangle does not exceed a certain area after typing.

**Comment by bryphe** [comment]
As part of the performance test, we should also validate that we are adding elements continuously - this will help us catch issues like #1146 more quickly

**Comment by hoschi** [comment]
Does this also fix TextMate highlighting performance? I have the problem that when typing and there are completion candidates the last typed letter is first in the default color, then in the color the rest of the word is already set to. E.g typing `this.callMyReallyCoolMethod` and I'm at state `this.ca|` the `ca` part is already in blue (solarized8_light) and every additional letter after that has this problem. I'm pretty sure my hardware is not a problem :grin:

**Comment by Bretley** [comment]
Is this still an unsolved problem? Just curious

**Comment by Bretley** [comment]
@bryphe where would be a place to look into this? Which file(s) use the KeyboardInput, or do you think the issue is mostly in the KeyboardInput itself?

**Comment by bryphe** [comment]
@Bretley - actually, I don't think it makes too much sense to work on this now. With @Cryza 's super-fast WebGL work (#2120, #2198, #2199, #2207) , this isn't really necessary - I think in lieu of this, it's better to just invest in the WebGL renderer. I'll close this out, but let me know if you have questions or ideas.
