### ISSUE TITLE
Security threat: Missing NX bit on distributed binaries

### ISSUE THREAD

**Issue by nyronium** [onivim/oni#1137]
The `oni` binary provided in all release packages for linux-x64 is missing the [NX bit](https://en.wikipedia.org/wiki/NX_bit).
This is a major security threat.

Please also check the binaries in packages for other architectures.

**Comment by bryphe** [comment]
Thank you for logging the issue, @nyronium ! Really appreciate you bringing this up.

I just read up on the NX bit and used the `checksec.sh` utility from here: http://www.trapkit.de/tools/checksec.html, and am able to reproduce what you are reporting:
```
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
Partial RELRO   Canary found      NX disabled   No PIE          RPATH      No RUNPATH   Oni-0.2.19-x64-linux/oni
```

However, I see that it is the same for other popular electron-based editors (VSCode/Atom):
```
[bryphe@bryphe-arch Downloads]$ ./checksec.sh --file atom-1.23.1-amd64/atom
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
Partial RELRO   Canary found      NX disabled   No PIE          RPATH      No RUNPATH   atom-1.23.1-amd64/atom
```

```
[bryphe@bryphe-arch Downloads]$ ./checksec.sh --file VSCode-linux-x64/code
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
No RELRO        Canary found      NX disabled   No PIE          RPATH      No RUNPATH   VSCode-linux-x64/code
```

My understanding is that, as we use Electron - which leverages V8 - the JIT requiring there precludes using the NX bit on the binary (which is why VSCode and Atom also do not have NX enabled).

**Comment by bryphe** [comment]
Given that we are in parity with the other common electron editors, I'm closing this out as won't fix. @badosu - FYI - let me know if you have any feedback here too.

**Comment by bryphe** [comment]
I also took a pass through the following repos to see if I could find any related issues:

- [atom/atom](https://github.com/atom/atom)
- [microsoft/vscode](https://github.com/microsoft/vscode)
- [electron/electron](https://github.com/electron/electron)
- [electron-userland/electron-builder](https://github.com/electron-userland/electron-builder)

But did not see any issues related to this.

**Comment by nyronium** [comment]
For completeness: I took a quick look at how node.js and other languages do JIT.
It somehow makes sense that NX is disabled, but it can be done with NX enabled.

Java for example has the NX bit set and also uses a JIT compiler. They solve it by `mmap`-ing a memory region just for the JIT executables and calling `mprotect` on it to allow writing and execution. This way the rest of the code is still NX, which is great.

In theory they could even alternate between `R-X` and `RW-` modes but I haven't found any resources on it.

**Comment by bryphe** [comment]
Cool, thanks for the follow up and additional context, @nyronium ! Do you think it makes sense to log an issue on one of our dependent projects, like Electron or v8?
