### ISSUE TITLE
How do I disable the automatically inserted closing brackets

### ISSUE THREAD

**Issue by LucianBuzzo** [onivim/oni#1144]
When inserting `(`, `[`, or `{` a closing character is automatically inserted.
How do I disable this feature? I looked in the wiki but couldn't see anything!

**Comment by bryphe** [comment]
Hi @LucianBuzzo ,

Here's the relevant section: https://github.com/onivim/oni/wiki/Language-Support#auto-closing-pairs

And `autoClosingPairs.enabled` is the relevant setting, which you can set to false in your configuration.

Hope that helps.

**Comment by bryphe** [comment]
Also added a link in the `Configuration` section of the Wiki, hopefully that makes it more discoverable in the future: https://github.com/onivim/oni/wiki/Configuration

**Comment by LucianBuzzo** [comment]
@bryphe Thanks a bunch
