### ISSUE TITLE
Disappearing Config.js

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1154]
@bryphe, this is an issue with development I believe as it occurred as a result of that, when running integration tests the users `config.js` is deleted and replaced then restored afterwards, if there is a break in the test process due to in my case the tests hanging and the process is killed manually there is the risk as happened to me of the config file not being restored 😭 . 

It seems like an edge case occurrence as I've run these tests several times before but is worrying that it can ever happen as Oni cannot load without a `config.js` and I didn't realise this was the cause for a while, as the app just hangs indefinitely.

I'm not sure whether or not these tests are intended to be run on CI servers exclusively 😖 but if not then its quite risky/problematic to have the actual user config interfered with whilst running tests, is it possible to have oni point to a fake config for testing purposes instead ? or default to its native config? or whether we specify that the path to search for the oni config is swapped using a `process.env.NODE_ENV=test` variable so it points to a config path for tests.

EDIT: this also raises the issue that if the `config.js` is missing for whatever reason there could/should be a fallback or a warning msg or perhaps immediately/ user is prompted to replace it with the default from oni

**Comment by bryphe** [comment]
Wow, impeccable timing, I just hit this too 😦 Super annoying... sorry about that!

The tests are _supposed to backup the config_ here:
https://github.com/onivim/oni/blob/57929c06a02fe6e886747bda45ac2c9412ccd2fd/test/common/runInProcTest.ts#L44

(To `_config.js`)

But it looks like that isn't working correctly.

> I'm not sure whether or not these tests are intended to be run on CI servers exclusively

Nah, it's important to be able to run them locally too! Especially to debug failures. The integration tests are a little awkward but we should definitely fix this pain point.

I think like you suggested, what we should do to make this more robust is to add a `--config` option, that can specify a config to load from (overriding the default config path). That way we don't have to do any of that copy-config craziness. Using an environment variable is good too - happy with either approach!

>  this also raises the issue that if the config.js is missing for whatever reason there could/should be a fallback or a warning msg or perhaps immediately/ user is prompted to replace it with the default from oni

We actually should handle this case today... I noticed though on my machine, the `NoInstalledNeovim` test failed, and left a config that caused Oni to hang (it pointed to a non-existing Neovim instance). It might be worth closing all instances and re-opening.

Sorry again you lost your config!
