### ISSUE TITLE
Persist Window Dimensions and Location on startup

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1155]
@bryphe I read [an article](https://blog.avocode.com/4-must-know-tips-for-building-cross-platform-electron-apps-f3ae9c2bffff) that illustrates how to persist window dimensions for an electron app. The end result being that oni will open in the same place at the same size as when it was closed. It's subjective whether or not users will want this but personally when I open any app I immediately have to resize it to where I want it to be which is typically split screen somewhere left or right. 

It seems you've already added the necessary infrastructure for persisting settings and the article goes through how to add this I wonder if this is something that would be desirable in your opinion if so I'd be happy to implement it possibly as a configurable option (although i'm not sure if the config object can be reached from `main.ts`

**Comment by bryphe** [comment]
Awesome! The article looks great, thanks for sharing it @Akin909 

> It's subjective whether or not users will want this but personally when I open any app I immediately have to resize it to where I want it to be which is typically split screen somewhere left or right.

I like this behavior by default. It seems like the best 'heuristic' where the user would want the window is where they had it last. If we find that it is not desirable, we can always add a configuration option to disable it, but I don't think it's necessary at this time. Lots of apps behave this way anyway.

> It seems you've already added the necessary infrastructure for persisting settings and the article goes through how to add this I wonder if this is something that would be desirable in your opinion if so I'd be happy to implement it possibly as a configurable option (although i'm not sure if the config object can be reached from main.ts

💯 this would be great! Yes, we use the [electron-settings](https://github.com/nathanbuchar/electron-settings) library which has a very similiar API to the one in the article. There's an example of using it to read the background color here (from `main.ts`):
https://github.com/onivim/oni/blob/57929c06a02fe6e886747bda45ac2c9412ccd2fd/main/src/main.ts#L70

(I used `_internal.lastBackgroundColor` to differentiate from configuration options, which I am also planning on storing here - like for #571, #840 . Perhaps we could use `_internal.windowState` to check this?) You can also write from the main process as well, nothing tricky there luckily.

Would be great to have this, if you're up for implementing it!

**Comment by Akin909** [comment]
Sure @bryphe  i'll have a go and make a PR when i've got it working
