### ISSUE TITLE
[b and ]b does not work when I disabled oni.useDefaultConfig

### ISSUE THREAD

**Issue by Dcryfm** [onivim/oni#1162]
I want the indentation of two spaces, so I disabled `oni.useDefaultConfig`, but `[b` and `]b` does not work.

**Comment by badosu** [comment]
@Dcryfm See: https://github.com/onivim/oni/wiki/How-To:-Minimal-Oni-Configuration on how to disable Oni's default config and allow for your own settings, like tabspace.

I use a similar setup and ]b and [b work.
