### ISSUE TITLE
Markdown Preview - Default style / color for links?

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1169]
I wonder if we can pick out a highlight color for the links, by default? The 'blue' color (highlighted) is hard to read on our default colorscheme 😄 

![image](https://user-images.githubusercontent.com/13532591/34236457-821b901a-e5ac-11e7-83eb-a79f0f69f8cd.png)

A reasonable one to use could be `highlight.mode.normal.background`, as that is the main highlight color we've been using elsewhere.

I just plugged it in to one link with the dev tools to try it out, and it looks decent:
![image](https://user-images.githubusercontent.com/13532591/34236534-db0b930a-e5ac-11e7-9dff-949e48b7919c.png)

**Comment by TalAmuyal** [comment]
Should be fixed by https://github.com/onivim/oni/pull/1181 (please verify).

**Comment by bryphe** [comment]
Just tried on #1181 - looks great!

![image](https://user-images.githubusercontent.com/13532591/34314114-70c73952-e725-11e7-84cf-d846d4e5ccc6.png)
