### ISSUE TITLE
Markdown Preview - Stutter when typing quickly while markdown preview is open

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1170]
When I was tweaking some markdown files with the Markdown Preview view open, I noticed that if I typed fast, I'd get a stutter in performance. I'd also see all the images reload.

Some ideas / observations:
- _Every_ buffer change triggers an update - we might want to add some `debounce` or `throttle` logic - this would preserve our typing performance, and redraw a bit less frequently (but if I'm typing very fast, I don't need to see every character rendered per se). RxJS is great for this - there's a decent article here: https://medium.com/aviabird/rxjs-reducing-number-of-api-calls-to-your-server-using-debouncetime-d71c209a4613 (It's more focused on API calls, but it's similarly applicable to our markdown preview logic)
- We always _redraw the entire markdown document_ - in some cases, like typing in insert mode, we're only updating a single line - it'd be cool if we could somehow incrementally update the markdown preview document. I'm not sure if there is a good way to do this with `marked`, though.

Here's a gif of me trying to exercise the issue:
![markdown-preview-fast-typing](https://user-images.githubusercontent.com/13532591/34236557-fe4b3636-e5ac-11e7-8814-c1686a163c15.gif)

Note that after I stop typing on the left, the preview window 'catches up'. I think this is where throttling/debouncing could help.

**Comment by TalAmuyal** [comment]
Should be fixed by https://github.com/onivim/oni/pull/1181 (please verify).

**Comment by bryphe** [comment]
This is much better now that the 'Loading Preview'  doesn't flash in.
