### ISSUE TITLE
Markdown Preview - Preview window scrolls to top when typing in insert mode

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1171]
Looks like when we are in insert mode, and type, the preview window always gets scrolled to the top, until we go back to insert mode. This isn't noticeable when typing near the top of a markdown document, but it does manifest when editing a document that is scrolled.

Repro:
- Open Oni's `README.md`, with markdown preview open
- Scroll part way (like the contributing section)
- Start typing

Expected: The preview window should stay in the same position, and I should see my updates
Actual: The preview window scrolls to the top

Here's a gif:
![markdown-preview-scroll-up](https://user-images.githubusercontent.com/13532591/34236706-a4f4436a-e5ad-11e7-8142-500472aeec7a.gif)

**Comment by TalAmuyal** [comment]
Should be fixed by https://github.com/onivim/oni/pull/1181 (please verify).

**Comment by bryphe** [comment]
Verified this is fixed now by #1181 - awesome!
