### ISSUE TITLE
Markdown Preview - Preview window can not support code block

### ISSUE THREAD

**Issue by saibing** [onivim/oni#1176]
![image](https://user-images.githubusercontent.com/5676390/34281739-9f6c529e-e6fb-11e7-9cab-8a5417bc24de.png)

**Comment by TalAmuyal** [comment]
Added to my list of followups.

**Comment by TalAmuyal** [comment]
Should be fixed by https://github.com/onivim/oni/pull/1181 (please verify).

**Comment by saibing** [comment]
@TalAmuyal 

Thank you very much, it work well now.

![image](https://user-images.githubusercontent.com/5676390/34315856-345c59b4-e7c2-11e7-851a-7c3d097670b9.png)

**Comment by bryphe** [comment]
Awesome, thanks @TalAmuyal ! I'll close this out.
