### ISSUE TITLE
Better integration with theme gruvbox

### ISSUE THREAD

**Issue by meijieru** [onivim/oni#1197]
Currently when work with gruvbox light, most of them are really well, except the tab. Anyway to improve it?

![image](https://user-images.githubusercontent.com/9511136/34439650-5c913cc4-ecea-11e7-85f2-db57d1d5e71e.png)

**Comment by Akin909** [comment]
@meijieru I don't think gruvbox is currently one of the supported themes so the theme you're actually seeing is the solarized theme (light) I think though not sure how have you set solarized anywhere in you're config by chance?

**Comment by meijieru** [comment]
@Akin909 No, it looks almost like the one in terminal. So I think it's gruvbox here.

**Comment by CrossR** [comment]
I'll close this out since @parkerault added the gruvbox themes (`gruvbox_light`/`gruvbox_dark`) as native Oni themes!

The PR was #2088 in case anybody ends up here and wants a nice template for making a native Oni theme.
