### ISSUE TITLE
Markdown not rendering correctly in hover (quick info)

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1202]
Reported on twitter:
https://twitter.com/iamunr/status/946763197842849794

[Screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2Y2y420L0q3m1F46462Y/image.jpg)

Looks like a bug in our rendering of quick info / hover - need to check and see what format the language server is sending it to us in. There are currently places where we don't render markdown when we should.

I believe this repros in our CSS language server.

**Comment by unr** [comment]
1. another example of non-escaped characters. (this one is from vue lang server I implemented myself, https://www.npmjs.com/package/vue-language-server
![image](https://user-images.githubusercontent.com/317957/34444332-701a7502-ec9b-11e7-868a-d53eba4a7c22.png)

2. seems to happen anywhere in scss (whether in a .vue file, or a .scss file)
![image](https://user-images.githubusercontent.com/317957/34444808-c4972744-ec9e-11e7-9cf3-de5ecd8bb9c7.png)

**Comment by bryphe** [comment]
Looks like this is fixed now with @Akin909 's hover improvements in #1253 (available in the latest release).
