### ISSUE TITLE
Relation with neovim lsp implementation

### ISSUE THREAD

**Issue by meijieru** [onivim/oni#1204]
Is there any relationship with the lsp-client which neovim will do?

**Comment by Akin909** [comment]
@meijieru so far oni has implemented its own lsp integration I didn't even know neovim was planning on implementing that. From the issues I've read so far and the fact that it currently implements it's own I'm thinking a valid response is no but @bryphe  would  be able to give a definitive response. Just to clarify do you mean `autoimzu/LanguageServerClient` or are you talking about an inhouse `neovim` lsp client?

**Comment by meijieru** [comment]
@Akin909 The inhouse one.

**Comment by Akin909** [comment]
@meijieru any chance you can link me to details on this for my info? has this been merged ? or is it a [WIP] the only reference I've found so far is neovim/neovim#5522

**Comment by meijieru** [comment]
https://github.com/neovim/neovim/pull/6856

**Comment by bryphe** [comment]
No relationship to `vim-lsp`  - we are actually using VSCode's library for language server integration - [vscode-jsonrpc](https://www.npmjs.com/package/vscode-jsonrpc). 

There's a few issues where we discussed approaches to LSP (using VimL plugin or Neovim integration vs JavaScript + vscode's libraries) - #6  #351

**Comment by bryphe** [comment]
Will close this out, since it doesn't look there is any action required. Let us know if you have further questions, though @meijieru
