### ISSUE TITLE
Feature: Filetype associations

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1213]
@brype whilst not really a native vim feature I think it might be nice for oni to support the ability to be selected as the default program for filetypes so that in a gui menu a user can select oni as the default program or double click a file to open it in oni.

I've found that implementing this simply requires entries for `electron-builder` in the package.json see [here](https://www.electron.build/configuration/configuration). Which i've done locally using

```json
    "fileAssociations": [
      {
        "ext": "js",
        "name": "javascript",
        "role": "Editor"
      },
      {
        "ext": "jsx",
        "name": "JSX",
        "role": "Editor"
      },
      {
        "ext": "py",
        "name": "Python",
        "role": "Editor"
      },
      {
        "ext": "go",
        "name": "Go Lang",
        "role": "Editor"
      },
      {
        "ext": "re",
        "name": "Reason",
        "role": "Editor"
      },
      {
        "ext": "vim",
        "name": "VimL",
        "role": "Editor"
      },
      {
        "ext": "ts",
        "name": "Typescript",
        "role": "Editor"
      },
      {
        "ext": "tsx",
        "name": "Typescript",
        "role": "Editor"
      }
    ]
  },
```

Whilst this allows `oni` to be set as the default program and to open files it seems that despite functionality to open files if passed arguments on launch, oni does not receive files passed to it on opening, (checked locally and the log re. `FilesToOpen` on init is empty).  I'm opening this to 
  1. Confirm this is functionality that you would like?
  2. secondly to ask for your insight re. why filepath may not be being passed to oni on init (its fairly hard to debug since a built version of the app is needed to test this functionality and I cannot see logs in main.ts)

**Comment by CrossR** [comment]
There is something like this already added for Windows at least, with a file extension list defined in https://github.com/onivim/oni/blob/master/build/BuildSetupTemplate.js#L35. The installer then asks if the user would like these mappings added, and adds them in they do.

That said, that way entirely deals with the adding of Registry keys to the Windows installer so is Windows specific, where as this looks like it works for at least Windows + MacOS, so this way should be better, though looks like it would remove the option for Windows user's to opt out of associations?

I can also confirm that the Windows implementation does work currently, so the passing of arguments seems to work there. There was an issue with it recently after the splitting of state, but it works on the latest master.

**Comment by Akin909** [comment]
@CrossR  thanks that's really helpful to know didn't realise it had been implemented at all, and also given that it works on windows it probably means that some mac specific issue re passing filetypes on opening with a gui icon is not working.

As for the filetype associations these according to `electron-builder` are designed to work cross platform so should cover everything hopefully although I still need to investigate why arguments aren't being passed on mac. 

Can i ask when you open Oni there is a log to the console of the `filesToOpen` argument, does this show the correct file for you? As that function seems to be where the logic for opening oni with a file is but I just want to cross check that there isn't some other handler elsewhere that's responsible for it working on Windows

**Comment by bryphe** [comment]
Awesome! I love this functionality on Windows that @CrossR added to our installer. Fun seeing the Oni icons all over my desktop 😄 

Definitely think it makes sense to include in OS X. I wonder if we can scope the `fileAssocations` to the  `mac` section in the package.json? Including them in the installer on Windows is ideal, to preserve the opt-out experience.

> Can i ask when you open Oni there is a log to the console of the filesToOpen argument, does this show the correct file for you? As that function seems to be where the logic for opening oni with a file is but I just want to cross check that there isn't some other handler elsewhere that's responsible for it working on Windows

It might be worth checking the main process logs here. You can check this by running `require("electron").remote.getGlobal("getLogs")()` in the console. Here's what i show when I open a file from explorer:
![image](https://user-images.githubusercontent.com/13532591/34492431-665d6d9a-ef9c-11e7-87c0-6c99579547f2.png)

Would be worth seeing what's happening there - I wonder if the file is being passed or picked up there? We may need to add additional logging here, too. This is the relevant spot where we pick up the args and hand them off to `loadFileFromArguments`:
https://github.com/onivim/oni/blob/ddfd1a1c3b6e8283c5d1fded3b97066aa2d4c01a/main/src/main.ts#L83

**Comment by Akin909** [comment]
@bryphe think you're right and the process.args aren't being passed in there as in `loadFileFromArguments` which triggers `startEditors` where I can log it seems there are no files passed so somehow on mac inside main.ts, the process arguments are getting lost or dont exist, I'll try the method you recommend to see if I can get logs for this

**Comment by bryphe** [comment]
> @bryphe think you're right and the process.args aren't being passed in there as in loadFileFromArguments which triggers startEditors where I can log it seems there are no files passed so somehow on mac inside main.ts, the process arguments are getting lost or dont exist, I'll try the method you recommend to see if I can get logs for this

Bummer! I know there were some tricky things for getting the shell integration hooked up, which is why we needed to add the `oni.sh` for mac. Do you happen to know if it is launching the executable directly, or going through the shell script?

> As for the separating the file associations, from the docs that doesn't seem possible but it only allows oni to be set as default file type but doesn't explicitly set this, so if the concern is that oni will automatically be set to the default file type that's not what this addition will do It will just give users on other platforms the opportunity to do what seems to be possible already on windows.

That seems reasonable, as long as it's not forcing the user to having Oni be the default app to open files. That would be painful for people who download it to try it out, not realizing we're taking over 😉 

Another option is you can set `Info.plist` options in electron-builder via the `extendInfo` setting: https://www.electron.build/configuration/mac . This seems like it could let us supply a custom `CFBundleTypeRole` / `CFBundleTypeExtensions` / `CFBundleDocumentTypes` (I'm not exactly sure which ones we need in Mac to make this work). But if the `fileAssocations` does what we want, that's great too (and easier!)
