### ISSUE TITLE
Get rid of .tern-port files

### ISSUE THREAD

**Issue by MikaAK** [onivim/oni#1232]
One of the issues I'm having in my JS projects is the creation of tern-port files. It seems you can turn them off with `--no-port-file` but I'm unsure of how to do that with Oni!

**Comment by Akin909** [comment]
@MikaAK i'm a big fan of tern myself and personally I just `gitignore` the port files it cool to know you can pass a flag can I ask where you've been passing the flag are you using tern directly or using `deoplete tern.js` or `tern.vim`?

**Comment by MikaAK** [comment]
https://github.com/ternjs/tern_for_vim/issues/12

**Comment by Akin909** [comment]
@MikaAK if tern isn't a language server which you've setup and from its site I don't believe it is I dont think that will work, I have the following flag in my vimrc a variable which `tern.vim` allows you to specify `let g:tern#arguments = ["--persistent"]` perhaps you can add the --no-port-file argument there

**Comment by MikaAK** [comment]
@Akin909  you were spot on. I don't know why I didn't think of this

**Comment by bryphe** [comment]
Nice catch, @Akin909 !
