### ISSUE TITLE
auto closing paires not working with quotes

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1258]
config part:
```js
{
    "autoClosingPairs.enabled": true,
    "autoClosingPairs.default": [
        { "open": "{", "close": "}" },
        { "open": "[", "close": "]" },
        { "open": "(", "close": ")" },
        { "open": "'", "close": "'" },
        { "open": "`", "close": "`" },
        { "open": '"', "close": '"' },
    ],
}
```

When I write a `(` I get `(|)` and I can type a `)` which leads me to `(foo)|` as expected. With quotes it doesn't work and I get `"foo"|""` instead.

**Comment by someguynamedmatt** [comment]
@hoschi What platform are you on? Mac? Linux? What version of Oni? I'm on `0.2.21` and I'm not seeing this behavior.

**Comment by hoschi** [comment]
Linux, Oni master fef2e10d1abf55bcb4126fbb5ed86cf5dde0ac4d

**Comment by jonaspm** [comment]
In 0.2.20 I suffer the same behaviour.
