### ISSUE TITLE
Rename action changes not only symbols

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1263]
```js
let put = 'fooo'
// put it down
let bar = {
    myString:'put'
}
```

When you try to use the rename feature on `put` the content of `myString` and the comment also gets changed, which I thought would not be the case. Shouldn't it only change it to

```js
let post = 'fooo'
// put it down
let bar = {
    myString:'put'
}
```

When I rename it to `post`?

**Comment by bryphe** [comment]
Thanks for the issue, @hoschi !

It looks like these are settings provided by the TypeScript language server:
https://github.com/Microsoft/TypeScript/blob/538d7e705f88381a452b6360e16be6ca51014451/lib/protocol.d.ts#L688

Seems like a reasonable default would be to set these as `false`.
