### ISSUE TITLE
Regression - Theming: Theme colors used by 'styled-components' are not updated when changing colorscheme

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1275]
__Repro:__
- Open Oni
- Edit `config.,js`
- Change colorscheme

Expected: The editor + all shell / chrome should be updated. (You can check 'QuickOpen' to validate)
Actual: Only the editor colorscheme is updated.

It seems that the `ThemeManager` we use with our `styled-components` isn't getting the updated colors.

**Comment by Akin909** [comment]
@bryphe had a very quick look at this and it seems that the `this.props.theme` that is being passed to the `<ThemeProvider />` isn't being update on `SET_CONFIGURATION` as `state.colors` is not updated in the redux store (from what I can see in the dev tools) so it doesn't cause a re render with the new colors

**Comment by bryphe** [comment]
Ah ya, good call - seems like we need to listen for the colors change and dispatch the `setColors` action against the `shell` store.

**Comment by Akin909** [comment]
@bryphe I can push a fix for that if you'd like/aren't already working on it?

**Comment by bryphe** [comment]
That would be awesome - thanks @Akin909 !
