### ISSUE TITLE
Quick Open Item Limit

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1281]
I can't see an issue for implementing a scroll bar or similar for Oni quick open, so thought I'd open one.

I hit issues when I have lots of files all with the same name.
I can't search more directly, since I've I forgotten where it is, so I just search for `main.tex` and then hope it is in the results.

Just opening this in case there needs to be any discussion about this, since I am not sure if there is any technical reasons for this to happen or not.

**Comment by badosu** [comment]
One possibility is to restrict the amount of results to a number that is manageable on screen, like 20 or 10.

For me it would make sense to expect a refinement of the quickopen query instead of allowing the user to delve into the options, the drawback is that it kills discoverability of options.

**Comment by bryphe** [comment]
Thanks for creating this issue, @CrossR . Definitely, this fits in with some of the other work we have with adding scrollbars + mouse behavior - like #166 , #163, #251, #501

**Comment by bryphe** [comment]
PR #1352 adds some scrollbars, so it may help, but I think it's still a bit awkward when you start searching and can't find an item.

Some fuzzy-finders have a 'refine' approach - where you could type `main.tex`, realize there's a bunch of them, but realize you're looking for the one in `research` folder, so you could then _refine_ the result by typing space + `research` (so the filter text would be `main.tex research`). This would turn the filter into a two-pass filter - first, filter all the results with `main.tex`, then filter all of those results with `research`.  In addition, if we sorted the search results by length, this might be a cheap way to make the fuzzy finder significantly more useful.

This would be useful for me in some similiar situations - do you think that 'refine' behavior would be helpful for you, @CrossR ?

**Comment by CrossR** [comment]
> This would be useful for me in some similiar situations - do you think that 'refine' behavior would be helpful for you, @CrossR ?

Sounds like it would be! There is a bunch of times where I will search and either realise where I should have been searching, or see in the search results its searching over in X folder, and I might not know fully where it is but I do know its probably in Y folder instead.

That + a scroll bar + the search in the explorer sidebar that I think was mentioned in the current release notes would put Oni at the same level or higher than any solutions I use currently for finding files.

**Comment by CrossR** [comment]
Going to close this issue out in favour of a more specific issue for adding a second pass feature to the quick open window and similar.
