### ISSUE TITLE
Three dots appear on tab through wildmenu

### ISSUE THREAD

**Issue by khalidchawtany** [onivim/oni#1292]
When I tab through the wildmenu results (using `tab`, `ctrl+n`, or `ctrl+p`) I get three dots at the bottom of the screen for each key press.

This happens even If the wildmenu result is empty.

![screen shot 2018-01-14 at 10 41 34 pm](https://user-images.githubusercontent.com/1681606/34919970-3bc54ae6-f97c-11e7-86ca-c2f0d6ee79d3.png)

**Comment by bryphe** [comment]
>  @bryphe what would your thoughts be on hiding the cursor while the wildmenu is active so it doesn't output anything though that seems like a complex solution to what might be a bug from neovim?

I was just poking around, and it looks like this was already found / identified in Neovim's repo with #7689 - and fixed with #7692. @bfredl rocks! 😄
 
I'll tag this with `neovim-core`, and we can close it when we pick up the next Neovim version.

**Comment by CrossR** [comment]
I'll close this out since we have the next neovim version in master now!
