### ISSUE TITLE
[BUG] Block cursor "bursting" on navigation

### ISSUE THREAD

**Issue by nwaywood** [onivim/oni#1294]
As you can see from the gif below, whenever the cursor moves it bursts at the top by 1 or 2 pixels (I can't exactly tell) which is rather distracting.

![oni_burst](https://user-images.githubusercontent.com/3773641/34928492-0702af6a-fa12-11e7-97a9-204be16abedc.gif)

**Comment by CrossR** [comment]
Have you tried with `"ui.animations.enabled"` set to `false` in your `config.js`?
Config options still aren't the easiest thing to discover but that should fix it!

If nobody else has picked up #976, I might look into moving the default options over when I'm done with some of my masters work at the end of this week.... Would at least help cases like this to be discovered more easily, whilst we get a better system.

**Comment by bryphe** [comment]
Nice find @CrossR !

> If nobody else has picked up #976, I might look into moving the default options over when I'm done with some of my masters work at the end of this week.... Would at least help cases like this to be discovered more easily, whilst we get a better system.

Yes, this would be great! It's tough to discover them at the moment - having them all there would be much improved. Good luck with wrapping up the masters work 😄

**Comment by nwaywood** [comment]
Yes, setting `"ui.animations.enabled"` to `false` got rid of the bursting. I was aware of that option but I didn't think to try it because I assumed this was a bug and not a feature.

Sorry for the inconvenience, keep up the great work guys!
