### ISSUE TITLE
Clipboard Integration: Deletes

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1297]
The current clipboard integration default behavior is a bit unintuitive:

From twitter:
Yeah, when this is on....

1. copy text
2. open oni
3. delete text 
4. paste.... the text I just deleted.

If I turn it off...

1. copy
2. oni
3. delete text
4. paste.... but it doesn't paste.
Typing Cmd+v only types 'v'

It's confusing that delete overrides what gets pasted in Oni.

**Comment by bryphe** [comment]
Reasonable fix here would be to split out the synchronization back to the clipboard - we could add a setting for:
`editor.clipboard.synchronizeYank` (default `true`)
and
`editor.clipboard.synchronizeDelete` (default `false`)

**Comment by kopischke** [comment]
It would also be reasonable to _always_ bind the system clipboard shortcuts (i.e Ctrl-/Cmd-C, -X and -V) to equivalent Vim operations, integration or not: anybody using these instead of Vim commands probably expects them to work in OS wide fashion. AFAIK, that is what MacVim does…

**Comment by bryphe** [comment]
> It would also be reasonable to always bind the system clipboard shortcuts (i.e Ctrl-/Cmd-C, -X and -V) to equivalent Vim operations, integration or not: anybody using these instead of Vim commands probably expects them to work in a OS wide fashion. AFAIK, that is what MacVim does…

Agreed - this is actually enabled today with our default set of key bindings. (well, at least Ctrl/Cmd-C and V... I don't believe `X` is hooked up at the moment).

**Comment by bryphe** [comment]
Fixed now with #1342
