### ISSUE TITLE
Input: '<space>' should be used for bindings, as opposed to the literal space character

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1300]
Repro:

- Add  `oni.input.bind("<space>", () => { alert("hi") })` to your config, save.

The `alert` should show, but does not.

Note that if instead you use an explicit space character via `oni.input.bind(" ", () => { alert("hi") })`, it works.

This is not ideal, because this is sensitive to whitespace trimming - we should be using the explicit `<space>` instead.

**Comment by someguynamedmatt** [comment]
@bryphe Been a while since I've expolored through the codebase. Would you be able to point me towards the file that reads from the users config file? In other words, whichever file parses their settings?

Thanks!

**Comment by bryphe** [comment]
Hi @someguynamedmatt , good to see you here again 😄 

> Would you be able to point me towards the file that reads from the users config file? In other words, whichever file parses their settings?

For sure - this is the file that loads the user's configuration file:
https://github.com/onivim/oni/blob/a5cbb53fce654c0047cd60f46a48028e84e53ff4/browser/src/Services/Configuration/FileConfigurationProvider.ts#L115

And the input stuff - the implementation of `oni.input.bind` - is here:
https://github.com/onivim/oni/blob/a5cbb53fce654c0047cd60f46a48028e84e53ff4/browser/src/Services/InputManager.ts#L28

**Comment by someguynamedmatt** [comment]
@bryphe Fantastic! Thanks! I'll start messin' around with it when I get a free moment.

**Comment by bryphe** [comment]
Fixed on master w/ #1333 - thanks @someguynamedmatt !
