### ISSUE TITLE
Neoterm :Ttoggle command crashes Oni

### ISSUE THREAD

**Issue by nwaywood** [onivim/oni#1304]
Steps to reproduce:

1. Install the [neoterm](https://github.com/kassio/neoterm) plugin (I installed via `vim-plug`)
1. Restart oni
1. Execute `:Ttoggle` (a command from neoterm that toggles a `:term` buffer)

The result of following the above steps is that oni crashes and the window goes completely black with the following error in the dev tools console:

![image](https://user-images.githubusercontent.com/3773641/34970980-d9735f30-facb-11e7-9675-7f79263501bc.png)

Please let me know if you require any additional information

**Comment by Akin909** [comment]
@bryphe  think is the same error as #1295 I've found that it also occurs in other circumstance as @nwaywood has observed, I also find that it occurs when checking for changes in recent updates in `vim-plug`, I added some notes as to what I've found looking into the cause but am not very familiar with the `oni-layer`/`windowManager` setup

**Comment by bryphe** [comment]
Thanks for the all the details, @nwaywood ! Very helpful to have the screenshot. And thanks for your investigation @Akin909 - does look like another manifestation of the issue in #1295 . I'm just investigating it now, I'll resolve this as a duplicate and track the fix against #1295 .
