### ISSUE TITLE
Pre-Push +/- Pre-Commit hooks

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1317]
@bryphe  this issue is aimed primarily at development, I'm not sure what your feeling might be regarding setting up `prepush` +/- `pre-commit` hooks for oni which at the very least run `tsc` and `yarn lint` commands to avoid situations where a developer might push code which was inevitably going to fail in CI as they didn't run linting or tsc before hand I personally find that I forget all the time and locally and at work use [`husky`](https://github.com/typicode/husky) which is an npm package that sets up a dev's `git` folder with a pre-push hook.

As for pre-commit hooks I personally them a little hit and miss as they can interrupt the flow of developing but its also possible to run things without verification.

Also related but definitely more controversial is the idea of using the spectacular [`Prettier`](https://github.com/prettier/prettier) auto formatter (I'd suggest having a look at its repo if you're unfamiliar with it as its very much unlike other auto-formatters in the way it works) to run pre-push or pre-commit to format all repository code. Whilst I appreciate that people tend to be quite invested in how they format code using an opinionated formatter like prettier can ensure that the formatting of the code base is always consistent with a few preset rules, and that there aren't disparate areas of unique formatting which don't match other areas, whilst tslint provides some guards which are more about say preferring arrow functions etc. 

`Prettier` is just very robust means of formatting code which is I would say far more advanced at actually *re-formatting code* . This would be more about consistency as hopefully `oni` grows and hopefully gets more contributors and differences become more apparent. Also it would require no effort on the contributors part to ensure their code matched with the rest of the code base, as prettier would just run and only fails if the code has parsing errors in it in which case it just fails and the hook itself should fail.

Either way depending on your feeling I am happy implement the simple hooks pre-push for linting and tsc or if you're interested in `prettier` I can set that up as well.

**Comment by bryphe** [comment]
Thanks for logging the issue, @Akin909 ! Always interested in ways we can improve the developer experience 👍 

>  I'm not sure what your feeling might be regarding setting up prepush +/- pre-commit hooks for oni

I'm not really a fan of pre-commit hooks - we have them on the https://github.com/onivim/onivim.io repo and they add significant friction to the development process. MO part of the power of git is how easy it is to branch, experiment, roll back, and having commit hooks gets in the way of that quick experimentation.

A push hook might be OK as long as it doesn't get in the way.

> As for pre-commit hooks I personally them a little hit and miss as they can interrupt the flow of developing but its also possible to run things without verification.

Sounds like we're on the same page here - anything that gets in the way of flow for developing is a no-go for me 😄 

> Also related but definitely more controversial is the idea of using the spectacular Prettier auto formatter (I'd suggest having a look at its repo if you're unfamiliar with it as its very much unlike other auto-formatters in the way it works) 

I'd be open to using a solution like `Prettier` to enforce a canonical coding style (potentially hooking up to a pre-push hook). I know at work for me there are _huge_ discussions around coding style and everyone has different opinions - having an enforced solution just eliminates that entire class of issues.

A few questions I have:
- Does `Prettier` work well with TypeScript? Looking like this it seems there is official typescript support: https://github.com/prettier/prettier/issues/13
- Are there cases where `tslint` and `Prettier` would clash? In other words, cases where `Prettier` might format something that `tslint` flags as an error?
- Would it still make sense to have our `fix-lint` commands (where we pass `--fix` to `tslint` and it fixes whitespaces issues, etc)?

So I'd be open to exploring hooking up tsc/lint/prettier as a _pre-push_ hook, if you're up for checking that out! Thanks for the suggestions!

**Comment by Akin909** [comment]
@bryphe I currently use Prettier at work on a Typescript codebase with `tslint`, so can definitely vouch for Typescript support.

As for `tslint` there are plugins that ensure they work together, however I feel those aren't necessary as long as each is used to for the *right* 😉 thing. 
The things that prettier cares about are aesthetic things like enforcing indentation and spacing and semicolons `prettier` should be left in charge and as far as coding style like arrow fns, method ordering, ununsed imports etc. `tslint` can be left in charge.

Prettier despite being opinionated fortunately/unfortunately has about 5 config options which we can set as you'd like and leave those to prettier, so running `tslint` should never conflict with prettier if each is configured correctly.

**Comment by bryphe** [comment]
Excellent! Let's go for integrating it then.

> As for tslint there are plugins that ensure they work together, however I feel those aren't necessary as long as each is used to for the right 😉 thing.

Agreed, sounds like complexity we don't need 😄 As you mentioned sounds like we just need to make sure there aren't conflicting configurations.

> Prettier despite being opinionated fortunately/unfortunately has about 5 config options which we can set as you'd like and leave those to prettier,

Perfect! Let's just pick the ones closest to the existing style.
