### ISSUE TITLE
Session loading broken

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1324]
I use CtrlSpace for this but the built in `:source Session.vim` created by a previous `:mksession` call gives the same error.

https://github.com/onivim/oni/blob/a667ab845eec1a233d7d40949dd3f99e4b505b04/browser/src/Editor/NeovimEditor/NeovimLayersView.tsx#L43
Calls the dimension function which tries to call a not existing function:
![2018-01-19-153054_1333x612_scrot](https://user-images.githubusercontent.com/163128/35155402-c8231ee6-fd2d-11e7-8806-c75217e1187d.png)

With a prod build the whole window gets the background color. In debug mode you can skip over the errors and you will at least can work with Oni while debugging it.

**Comment by bryphe** [comment]
This looks like a dup of #1295 - have PR #1309 out to address it... just need TravisCI to come back to life 😄
