### ISSUE TITLE
TS Error on `npm run build`

### ISSUE THREAD

**Issue by someguynamedmatt** [onivim/oni#1332]
Off the latest pull of master:
Arch Linux 4.14.13-1-ARCH
Node 8

`npm run build` throws:

```
ERROR in ./browser/src/UI/components/StatusResize.tsx
(103,23): error TS2345: Argument of type '(state: Readonly<State>) => { children: { [x: string]: { id: string; width: number; alignment: nu...' is not assignable to parameter of type 'State | ((prevState: Readonly<State>, props: Props) => State | Pick<State, "children" | "containe...'.
  Type '(state: Readonly<State>) => { children: { [x: string]: { id: string; width: number; alignment: nu...' is not assignable to type 'Pick<State, "children" | "containerWidth">'.
    Property 'children' is missing in type '(state: Readonly<State>) => { children: { [x: string]: { id: string; width: number; alignment: nu...'.

ERROR in ./browser/src/UI/components/StatusResize.tsx
Module build failed: Error: Typescript emitted no output for /home/my/code/oni/browser/src/UI/components/StatusResize.tsx.
    at successLoader (/home/my/code/oni/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/home/my/code/oni/node_modules/ts-loader/dist/index.js:21:12)
 @ ./browser/src/UI/components/StatusBar.tsx 7:0-42
 @ ./browser/src/UI/Shell/ShellView.tsx
 @ ./browser/src/UI/Shell/Shell.tsx
 @ ./browser/src/UI/Shell/index.ts
 @ ./browser/src/index.tsx
 @ multi ./browser/src/index.tsx
```

Not sure if this is my particular environment or what, but it's confusing. I don't see other builds failing as a result of this.

**Comment by bryphe** [comment]
Ah ya, looks like @TalAmuyal ran into this on our [gitter](https://gitter.im/onivim/Lobby) the other day too.

I believe that there is a React typing that was updated that is causing this - you can do the following to resolve:
- Grab the latest master - `git pull origin master`
- delete your `node_modules` folder (`rm -rf node_modules`)
- Run `yarn install`
- Run `npm run build`

Let me know if you're still seeing issues after those steps. If you don't have `yarn`, you might need to install it via `npm -g yarn`. Hope that helps!

**Comment by someguynamedmatt** [comment]
Gitter, nice.

Didn't even think to try the installs with `yarn`. Thanks @bryphe that solved it!
