### ISSUE TITLE
Feature: autocomplete aliases

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1367]
Whilst completing file paths, `oni`'s file completion which I imagine is provided by the `lsp` does not provide path completion if a `webpack` or similar alias is used for the file, to clarify it provides general completion but not for subfolders within the *aliased directory*. I'm not sure if this is a configuration option or is specifically implemented by other editors but what I have observed is that in the case of `typescript` vscode (which uses the same lsp) and other editors like webstorm are able to complete paths including aliases e.g. `@redux` is set as a webpack alias (and tsconfig) alias to `app/src/redux` this path is resolved by vscode in this example so completion results include contents of `app/src/redux`.

At present it seems the `lsp` can recognise if an alias is accurate for example `@redux/src/someFileTypo` will show an error marker until the typo is fixed as expected, but in completing this autocomplete options do not include any files or subfolders. 

From the documentation of the typescript lsp it seems a little unclear whether it provides this functionality out of box but mentions
>  textDocument/completion (incl. completion/resolve)

but its unclear if this refers to aliases. Tbh without the support of the lsp this would be very complex to implement so this issue is more for exploring that Oni is using all the available completion options rather than to suggest this be implemented from scratch 😟

**Comment by bryphe** [comment]
I would guess that the TypeScript standalone server gives us this, but we're not respecting the meet - we might not be seeing `@` or the path as a character we should expand completions for.

This is the spot in the code where we figure out where the completion 'meet' is and where we should query from - https://github.com/onivim/oni/blob/a4f81102ce883c5f0c1519b9cd91998418bbb7ff/browser/src/Services/Completion/CompletionStore.ts#L227

I'm curious if we're getting a completion meet in this case. We might need to add `@` as a trigger character.

**Comment by Akin909** [comment]
For reasons unknown this suddenly works quite well Yay so closing (could have been an update in the `tss` 🤷‍♂️
