### ISSUE TITLE
Oni fails to start if persisted folder no longer exists

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1381]
When oni initialises it now looks for a persisted folder and executes a `changeDirectory` however this command does not check to see if the directory it is passed exists, as such in my case where I opened a folder in oni, later moved the folder outside of oni and closed oni, my next attempt to open Oni results in a blank screen which hangs indefinitely.

Running `oni --debug` the console shows an error as the folder that oni is trying to navigate to does not exist which halts the whole startup process, in order to resolve this as the persisted setting holds every time I opened oni manually called `Oni.workspace.changeDirectory('valid/path')` and restarted.

A solution to this is that the `changeDir` function should always check that the directory it is passed is valid before attempting to switch to it. A more general issue is that I think every function or rather main startup process should have a `try/catch` or some form of error handling so that oni doesn't end up hanging without any feedback given back to the user

**Comment by bryphe** [comment]
Thanks for catching this, @Akin909 ! This is a bad bug - really appreciate you finding it, investigating it, and fixing it 😄 

> A solution to this is that the changeDir function should always check that the directory it is passed is valid before attempting to switch to it 

Makes sense to me.

> A more general issue is that I think every function or rather main startup process should have a try/catch or some form of error handling so that oni doesn't end up hanging without any feedback given back to the user

Definitely - this is one thing that worries me about the persisted settings. The worst case is bugs like these where the editor doesn't even start. Having a more robust path here will be important. Logged #1383 to track this.
