### ISSUE TITLE
Oni Directory Navigate to Project Root Option

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1385]
When working on a project, I usually have this under some form of version control (90+ % of the time) so I use [`vim-rooter`](https://github.com/airblade/vim-rooter), which is a `viml` plugin that automatically sets vim's directory to that of the *current buffer's __project__ root* which it identifies by looking for a `.git, node_modules` and various other config files (the preceding were just examples).

I think as a configurable option It would be very handy to have `oni` be able to replicate this functionality as for example any project wide command a user might run is likely intended for the project or if you do a search in project the starting dir I think as a good default should be the project root *for the file being edited*. Also I think unless specifically sought by the user, *opinion alert*  whilst working on a buffer Its most useful to have oni pointing towards that buffer's project root, which could be very handy with the file explorer as the explorer's contents could reflect the current files project root from buffer to buffer

**Comment by bryphe** [comment]
Thanks for the suggestion, @Akin909 ! Agree, this would be good functionality to have - we're becoming more dependent on having a workspace for features like explorer/search, so guiding users to that path will improve the expreience.

> Also I think unless specifically sought by the user, opinion alert whilst working on a buffer Its most useful to have oni pointing towards that buffer's project root, which could be very handy with the file explorer as the explorer's contents could reflect the current files project root from buffer to buffer

Yes, makes sense. We could have an option for `workspace.autoDetectWorkspace` based on buffer enters (and have the sort of files that identify as a project configurable). I could see the following behavior:
- __`always`__ - we always switch the workspace root if it's different - even if there is already a workspace open
- __`noworkspace`__ - we switch to the workspace root for a file, if a workspace isn't already open
- __`never`__ - we never auto-switch workspaces

`noworkspace` would be a reasonable default, it's conservative. I like us switching to a workspace,. as most features like the explorer/search are really only useful if there is a workspace.

We could also have a configuration of `"workspace.autoDetectRootFiles": [".git", "node_modules", ..etc]`

**Comment by Akin909** [comment]
@bryphe not really the best place for this comment but there's no associated issue really, essentially the start screen was only opening up to an empty buffer called "WELCOME" with no content I've narrowed down the cause to `vim-rooter` plugin which on `vimEnter, bufEnter` etc switches vim's directory to a project root or leaves it in the current dir if there is no directory, not sure or why exactly but with the plugin enabled the welcome page doesn't appear.

I've raised it here as potentially with this option in place something like vim rooter won't be required although changing the workspace dir is currently not equivalent to changing  vim's directory
