### ISSUE TITLE
Navigating file explorer Quirks

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1396]
@bryphe given you're looking to get the file explorer into the next release wanted to give some feed back on issues I've noted (following on from the gitter conversation).

As I mentioned with my own `init.vim` enabled I find that pressing `j` or `k` causes the cursor to occasionally jump over nodes in the tree. I've tried deactivating my config which actually results in an error which crashes oni.

<img width="814" alt="screen shot 2018-01-30 at 08 15 44" src="https://user-images.githubusercontent.com/22454918/35555415-00cddd14-0597-11e8-99b8-0f70898641c0.png">

Will do some more digging and add a screen cast to illustrate the issue shortly.

**Comment by Akin909** [comment]
@bryphe I set `useInitVim: false, useDefaultConfig: true`, I will try again a bit later and share a screen cast of the jumping and see if I can find more details re the crash.

**Comment by Akin909** [comment]
### Screencast: 

@bryphe here's a screen grab of the error whilst it occurs haven't had a chance to try without my config again yet
![explorer](https://user-images.githubusercontent.com/22454918/35596870-a50aa2c8-0613-11e8-8fc9-bc5ed9c09e99.gif)

**Comment by Akin909** [comment]
Just tried again with my config disabled and was able to get the full navigation. I'm thinking that it might be a good idea to temporarily remove a user's default `h,j,k,l` binding whilst in the file explorer so their mappings don't override the explorer's then restore them afterwards which Is what loads of vim ui plugins like `NERDTree` do, wasn't able to reproduce the crash 😟

**Comment by Akin909** [comment]
I ended up implementing the functionality to temporarily save, remove then restore a users bindings only to discover that the bug persists despite this 😭 , I was so sure it was due to the bindings I didn't try a simple `unmap` to see if that helped. Anyway It seems like potentially very useful functionality to have for many reasons like a user using an oni config to set their vim keybindings etc. so can make PR if you'd like to see the work that entailed. 

Re. this bug ill keep looking but if you have any ideas re the movement issues, I'm having the same on the welcome screen i.e. I'm unable to use the onivim navigation

**Comment by bryphe** [comment]
Thanks for all your help here, @Akin909 ! It's helpful to know that turning off the config made it work (there were some other bugs related to navigation that I thought I fixed, so I wasn't sure if it was still those or something else).


> I'm thinking that it might be a good idea to temporarily remove a user's default h,j,k,l binding whilst in the file explorer so their mappings don't override the explorer's then restore them afterwards which Is what loads of vim ui plugins like NERDTree do, wasn't able to reproduce the crash 😟

Seems reasonable. We actually use a _second_ Neovim instance for these 'extra-UI' pieces, like the sidebar, panes, and welcome screen - we could switch that to not load the users `init.vim` at all. Might be safer to minimize conflicts in those cases!

> I ended up implementing the functionality to temporarily save, remove then restore a users bindings only to discover that the bug persists despite this 😭 , I was so sure it was due to the bindings I didn't try a simple unmap to see if that helped

Oh man sorry you went to those lengths! I'm guessing this might not have worked if it was run against the _main_ Neovim instance.
