### ISSUE TITLE
Quick Open uses relative path sometimes.

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1397]
Occasionally, QuickOpen seems to use a relative path.

As far as I can tell, the repo is as follows:

* `Ctrl+Shift+P` and Close the current Workspace.
* Close Oni, then re-open.
* `Ctrl+Shift+P` and Open a new workspace.
* `Ctrl+P` and open a file.

When I do this, I'll have Oni trying to open `browser\src\Font.ts` instead of `F:\Git\oni\browser\src\Font.ts`.

Clicking in the Explorer works, so I assume the fix for always using the full path wasn't applied to the quick open window. Closing and reopening Oni fixes this for QuickOpen.

**Comment by bryphe** [comment]
Thanks for testing this out, @CrossR , and finding a repro. Unfortunately, it doesn't seem to reproduce for me on my following those steps.

A couple of troubleshooting questions after the 4th step:
- What's the value of `process.cwd()` in the dev tools?
- What's the value of `Oni.workspace.activeWorkspace` in the dev tools?
- What's the value of `Oni.editors.activeEditor.neovim.request("nvim_command_output", [":pwd"]).then((out) => console.log(out))` run in the dev tools?

It seems like the path is getting out of sync somehow. When we set the workspace path in step 3, i'd expect it to be set for both Neovim and the workspace. That assumption might not always be true if users have different configurations for managing the active neovim directory - if that's the case, we might be safer figuring out the full path from the 'QuickOpen' experience and sending that, as opposed to assuming neovim is always in sync. But knowing the values of those bullets above can help us see where it is breaking down.

**Comment by CrossR** [comment]
If I repeat the steps listed, the values are as follows:
* `F:\User Files\My Documents\Git\oni`
* `"F:\User Files\My Documents\Git\oni"`
* `C:\Program Files (x86)\Oni`

If I then close and re-open Oni, where the QuickOpen works again I get `"F:\User Files\My Documents\Git\oni"` for all 3.

I guess from that it looks like Oni is updating the location it uses, but Neovim isn't being updated since `:pwd` isn't correct.

**Comment by CrossR** [comment]
This has changed for me, I now can't seem to open anything from QuickOpen as all paths are now relative, even after closing and reopening Oni.

Running the tests mentioned above gives the following:
-`F:\User Files\My Documents\Git\oni`
-`"F:\User Files\My Documents\Git\oni"`
-`C:\Program Files (x86)\Oni`

I'm running the latest build of master, that is d0f3cca.
Not fully sure what changed to cause this though.

**Comment by Akin909** [comment]
@CrossR I'd been wondering what was going on I get this issue as well or rather quite often seemingly randomly when I try and open a file it just opens a non-existent buffer with what is now clicking is only part of the path.

One very clear place I know where this is definitely not in sync is `workspace.changeDirectory` I looked at this function when working on `autoDetectWorkspace` and noted it definitely doesn't inform vim of the change which @hoschi pointed out in #1575, I'm not sure if its setup somewhere else to update vim of the change but thats definitely a place it needs hooking up.

It seemed like a step I definitely was thinking to add when working on it but as @bryphe pointed out if a user has `autochdir` setup or is using a plugin like `vim-rooter` things are still going to go out of sync

I wonder if as well as informing vim of the change it isn't worth having things that open files always use absolute paths?

**Comment by bryphe** [comment]
> I wonder if as well as informing vim of the change it isn't worth having things that open files always use absolute paths?

👍 , using absolute paths seems like the safest fix in QuickOpen
