### ISSUE TITLE
Definition underline not correctly placed

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1407]
Since very recently when the cursor rests on a `symbol` the definition underline is not located underneath the symbol sometimes it rests off to the side a little or by several words or is below by several lines or does not appear at all.

The errors I'm getting are mainly `react key warnings` and one regarding the `oni-layer-browser` plugin and `rxjs` (which I believe) is a separate issue  I was going to raise.

screenshot:

<img width="462" alt="screen shot 2018-01-31 at 11 44 38" src="https://user-images.githubusercontent.com/22454918/35621501-68a513a4-067c-11e8-9763-6705c80fc4ae.png">

**Comment by Akin909** [comment]
To be closed once I confirm that this relates to changes to #1318 I'm running locally following removing using the document viewport.

**Comment by Akin909** [comment]
Screen grab:

![underline](https://user-images.githubusercontent.com/22454918/35629232-fa49d380-0695-11e8-9d73-b872819d4ccb.gif)

Not sure if the definitions is one component that is constantly re-rendered in a different place or an array but if it is an array then this feels like the kind of bug would occur if keys are not set properly.

**Comment by bryphe** [comment]
Ah nice catch, thanks for the issue @Akin909 !

**Comment by bryphe** [comment]
Should be fixed now with #1454

**Comment by Akin909** [comment]
indeed this does appear to be fixed, thanks, closing
