### ISSUE TITLE
Oni's "open folder" command does nothing

### ISSUE THREAD

**Issue by jad** [onivim/oni#1427]
To reproduce:

* Download the latest version of Oni.
* Launch Oni.
* From the "Oni" item in the menu bar, select "Open Folder..."

Nothing happens. I made a [recording](https://www.dropbox.com/s/7059uinwokbs5hy/oni-open-folder.mov?dl=0) of the problem.

**Comment by CrossR** [comment]
This should have been fixed on master (#1393) but a new release hasn't been made yet.

Next release is aimed for around the 12th Feb as far as I know, or you could build from master where this should be fixed.

**Comment by jad** [comment]
Thanks for the info. I did a build and that functionality now works. The 12th is almost 2 weeks away and "open folder" seems like a pretty foundational feature to leave broken for that long. You might want to consider cutting a hotfix release so others don't run into the same problem.

**Comment by bryphe** [comment]
Thanks @CrossR and @jad for verifying the new functionality!

Just an FYI - there is a workaround of opening the command palette - `Control+Shift+P`, `Close Folder`, and then `Open Folder`. It's not ideal, but I wanted to make sure it's here in case someone else hits this. I will consider a hot fix build in the interim.
