### ISSUE TITLE
Automation: CiTests - show error at bottom

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1439]
Another issue from #1415 - the error we get at the bottom isn't very descriptive (it's just from the main process, telling us the test case failed). There is usually a more detailed error message inside the test - we should make sure that is shown, so that the developer doesn't need to scroll around or search for an error. Having the context around the error can save a lot of time in terms of troubleshooting.

**Comment by someguynamedmatt** [comment]
PR #1474

**Comment by bryphe** [comment]
Fixed now by #1474 - thanks @someguynamedmatt !
