### ISSUE TITLE
File explorer: Improve truncation/overflow strategy

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1446]
Currently labels for files and directories can be offset, overflown hidden or wrapped in a new line depending on the state of the file explorer pane:

### Hidden

![screenshot from 2018-02-06 15-50-07](https://user-images.githubusercontent.com/347552/35875205-b0a2f256-0b55-11e8-83a1-acd08b0ea0d7.png)

### Offset

![screenshot from 2018-02-06 15-52-28](https://user-images.githubusercontent.com/347552/35875238-c39461b0-0b55-11e8-8ee6-95e3eff4fac1.png)

### New line

![screenshot from 2018-02-06 15-53-11](https://user-images.githubusercontent.com/347552/35875275-dd21bd94-0b55-11e8-88a1-a2fb30451ca7.png)

**Comment by bryphe** [comment]
This should be addressed now by #1473 (still need to add resize functionality to the sidebar, though!)
