### ISSUE TITLE
Deoplete python process high usage

### ISSUE THREAD

**Issue by Sandee022** [onivim/oni#1447]
I am using deoplete for php completion but when i quit oni, python processes not exiting instead taking high cpu usage.

**Comment by bryphe** [comment]
Thanks for logging the issue, @Sandee022 . How are you exiting Oni? Via `:q`?

**Comment by Akin909** [comment]
ah I'd been thinking about whether or not to raise a similar issue (wasn't sure if it was an electron issue or oni issue). I've noticed as well that things like language server processes remain open after `oni` exits not sure if this is an issue with electron or `oni` has to manually kill all its child processes when it closes in a `pre-quit` handler. I've not personally noticed a pattern with this I use `cmd-q` or `:q!` and I believe it happens regardless. It's especially noticeable if I had multiple oni windows open

**Comment by Sandee022** [comment]
Yes with :q and :q! too.

**Comment by bryphe** [comment]
Interesting - sounds like two potential issues:
- In the Neovim / deoplete cases, Neovim is managing the lifetime of the python processes - so I'd expect that when we quit, Neovim would kill those processes.
- For the oni language server processes, we manage the lifecycle of those, so it's possible we're not doing proper cleanup on exit.

**Comment by Sandee022** [comment]
Deoplete has fixed this issue.
