### ISSUE TITLE
Install from source failure, maybe related to cross-spawn 

### ISSUE THREAD

**Issue by Canop** [onivim/oni#1460]
I followed the instructions [here](https://github.com/onivim/oni/wiki/Development#first-build)

So I did

    yarn install
    npm run build
    npm link

During the execution of `npm run build` I got this warning:

```
WARNING in ./node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'spawn-sync' in '/home/dys/dev/oni/node_modules/cross-spawn'
 @ ./node_modules/cross-spawn/index.js 32:26-47
 @ ./node_modules/shell-env/node_modules/execa/index.js
 @ ./node_modules/shell-env/index.js
 @ ./browser/src/Plugins/Api/Process.ts
 @ ./browser/src/Services/Language/LanguageClientProcess.ts
 @ ./browser/src/Services/Language/index.ts
 @ ./browser/src/index.tsx
 @ multi ./browser/src/index.tsx
```

And `npm link` failed with this error:

```
An unhandled error occurred inside electron-rebuild
ENOENT: no such file or directory, open '/home/dys/dev/oni/node_modules/execa/node_modules/cross-spawn/package.json'

Error: ENOENT: no such file or directory, open '/home/dys/dev/oni/node_modules/execa/node_modules/cross-spawn/package.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! oni@0.2.22 postinstall: `npm run install:plugins && electron-rebuild && opencollective postinstall`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the oni@0.2.22 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

What did I do wrong ?

OS: Ubuntu 16.04
Node: v8.9.3

**Comment by someguynamedmatt** [comment]
Hey @Canop

I get the same issue on Arch as well. You can circumvent it by

```
rm -rf node_modules
npm i 
npm link
yarn install
npm run build
```

Lemme know if that doesn’t fix it for you.

**Comment by Canop** [comment]
This seems to work, thanks.

**Comment by rogererens** [comment]
@someguynamedmatt: Despite running your suggested commands, I end up with this output for `npm run build`:
roger@HP:~/repos/oni$ npm run build

> oni@0.3.3 build /home/roger/repos/oni
> npm run build:browser && npm run build:webview_preload && npm run build:main && npm run build:plugins


> oni@0.3.3 build:browser /home/roger/repos/oni
> webpack --config browser/webpack.production.config.js

Hash: a5367c5ee417c62f177b
Version: webpack 4.6.0
Time: 91860ms
Built at: 2018-04-22 00:12:40
           Asset       Size  Chunks             Chunk Names
    13.bundle.js   2.41 KiB      13  [emitted]
vendor.bundle.js   1.03 MiB       0  [emitted]  vendor
     2.bundle.js   1.06 KiB       2  [emitted]
     3.bundle.js   1.28 KiB       3  [emitted]
     4.bundle.js   2.07 KiB       4  [emitted]
     5.bundle.js   4.01 KiB       5  [emitted]
     6.bundle.js    2.7 KiB       6  [emitted]
     7.bundle.js   3.13 KiB       7  [emitted]
     8.bundle.js   10.8 KiB       8  [emitted]
     9.bundle.js   7.64 KiB       9  [emitted]
    10.bundle.js    359 KiB      10  [emitted]
    11.bundle.js   15.9 KiB      11  [emitted]
    12.bundle.js  996 bytes      12  [emitted]
     1.bundle.js   64.7 KiB       1  [emitted]
    14.bundle.js   1.01 KiB      14  [emitted]
    15.bundle.js   2.35 KiB      15  [emitted]
    16.bundle.js   14.7 KiB      16  [emitted]
    17.bundle.js    2.8 KiB      17  [emitted]
    18.bundle.js   2.39 KiB      18  [emitted]
    19.bundle.js   1.02 KiB      19  [emitted]
    20.bundle.js     11 KiB      20  [emitted]
    21.bundle.js   1.14 KiB      21  [emitted]
    22.bundle.js  556 bytes      22  [emitted]
    23.bundle.js   1.74 KiB      23  [emitted]
    24.bundle.js   27.2 KiB      24  [emitted]
    25.bundle.js   17.5 KiB      25  [emitted]
       bundle.js     58 KiB      26  [emitted]  main
Entrypoint main = bundle.js
  [6] external "electron" 42 bytes {26} [built]
 [19] ./browser/src/Utility.ts 5.39 KiB {26} [built]
 [39] ./browser/src/App.ts 13.6 KiB {26} [built]
 [57] ./browser/src/Services/CommandManager.ts 2.21 KiB {0} [built]
[157] ./browser/src/index.tsx 1 KiB {26} [built]
[158] multi ./browser/src/index.tsx 28 bytes {26} [built]
[181] ./browser/src/Services/IconThemes/index.ts + 3 modules 8.51 KiB {0} [built]
      | ./browser/src/Services/IconThemes/index.ts 989 bytes [built]
      | ./browser/src/Services/IconThemes/Icons.ts 4.07 KiB [built]
      | ./browser/src/Services/IconThemes/IconThemeLoader.ts 2.16 KiB [built]
      | ./browser/src/Services/IconThemes/StyleWriter.ts 1.28 KiB [built]
[182] ./browser/src/Services/Sneak/index.tsx + 3 modules 8.94 KiB {0} [built]
      | ./browser/src/Services/Sneak/index.tsx 2.05 KiB [built]
      | ./browser/src/Services/Sneak/SneakStore.ts 1.44 KiB [built]
      | ./browser/src/Services/Sneak/Sneak.tsx 2.7 KiB [built]
      | ./browser/src/Services/Sneak/SneakView.tsx 2.71 KiB [built]
[183] ./browser/src/Services/Snippets/index.ts + 8 modules 36.6 KiB {0} [built]
      | ./browser/src/Services/Snippets/index.ts 1.81 KiB [built]
      | ./browser/src/Services/Snippets/OniSnippet.ts 2.61 KiB [built]
      | ./browser/src/Services/Snippets/SnippetProvider.ts 3.57 KiB [built]
      | ./browser/src/Services/Snippets/SnippetVariableResolver.ts 1.3 KiB [built]
      | ./browser/src/Services/Snippets/SnippetSession.ts 10.9 KiB [built]
      | ./browser/src/Services/Snippets/SnippetManager.ts 4.32 KiB [built]
      | ./browser/src/Services/Snippets/SnippetCompletionProvider.ts 2.08 KiB [built]
      | ./browser/src/Services/Snippets/UserSnippetProvider.ts 4.99 KiB [built]
      | ./browser/src/Services/Snippets/SnippetBufferLayer.tsx 4.9 KiB [built]
[184] ./browser/src/Services/Overlay.ts 866 bytes {0} [built]
[185] ./browser/src/Services/Colors.ts 2.43 KiB {0} [built]
[187] ./browser/src/Services/Sidebar/index.ts + 4 modules 13.9 KiB {0} [built]
      | ./browser/src/Services/Sidebar/index.ts 929 bytes [built]
      | ./browser/src/Services/Sidebar/SidebarStore.ts 3.81 KiB [built]
      | ./browser/src/Services/Sidebar/SidebarContentSplit.tsx 4.05 KiB [built]
      | ./browser/src/Services/Sidebar/SidebarSplit.tsx 785 bytes [built]
      | ./browser/src/Services/Sidebar/SidebarView.tsx 4.26 KiB [built]
[188] ./browser/src/Plugins/PluginManager.ts + 11 modules 30 KiB {1} [built]
      | ./browser/src/Services/Recorder.ts 5.43 KiB [built]
      | ./browser/src/Plugins/PluginManager.ts 3.52 KiB [built]
      | ./browser/src/Plugins/PluginInstaller.ts 4.45 KiB [built]
      | ./browser/src/Plugins/Plugin.ts 2.08 KiB [built]
      | ./browser/src/Plugins/Api/Oni.ts 5.11 KiB [built]
      | ./browser/src/Plugins/PackageMetadataParser.ts 1.51 KiB [built]
      | ./browser/src/Plugins/AnonymousPlugin.ts 206 bytes [built]
      | ./browser/src/Plugins/Api/Services.ts 111 bytes [built]
      | ./browser/src/Plugins/Api/Capabilities.ts 132 bytes [built]
      | ./browser/src/Services/Automation.ts 6.41 KiB [built]
      | ./browser/src/Plugins/Api/Ui.ts 475 bytes [built]
      | ./browser/src/Services/Git.ts 478 bytes [built]
[191] ./browser/src/Services/StatusBar.ts 2.14 KiB {0} [built]
[219] ./browser/src/Services/Debug.ts 1.68 KiB {21} [built]
    + 1512 hidden modules

WARNING in ./node_modules/shell-env/node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'spawn-sync' in '/home/roger/repos/oni/node_modules/shell-env/node_modules/cross-spawn'
 @ ./node_modules/shell-env/node_modules/cross-spawn/index.js 32:26-47
 @ ./node_modules/shell-env/node_modules/execa/index.js
 @ ./node_modules/shell-env/index.js
 @ ./browser/src/Plugins/Api/Process.ts
 @ ./browser/src/Plugins/PluginInstaller.ts
 @ ./browser/src/Plugins/PluginManager.ts
 @ ./browser/src/App.ts
 @ ./browser/src/index.tsx
 @ multi ./browser/src/index.tsx

> oni@0.3.3 build:webview_preload /home/roger/repos/oni
> cd webview_preload && tsc -p tsconfig.json


> oni@0.3.3 build:main /home/roger/repos/oni
> cd main && tsc -p tsconfig.json


> oni@0.3.3 build:plugins /home/roger/repos/oni
> npm run build:plugin:oni-plugin-typescript && npm run build:plugin:oni-plugin-markdown-preview


> oni@0.3.3 build:plugin:oni-plugin-typescript /home/roger/repos/oni
> cd vim/core/oni-plugin-typescript && npm run build


> oni-plugin-typescript@0.0.1 build /home/roger/repos/oni/vim/core/oni-plugin-typescript
> npm install && tsc

npm WARN oni-plugin-typescript@0.0.1 No description
npm WARN oni-plugin-typescript@0.0.1 No repository field.
npm WARN oni-plugin-typescript@0.0.1 No license field.

up to date in 0.359s

> oni@0.3.3 build:plugin:oni-plugin-markdown-preview /home/roger/repos/oni
> cd extensions/oni-plugin-markdown-preview && npm run build


[sudo] password for roger:
Reading package lists... Done
Building dependency tree
Reading state information... DoneThe following packages were automatically installed and are no longer required:
  indicator-application libappindicator1 libappindicator3-1 libdbusmenu-glib4 libdbusmenu-gtk3-4 libdbusmenu-gtk4 libindicator3-7 libindicator7 libnotify4 libnspr4 libnss3 libnss3-nssdb notification-daemon
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  bc fish-common javascript-common libjs-jquery lynx lynx-common
Suggested packages:
  doc-base apache2 | lighttpd | httpd
The following NEW packages will be installed:
  bc fish fish-common javascript-common libjs-jquery lynx lynx-common
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,337 kB of archives.
After this operation, 9,659 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libjs-jquery all 1.11.3+dfsg-4 [161 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/universe amd64 fish-common all 2.2.0-3 [610 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 bc amd64 1.06.95-9build1 [82.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial/universe amd64 lynx-common all 2.8.9dev8-4ubuntu1 [411 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/universe amd64 lynx amd64 2.8.9dev8-4ubuntu1 [624 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe amd64 fish amd64 2.2.0-3 [443 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/main amd64 javascript-common all 11 [6,066 B]
Fetched 2,337 kB in 1s (2,032 kB/s)
Selecting previously unselected package libjs-jquery.
(Reading database ... 60139 files and directories currently installed.)
Preparing to unpack .../libjs-jquery_1.11.3+dfsg-4_all.deb ...
Unpacking libjs-jquery (1.11.3+dfsg-4) ...
Selecting previously unselected package fish-common.
Preparing to unpack .../fish-common_2.2.0-3_all.deb ...
Unpacking fish-common (2.2.0-3) ...
Selecting previously unselected package bc.
Preparing to unpack .../bc_1.06.95-9build1_amd64.deb ...
Unpacking bc (1.06.95-9build1) ...
Selecting previously unselected package lynx-common.
Preparing to unpack .../lynx-common_2.8.9dev8-4ubuntu1_all.deb ...
Unpacking lynx-common (2.8.9dev8-4ubuntu1) ...
Selecting previously unselected package lynx.
Preparing to unpack .../lynx_2.8.9dev8-4ubuntu1_amd64.deb ...
Unpacking lynx (2.8.9dev8-4ubuntu1) ...
Selecting previously unselected package fish.
Preparing to unpack .../fish_2.2.0-3_amd64.deb ...
Unpacking fish (2.2.0-3) ...
Selecting previously unselected package javascript-common.
Preparing to unpack .../javascript-common_11_all.deb ...
Unpacking javascript-common (11) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for install-info (6.1.0.dfsg.1-5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up libjs-jquery (1.11.3+dfsg-4) ...
Setting up fish-common (2.2.0-3) ...
Setting up bc (1.06.95-9build1) ...
Setting up lynx-common (2.8.9dev8-4ubuntu1) ...
Setting up lynx (2.8.9dev8-4ubuntu1) ...
update-alternatives: using /usr/bin/lynx to provide /usr/bin/www-browser (www-browser) in auto mode
Setting up fish (2.2.0-3) ...
Setting up javascript-common (11) ...
