### ISSUE TITLE
Marks Side Bar item causes Neovim Message Pop up

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1461]
@bryphe I noted an issue whilst working on #1443 having attempted to use `nvim_command_output` to get highlight colors. I discovered that a major side effect of this command is that it causes neovim to briefly show the output of the given command in the echo msg area. This means that with `sidebar.marks.enabled` on there is a flicker of messages on navigating pages which is when I believe the function is called.

A solution would be to generate a `viml function` (I know you're not a fan 😟, I can have alook later I'm interested in trying to use `lua` in vimscript) that passes the output of the command back into oni which can be called silently to work around this and maybe this warrants an issue on neovim's repo as this seems like an unintended side effect

**Comment by bryphe** [comment]
Nice catch, @Akin909 ! I can't believe I missed this - it's incredibly jarring. Appreciate you logging the issue, would've been embarassing for the next release to have this...

In the short-term, I'll set `sidebar.marks.enabled` to `false` for now while we work out the kinks.

> A solution would be to generate a viml function (I know you're not a fan 😟, I can have alook later I'm interested in trying to use lua in vimscript)

Haha, ya, I just hate maintaining VimL 😄 But if there is no other way - I'm open to it!

> be called silently to work around this and maybe this warrants an issue on neovim's repo as this seems like an unintended side effect

👍 that would be great - my expectation was that calling `nvim_command_output` would suppress the output being displayed, so seems like it may be a bug (other consumers of the API may have the same expectation I'd imagine).

**Comment by Akin909** [comment]
This issue was resolved by neovim/neovim/pull/7821

**Comment by bryphe** [comment]
Awesome! Thanks @Akin909 . Need to bring back the bookmarks bar now 😄
