### ISSUE TITLE
Browser: Integrate with 'sneak' mode

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1464]
This tracks integrating the browser with sneak. This is one of the main value propositions of having a browser embedded in Oni - it means that we can use `Control+G` to quickly navigate to pieces of the UI in the browser.

This is non-trivial, and will require a few pieces:
- A sneak provider for the browser. We'll have to preload a javascript file that we can talk to in order to get the sneak locations.
- Support async in sneak - right now, it assumes all the providers will synchronously give the client rectangles, but this won't be the case with the browser integration.

**Comment by TalAmuyal** [comment]
What is this 'sneak' mode?

**Comment by bryphe** [comment]
@TalAmuyal - it's the implementation of #366 , accessible via `Control+G` in the master builds. It's limited right now, but I'd like for it to be another way to get around the UI.. it's useful in cases where the normal Vim navigation might not apply (like a browser window!):

![image](https://user-images.githubusercontent.com/13532591/35931484-9eb1c506-0be9-11e8-8a38-1b1d1ec6adf9.png)

Right now the embedded browser isn't too useful, because you need to use the mouse with it anyway

**Comment by TalAmuyal** [comment]
Looks cool **and** useful, nice!

**Comment by CrossR** [comment]
Looks like this can be closed with the recent PRs! (#1661 and #1699)

Other smaller issues should probably be picked up in more directed tickets.
Pretty excited to have this in, since a bunch of the time my work flow is Oni on half the screen and a browser on the other half.

**Comment by bryphe** [comment]
Cheers, thanks @CrossR !

> Pretty excited to have this in, since a bunch of the time my work flow is Oni on half the screen and a browser on the other half.

Same here. Hope we can smooth out this workflow shortly 👍

**Comment by DaniloZZZ** [comment]
Chek out Vimium browser extension, it brings up the feature
