### ISSUE TITLE
[RFC] Use `.config/oni` for configuration instead of `.oni`

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1478]
Currently oni uses the `~/.oni` folder to store local configuration.

While this is a common model to use, these days many providers use the `~/.config/oni` model instead.

This avoids cluttering of the home folder while also organizing all local configuration files, as you can see electron even creates one by default:

```
~ ❯❯❯ tree .config/oni
.config/oni
├── Cache
│   ├── data_0
│   ├── data_1
│   ├── data_2
│   ├── data_3
│   └── index
├── GPUCache
│   ├── data_0
│   ├── data_1
│   ├── data_2
│   ├── data_3
│   └── index
├── Local Storage
│   ├── chrome-devtools_devtools_0.localstorage
│   └── chrome-devtools_devtools_0.localstorage-journal
├── Preferences
└── Settings

3 directories, 14 files
```

This would also unify both configuration folders.

**Comment by CrossR** [comment]
As far as I know, this is also how Neovim works, so makes even more sense to me to do it this way.

**Comment by bryphe** [comment]
👍 , makes sense to me.

**Comment by TalAmuyal** [comment]
That is not exactly correct (though I do like the idea).
You describe the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) which requires things like cache to be in a seperate dir.
It seems to be implemented by [this package](https://www.npmjs.com/package/xdg) so it might be easy to implement compliantly (I think it supports Windows as well).

**Comment by badosu** [comment]
Thanks @TalAmuyal, I'll take a stab at this!
