### ISSUE TITLE
Development/ Integration tests timeout on (this) MacOS

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1524]
As per gitter integration test are hanging on *my* mac not sure if this is truly a platform issue possibly local environment. Here's a log of the output of the `yarn test:integration`  command
[out.log](https://github.com/onivim/oni/files/1714771/out.log)

**Comment by bryphe** [comment]
Looks like the tests are getting stuck on this wait condition:
```
     Log.info("[AUTOMATION] Waiting for neovim to attach to editor...")
        await this.waitFor(
            () =>
                editorManager.activeEditor.neovim &&
                (editorManager.activeEditor as any).neovim.isInitialized,
            30000,
        )
        Log.info("[AUTOMATION] Neovim initialized!")
```

Could you please attach the output of `:CheckHealth` when you run Oni? It'd be really helpful if it is without a config. I'm wondering if there is any environment variable set or anything that could impact Neovim starting up.

**Comment by Akin909** [comment]
@bryphe here's the output, is my init.vim loaded when the integration test are spun up? there's a lot of stuff in there so wouldn't suprise me if something in there broke something else.

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $COLORTERM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: pyenv was found, but $PYENV_ROOT is not set.
    - ADVICE:
      - Did you follow the final install instructions?
      - If you use a shell "framework" like Prezto or Oh My Zsh, try without.
      - Try a different shell (bash).
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /Users/akinyulife/.pyenv/shims/python2 does not have the "neovim" module. :help |provider-python|
    /Users/akinyulife/.pyenv/shims/python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    /Users/akinyulife/.pyenv/shims/python does not have the "neovim" module. :help |provider-python|
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /Users/akinyulife/.pyenv/shims/python2 does not have the "neovim" module. :help |provider-python|
          /Users/akinyulife/.pyenv/shims/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /Users/akinyulife/.pyenv/shims/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: pyenv was found, but $PYENV_ROOT is not set.
    - ADVICE:
      - Did you follow the final install instructions?
      - If you use a shell "framework" like Prezto or Oh My Zsh, try without.
      - Try a different shell (bash).
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /Users/akinyulife/.pyenv/versions/3.4.4/bin/python3
  - INFO: Python3 version: 3.4.4
  - INFO: python3-neovim version: 0.1.13 (outdated; from ~/.local/lib/python3.4/site-packages/neovim)
  - WARNING: Latest python3-neovim is NOT installed: 0.2.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - WARNING: Gem "neovim" is out-of-date. Installed: 0.5.1, latest: 0.6.2
    - ADVICE:
      - Run in shell: gem update neovim

## Node provider (optional)
  - INFO: Node: v8.9.1
  - INFO: Host: /usr/local/bin/neovim-node-host
  - WARNING: Package "neovim" is out-of-date. Installed: 3.5.0, latest: 3.5.2
    - ADVICE:
      - Run in shell: npm update neovim
```

**Comment by bryphe** [comment]
Thanks @Akin909 ! I don't see anything out of the ordinary here.

> @bryphe here's the output, is my init.vim loaded when the integration test are spun up? 

The tests definitely _shouldn't_ since it would give inconsistent results. They actually create a temporary `config.js` and load from that. It's possible there could be some environment variable set that is causing it to pick up another `init.vim`, though.

I'm looking through your test run logs to see if there are any other clues. Otherwise, we can try and add some additional logging.

**Comment by bryphe** [comment]
Alright, dived _deeper_ into the log, and actually, it's this _second_ wait that is failing:

```
        Log.info("[AUTOMATION] Waiting for shared neovim instance...")
        await this.waitFor(
            () => getSharedNeovimInstance() && getSharedNeovimInstance().isInitialized,
            30000,
        )
        Log.info("[AUTOMATION] Shared neovim instance initialized!")
```

It looks like the `SharedNeovimInstance` gets to this point in `_attachUI`:
```
        console.log(`Neovim version reported as ${version.major}.${version.minor}.${version.patch}`) // tslint:disable-line no-console
```
And reports the version.

But it doesn't seem like it gets past the actual `attach` call here:
```
        console.log(`Neovim version reported as ${version.major}.${version.minor}.${version.patch}`) // tslint:disable-line no-console
```

We could add a bit more logging around here to see if we can isolate the issue. I'll create a branch with some ideas, and we'll see if we can get some more clues. Thanks for your help debugging this, @Akin909 !

**Comment by Akin909** [comment]
@bryphe sorry I missed this Ill pull the branch and post the log of the output

**Comment by bryphe** [comment]
@Akin909 , just checking - were you ever able to run the integration tests?

**Comment by Akin909** [comment]
@bryphe unfortunately not when I run the ciTests they all fail with the following error `Error: ChromeDriver did not start within 5000ms`, this is with all `oni` windows closed. This is the original/long standing error i've been getting. The electron window doesn't open.

**Comment by Akin909** [comment]
Resolved I'll leave an explanation here in case this happens to anyone else but that seems unlikely. 

Essentially I had a duplicate `chromedriver` process running on `9515` the default port which was resulting in a `chromedriver timed out after 5000ms` error since chromedriver does not actually report the actual error. I had to find the processes PID and kill it after which everything worked fine

**Comment by bryphe** [comment]
Woohoo! So glad they are finally working!

Thanks for sharing the result of your investigation - will be helpful as a troubleshooting step if anyone else runs into this. 💯
