### ISSUE TITLE
Remote capabilities

### ISSUE THREAD

**Issue by AGhost-7** [onivim/oni#153]
It seems that oni uses a packaged neovim binary instead and calls that. I was trying to get oni to connect to an already running neovim instance and wasn't able to do so.

You can do this with neovim-qt, e.g.

```
NVIM_LISTEN_ADDRESS=/tmp/nvim.sock nvim --headless
nvim-qt --server /tmp/nvim.sock
```

**Comment by extr0py** [comment]
Yes, right now Oni makes the assumption that it is going to spin up the Neovim instance and talk directly to it. This is something we can support though - we'll just need to parse that argument and connect to the running instance, as opposed to spinning up a new one.

**Comment by bryphe** [comment]
More in depth discussion in #247  - I'll close this and use that to track.
