### ISSUE TITLE
TS file recognized as XML file

### ISSUE THREAD

**Issue by TalAmuyal** [onivim/oni#1537]
Currently on master, for some reason, TS files are recognized as XML files...

**Comment by TalAmuyal** [comment]
I am not currently sure what are the circumstances, will post an update (hopefully with some pattern).

**Comment by bryphe** [comment]
Hmm, I've seen this sometimes if I don't run `git submodule update --init -recursive` - one of our git submodules is responsible for loading the filetype for `ts` files.

Just a quick sanity check - what do you have in your `oni\vim\core\typescript-vim` folder?

**Comment by TalAmuyal** [comment]
Spot on!

Indeed the `vim/core/typescript-vim` was empty.
Running `git submodule update --init --recursive` solved it.

Thanks and sorry for bothering you...

**Comment by bryphe** [comment]
No prob, glad that was the issue ! 👍

**Comment by markhu** [comment]
FBO non-`onivim` users who found this page from a Google search: keep looking... try https://github.com/leafgarland/typescript-vim/issues/96
