### ISSUE TITLE
:set nolist from init.vim file not being read

### ISSUE THREAD

**Issue by nwaywood** [onivim/oni#1539]
I have `set nolist` in my `init.vim` file (https://github.com/nwaywood/dotfiles/blob/master/oni/init.vim#L56) which is meant to hide invisible characters but it doesn't seem to be working. Here is what it looks like:

![image](https://user-images.githubusercontent.com/3773641/36125051-96365b00-10a6-11e8-8b1c-790a7583ec77.png)

However, if I manually execute `:set nolist` as an ex command then it gets applied properly:

![image](https://user-images.githubusercontent.com/3773641/36125082-b78dd986-10a6-11e8-915f-204b8ace850c.png)

So it seems like Oni is failing to read/apply `nolist` when it is set from the `init.vim` file but applies it fine when set manually. I have also tried with a minimal `init.vim` file but it is still the same issue.

**Comment by CrossR** [comment]
This is probably due to #973.

Oni has its own set of Defaults, which currently is a bit too opinionated, and in cases like this it can clobber the user's settings, in this case the `set list` is over-writing yours.

Looks like we need to cut it down to the very basics Oni needs, and nothing more.

**Comment by bryphe** [comment]
One workaround for now, until we trim down the settings in #973, is to add this to your config:
```
"vim.setting.list": false,
```

This will set `nolist`, after all the `.vim` files are sourced, so it will override those overly-opinionated settings.

**Comment by nwaywood** [comment]
@bryphe can confirm that workaround worked. Thanks! I'll keep an eye on #973 :)

**Comment by CrossR** [comment]
I'll close this out as with #1811 `set list` was removed from the default config.
#973 is still open to track the tab size changes and a few other bits however.
