### ISSUE TITLE
Insert mode and cmd+shift+p

### ISSUE THREAD

**Issue by TheKnarf** [onivim/oni#1543]
If you first enter insert mode, then hit cmd+shift+p, start typing something and then hit backspace:

Instead of deleting what you wrote in the popup you delete stuff in the document.

http://recordit.co/sVt8CyRto5

macOS Sierra v10.12.6
oni v0.3.0

**Comment by CrossR** [comment]
Hmm, can't reproduce on Windows.

That said, on Mac we have :

https://github.com/onivim/oni/blob/ab0704a25c4db2425d193809942d26da7d0562a7/browser/src/Input/KeyBindings.ts#L28

vs this on Windows:

https://github.com/onivim/oni/blob/ab0704a25c4db2425d193809942d26da7d0562a7/browser/src/Input/KeyBindings.ts#L49

Looks like Mac may just be missing the filter?
