### ISSUE TITLE
Can't disable external command line

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1547]
After upgrading to 0.3.0 I noticed the external command line was too disruptive for my workflow.

I tried using the instructions at the [wiki](https://github.com/onivim/oni/wiki/Configuration#externalised-command-line) but no success so far.

How can I disable it?

Btw, I think it's a great idea, but the position and current look distract from the content of the editor.

**Comment by CrossR** [comment]
Looks like the Wiki hasn't been updated for the new values....

They moved out of `experimental` so you should just use the following:
```
    "commandline.mode": false,
    "commandline.icons": false,
    "wildmenu.mode": false,
```

**Comment by badosu** [comment]
Thanks @CrossR, I was going to update the wiki but noticed you got ahead of me :-).

**Comment by bryphe** [comment]
Sweet, thanks for updating the wiki @CrossR  👍
