### ISSUE TITLE
Control-P in explorer split doesn't open file finder

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1554]
__Issue:__ `Control+P` in the explorer split doesn't open the quick open menu (rather, it moves back a line).

It's easy to repro by navigating to the explorer split (`<C-w><C-h>`), and then pressing `Control-P`.

**Comment by am2605** [comment]
On man, I've worked this out.  I looked again at my config.js which I'd copied from the [docs ](https://github.com/onivim/oni/wiki/Configuration#configjs) without really understanding what it did.  And it unbinds Ctrl-P.  I've commented that out, and it works again.  How embarrassing. ;-)

**Comment by someguynamedmatt** [comment]
Not embarrassing at all. Glad you figured it out!

**Comment by TalAmuyal** [comment]
So, as far as I understand there is no issue to resolve - closing this issue.
If I'm wrong, please reopen.

Cheers :)

**Comment by CrossR** [comment]
I'll re-open this since I am still having this issue.

The Command Palette opens fine, its just the quick open menu that doesn't work for me.
I've not got any unbinds in my config so I assume it is just a bug that we aren't passing over the `<c-p>` keybind when in the explorer or in the sidebar.

**Comment by CrossR** [comment]
From a quick debugging, two things are  happening here:

1. The command `quickOpen.show` isn't in the `commandDictionary` when we press it in the explorer or side bar.
2. Instead, it then cycles through the other `<c-p>` bindings, before landing on `menu.previous` which does work.

I'm less sure why the `commandDictionary` doesn't contain this command though.

**Comment by CrossR** [comment]
I'll close this out now, since its been fixed recently.
