### ISSUE TITLE
Shortcut hints on the command pallet got cropped when the window size is small

### ISSUE THREAD

**Issue by Contextualist** [onivim/oni#1560]
(Just saw Oni's "What's new in 0.3.0" video and realized that the command pallet had been long available. 😉 Really helpful video for the slow-witted me.)

When I started to explore Oni's shortcuts with command pallet, I noticed that some shortcut hints are not fully displayed:
![2018-02-14 21 15 40](https://user-images.githubusercontent.com/16000021/36209630-c9dc4b8a-11ce-11e8-9ec9-9500b30c5d90.png)

When I entered full-screen, the issue is solved, so there're probably some problems with the overflow strategy.

**Comment by bryphe** [comment]
Thanks for the issue, @Contextualist ! Yes, definitely a bug.

> (Just saw Oni's "What's new in 0.3.0" video and realized that the command pallet had been long available. 😉 Really helpful video for the slow-witted me.)

LOL I think the video was long over-due, there is a lot of functionality packed in that we haven't done a good job showcasing. Glad it was helpful! More to come.

> When I entered full-screen, the issue is solved, so there're probably some problems with the overflow strategy.

Ya, looks like we need to step up our flex-box game there..

**Comment by Cryza** [comment]
I will try to fix this as my first contribution if you are okay with that :)

**Comment by bryphe** [comment]
@Cryza - that would be great! 👍 Let me know if you need any help getting started.
