### ISSUE TITLE
existing file opens as new file

### ISSUE THREAD

**Issue by rockneverdies55** [onivim/oni#1561]
I'm on Oni 0.3 latest. 
- launch oni
- change to the project folder (via launching file browser from the left bottom link)
- ctrl + p and fuzzy type file name
- click enter when the file is found and selected in the dropdown

Fuzzy file finder gets closed and the file is loaded. However the buffer is empty and in the status line it's saying (NEW FILE (or NEW DIRECTORY sometimes)) along with the full path to the file for some reason. Yeah crazy but true :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/4588562/36211481-57dbf21a-116f-11e8-8c38-f998f7218d35.png)

**Comment by bryphe** [comment]
Thanks for logging the bug, @rockneverdies55 ! I wonder if it is the same issue that @CrossR logged in #1397 ?

Just for some extra context - do you have a workspace open?

**Comment by someguynamedmatt** [comment]
I think I see the issue. I'll work on somethin'.

**Comment by CrossR** [comment]
Think this should be fixed after #1643 and #1645.
