### ISSUE TITLE
Sidebar: When 'sidebar.enabled' is false, get errors when trying to find in files

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1562]
Following the discussion from #1555 :

One bug I did notice though, when `sidebar.enabled` is `false` (after #1555), and I try and 'find in files' with `Control+Shift+F`, I get an error:
![image](https://user-images.githubusercontent.com/13532591/36218374-f8ffe856-1168-11e8-93c7-d23761052d1d.png) 

What we might want to eventually do is _always_ create the sidebar + sidebar content pane, but if `sidebar.enabled` is `false`, we just hide them (or they start hidden, and we only `show` them if `sidebar.enabled` is true`). Then, if a user does `Control+Shift+B` to toggle the sidebar, or `Control+Shift+F` to find in files, we can make it visible.

**Comment by someguynamedmatt** [comment]
Hmmm, @bryphe I can't recreate this on my Linux box. This is the config file I'm using (very lean for testing):

```
const activate = (Oni) => {
   console.log("config activated")
}

const deactivate = () => {
   console.log("config deactivated")
}

module.exports = {
   activate,
   deactivate,
   "editor.fontSize": "14px",
   "editor.fontFamily": "Droid Sans Mono for Powerline",
  //add custom config here, such as
  //"oni.useDefaultConfig": true,
  //"oni.bookmarks": ["~/Documents",]
  // "oni.loadInitVim": true,
  "sidebar.enabled": false,
  //"editor.fontSize": "14px",
  //"editor.fontFamily": "Monaco"
}
```
