### ISSUE TITLE
When using `tabs.mode: "tabs"` the files from the explorer open in the same tab

### ISSUE THREAD

**Issue by magopian** [onivim/oni#1563]
This is a follow-up of #1557, exploring ways to use tabs in oni, and close them.

The problem occurs when opening a file from the explorer: it opens it in the same tab as the one already active, instead of opening it in another tab.

**Comment by bryphe** [comment]
Good point - I wonder if a better default, for both the file finder and explorer, is to open in a new tab?  (In the fuzzy-file finder, we have a `Control+T` shortcut for opening in a new tab)

**Comment by magopian** [comment]
At least for my usage, it would definitely make sense. It seems I have no way to open a file in a new tab from the explorer. But then I also know I don't have a conventional use of tabs/buffers in the vim world, so please take that with a grain of salt.

**Comment by bryphe** [comment]
This is fixed now with #1667 (at least, the default is now to open in a new tab)
