### ISSUE TITLE
Ocaml LSP no longer working ?with new v1.0.26

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1571]
Since very recently the Ocaml language server no longer seems to work i.e. does not provide completions, hover, diagnostics etc.

The Oni console shows
<img width="825" alt="screen shot 2018-02-17 at 23 14 20" src="https://user-images.githubusercontent.com/22454918/36346582-738e91ae-1438-11e8-834a-38f90bb9be8f.png">

Looking at the changes made in the most recent `lsp` upgrade its not clear why Oni's integration no longer works though It might be that oni needs to change its configuration for the lsp

**Comment by bryphe** [comment]
Ah bummer... it would be great to get the the test working in #1189 so that we have a safety net to protect us from regressions here.
