### ISSUE TITLE
Tab characters show as weird symbol

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1573]
When a file contains tabs instead of spaces, I see strange tab chars instead of normal white space:
![2018-02-18-152238_2044x1395_scrot](https://user-images.githubusercontent.com/163128/36352909-c2794444-14bf-11e8-9054-94c9db2fff49.png)

I reset my config to default one.

**Comment by CrossR** [comment]
As far as I know, that is the symbol that is shown in vim if you have tabs and `set list` in your `init.vim` which is in the Oni default config.

We have #973 open to reduce the default config down the actual basics, but until then, you can set

`"vim.setting.list": false,` in your config to stop this happening.
