### ISSUE TITLE
textMateHighlighting.debugScopes is broken

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1578]
```json
	"experimental.editor.textMateHighlighting.debugScopes":true,
```
is broken. Only a little arrow (hard to see) shows up:
![2018-02-18-165530_70x68_scrot](https://user-images.githubusercontent.com/163128/36353888-a8fcbeee-14cc-11e8-9be8-f08e6b7decba.png)

**Comment by bryphe** [comment]
Thanks for logging the issue, @hoschi ! Can confirm the repro. It'll be important for us to fix so that users know what scopes to set when customizing token colors.
