### ISSUE TITLE
"Oh no!" error after loading a session

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#1579]
I use https://github.com/vim-ctrlspace/vim-ctrlspace for session loading. Which worked before, but now I get an error:

![2018-02-18-170037_1104x913_scrot](https://user-images.githubusercontent.com/163128/36353921-413814e2-14cd-11e8-8678-08dc15b2142a.png)
![2018-02-18-170114_1334x521_scrot](https://user-images.githubusercontent.com/163128/36353926-58c58554-14cd-11e8-8ba5-4b858c7d561f.png)
![2018-02-18-170446_2044x1395_scrot](https://user-images.githubusercontent.com/163128/36353988-057dcee6-14ce-11e8-909e-265e5e0ab1e1.png)
![2018-02-18-170556_2044x1395_scrot](https://user-images.githubusercontent.com/163128/36353989-07d2bc06-14ce-11e8-9c2c-d81cb7793bf4.png)

**Comment by hoschi** [comment]
Seems to happen when there is only one buffer in a tab?!

**Comment by hoschi** [comment]
I also get this every once in a while (5 times this day, I believe) when I hit `,tc` which is mapped to:
`nmap <Leader>tc :tab split<cr>`

**Comment by hoschi** [comment]
`:tab split` is not a plugin, I don't think it has to do with ctrl-space itself.

**Comment by badosu** [comment]
Seems like a core Oni issue then

**Comment by hoschi** [comment]
`:tabclose` also breaks Oni. I switch now to nvim as with that much various crashes and error popups I can't work.

@badosu yes, happens without init.vim aswell

**Comment by CrossR** [comment]
@hoschi , have you got a repro for this? I'm trying to have a look into it, but I'm struggling to get it to happen for me.

**Comment by hoschi** [comment]
I got it after 5mins with repeating this steps:

* open a file with "ctrl+p"
* open another file
* `:tab split`
* open another file
* open another file
* `:tab split`
* ...

I'm on 44e162d359c6b2a669e5d6

**Comment by CrossR** [comment]
Yep, repro'd it and got it sorted. 
Think its a stupid error of mine for not checking if the input was an array before running find. Sorry!

Should also fix #1588 as far as I can tell, just pushing it now so the CI tests can run.

**Comment by hoschi** [comment]
Thanks for looking into it @CrossR 
I update tomorrow morning and test it.

**Comment by badosu** [comment]
@hoschi Not sure if it would have avoided this specific error, but using the tagged released versions has proven stable for the last 3 months for day-to-day work to me.

**Comment by hoschi** [comment]
As I post several bugs after in depth testing after an update, I can skip the question "it is fixed in master" right away using master instead of stable.

**Comment by hoschi** [comment]
I try to update when a stable version was released, but most of the time it doesn't fit in my schedule :disappointed:

**Comment by hoschi** [comment]
Seems to be fixed with  #1590
I'll test it this day and close this and #1588 if it doesn't crash anymore.

**Comment by hoschi** [comment]
No crash yesterday.
