### ISSUE TITLE
QuickOpen Regex Errors

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1585]
When using `    "editor.quickOpen.filterStrategy": "regex",`, errors are raised when partial regex symbols are input.

Ie, an error is raised if `(` is typed since the group isn't complete yet, or `+` if it doesn't apply to anything.
If `(` is used, every letter after it until the closing `)` will also raise an error.

Errors in the regex are useful, but should be properly caught and displayed back to the user.
I'm not sure the best way to display that though, any ideas?

**Comment by badosu** [comment]
We could try to compile the regex, if it fails treat the whole input as literal pattern.

**Comment by CrossR** [comment]
I'm going to close this for now as it seems (to me) a waste for us to start patching the `regex` method when its hardly used.

Potentially worth re-opening if I'm wrong and the `regex` method is used loads, but I'm doubtful.
