### ISSUE TITLE
libxkbfile for mac?

### ISSUE THREAD

**Issue by TheKnarf** [onivim/oni#1587]
Running the step from the [Development guide](https://github.com/onivim/oni/wiki/Development) doesn't seem to work on my Mac.
```
➜  oni git:(master) sudo apt install libxkbfile-dev
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/apt" (-1)
```

**Comment by badosu** [comment]
I guess this step was a typo? I am not sure there exists apt for Mac.

**Comment by TheKnarf** [comment]
@badosu There is indeed no apt for Mac.

But that still leaves out how to actually build the project.

**Comment by TheKnarf** [comment]
Trying to build it without libxbkfile doesn't seem to work.

```
oni git:(master) yarn install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning vscode-languageclient@3.5.0: The engine "vscode" appears to be invalid.
info 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > oni-api@0.0.30" has unmet peer dependency "vscode-languageserver-types@^3.5.0".
warning " > oni-api@0.0.30" has unmet peer dependency "rimraf@^2.6.2".
[4/4] 📃  Building fresh packages...
[1/11] ⠂ keyboard-layout
[2/11] ⠂ oni-neovim-binaries
[3/11] ⠂ oni-ripgrep
[4/11] ⠂ oniguruma
error /Users/fl-macbook-retina/Dropbox/Projects/oni/node_modules/keyboard-layout: Command failed.
Exit code: 127
Command: node-gyp rebuild
Arguments:




^C
```

**Comment by bryphe** [comment]
@TheKnarf - do you have `XCode` installed, plus the command line utilities? The `keyboard-layout` module needs these. The `libxkbfile-dev` may not be needed.

As a sanity check, you could try creating a new folder, and running `npm install --loglevel verbose keyboard-layout` - it would be helpful to see the result of that.

**Comment by TheKnarf** [comment]
`xcode` with command line utilities should be installed.

`npm install --loglevel verbose keyboard-layout` seems to work.
So I tried deleting `node_modules` and run `yarn install` again and this time it seems to work.

**Comment by bryphe** [comment]
> So I tried deleting node_modules and run yarn install again and this time it seems to work.

Glad it worked the second time around - thanks for the update! Sometimes there are transient issues with the download 😦 I'll close this out.
