### ISSUE TITLE
Is possible to add org-mode in oni as a build-in feature?

### ISSUE THREAD

**Issue by ram535** [onivim/oni#1594]
One of the best feature in emacs is org-mode. I think it would be a great feature for oni if it is possible.
There is a new org-mode parser written in javascript called [Orga](https://github.com/xiaoxinghu/orgajs) that might help to accomplish that.

**Comment by bryphe** [comment]
Thanks @ram535 for the idea! That would be cool, org-mode is killer for Emacs.

I wonder if some of it would be possible to implement as a [language server](http://langserver.org/)? Things like agenda view etc probably don't fit into that protocol, though (that might be a cool way to use the preview capabilities for Oni).

**Comment by hoschi** [comment]
@ram535 do you know about vim plugins which can help or you meant the whole functionality should be implemented in JS? I don't know much about org-mode.

**Comment by ram535** [comment]
I don't know the best way to implement org-mode to oni. I personally use org-mode to keep organize my [dots files](https://github.com/ram535/dotfiles) and notes.

Somethings you can do in org-mode is [Literate Programming](https://orgmode.org/worg/org-contrib/babel/intro.html#literate-programming), or use it in similar way people use [jupiter](https://orgmode.org/worg/org-tutorials/org-plot.html), other people use it to write [latex](https://orgmode.org/worg/org-tutorials/org-latex-preview.html) in a sane way, some use it for [blogging](https://www.shanesveller.com/blog/2018/02/13/blogging-with-org-mode-and-ox-hugo/), calendar, todo list, etc.

There is a plugin for vim called [vim-orgmode](https://github.com/jceb/vim-orgmode) but there are some functionalities that cannot be implemeted in vim like showing in-line images, etc. and it just doesn't look good in the terminal.

**Comment by fbob** [comment]
This is a must have feature to dominate the world of text editor !
I'm not kidding ... org-mode is what makes emacs shine and what makes the users so productive with it.
Sorry, it's THE must have feature

**Comment by trev-dev** [comment]
Just chiming in, my favorite aspect of org-mode is scheduling, deadlines, the org-agenda that shows my work agenda for the week. I use org-caldav-sync to sync my agenda to my nextcloud calendar. 

It's stuff like this that makes me never want to leave Emacs whereas I would've easily done so given that their way of handling major-modes isn't always smooth. Take syntax highlighting & auto-completing in a .Vue component for example. I spent 2 hours on it and I'm still not 100% satisfied with it.

**Comment by Mpdreamz** [comment]
FWIW https://github.com/jceb/vim-orgmode does not work by simply cloning into `%APPDATA%/oni/plugins` for me.
