### ISSUE TITLE
Ctrl+G doesn't work as in vim

### ISSUE THREAD

**Issue by ha7ilm** [onivim/oni#1628]
It shows labels on the UI like this:

![image](https://user-images.githubusercontent.com/5903408/36638978-ed8da49e-1a01-11e8-9a58-bda8c4d1903d.png)

I used to use <kbd>1</kbd><kbd>Ctrl</kbd>+<kbd>G</kbd> to print the full path of the file in `vim`, like here:

![image](https://user-images.githubusercontent.com/5903408/36639020-117c5cc8-1a03-11e8-9840-da2dc20b3497.png)

**Comment by CrossR** [comment]
Hi,

Oni by default has its sneak-UI bound to `Ctrl+g`, which is those labels you are seeing. (Typing a label will select that item etc).

You can unbind that with `oni.input.unbind("<c-g>")` in your `config.js`, which is in the `Ctrl+Shift+P` menu as User config. That will tell Oni to stop capturing the input and to send it directly to neovim.

If you wanted to rebind sneak to another keybinding, you'd use something like:
`    oni.input.bind("<s-c-g>", () => oni.commands.executeCommand("sneak.show"))`

Which would bind it to `Ctrl+Shift+G` etc.

**Comment by ha7ilm** [comment]
Ah, OK. Thanks for the fast response!

**Comment by badosu** [comment]
@ha7ilm @CrossR I created a page to document the configurations that make Oni closer to vim: https://github.com/onivim/oni/wiki/How-To:-Make-Oni-closer-to-bare-Vim-experience
