### ISSUE TITLE
Ligatures broken in TS files

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1629]
With the new highlight tokens whilst I havent confirmed this I think that the `>` character is now being highlighted differently to the `=` character so that rather than creating a `=>` ligature you get a purple `>` sign instead

<img width="96" alt="screen shot 2018-02-25 at 11 11 17" src="https://user-images.githubusercontent.com/22454918/36640747-aad8d3e2-1a1c-11e8-96ad-30db8956a818.png">

I think a fix of for this would be finding the token for the `>` and not applying a token for that or applying a similar one for the `=` unless they dont match in which case remove the token

**Comment by bryphe** [comment]
Ah, good catch @Akin909  - I like your idea of not applying the highlighting for tokens for now. I'm not sure the TextMate highlighting implementation today handles this very well, so it might be best to leave those alone and defer to the vim highlighting (for now).

**Comment by Akin909** [comment]
I think this was spurious and related more to my config I havent seen this issue recur
