### ISSUE TITLE
Unable to scroll auto complete list beyond limit on autoCompletion

### ISSUE THREAD

**Issue by Rafi993** [onivim/oni#163]
I opened simple code snippet when and tried auto complete. I am unable to scroll beyont the limit to see other functions in suggestion. 
![screenshot from 2017-01-14 12-18-37](https://cloud.githubusercontent.com/assets/8092120/21953072/f85cb9a8-da53-11e6-937b-9eb34dd10c80.png)

In the above screen shot I was not able to scroll beyond **and** snippet in the auto completion.

**Comment by Rafi993** [comment]
I was able to solve this issue by removing FirstTen in Autocompletion.tsx that used _.take to get the first ten entries

**Comment by extr0py** [comment]
Thanks @Rafi993 ! Yes, I think we need to add a scrollbar + a way to manage the active view of these components (the Menu also has this same problem).  Appreciate the PR!

**Comment by extr0py** [comment]
I realized why the firstTen was used now... There is some expensive logic that iterates over all the entries at the moment. We'll need another way of filtering them and a different scrollbar mechanism.

**Comment by Rafi993** [comment]
@extr0py I agree. The scroll in auto completion feels clunky re-writing that module would be better.

**Comment by bryphe** [comment]
Seems like the same issue as #166 - I'll resolve this as a duplicate.
