### ISSUE TITLE
How to open/close the file explorer?

### ISSUE THREAD

**Issue by trusktr** [onivim/oni#1634]
How can we open/close the file explorer on the left?

**Comment by CrossR** [comment]
You can use `<Ctrl+Shift+B>` to toggle the side bar, or if you'd prefer some other keybind, you could unbind that and rebind any set of keys using the Oni input API and the command `"sidebar.toggle"`, ie putting the folloing in the `activate` section of your `config.js`:

```
oni.input.unbind("<s-c-b>")
oni.input.bind("<s-c-q>", "sidebar.toggle")
```

**Comment by trusktr** [comment]
Sweeet. Seems intuitive that clicking on the icon in the left bar would also open/close the view.

**Comment by badosu** [comment]
There are two improvements that are very needed for the Sidebar at the moment:

- Have an option for the Sidebar to not be shown on startup (but still be enabled)
- Have better gui controls for the sidebar (resizing and toggling mostly)

I think the question was answered already so we can close this issue and track the improvements somewhere else or discuss these items here.

**Comment by brianyang** [comment]
this doesn't seem to work on OSx. anybody else experiencing this issue?

**Comment by parkerault** [comment]
@brianyang on OSX the shortcut is command shift b.

**Comment by badosu** [comment]
The sidebar default state can be configured with `sidebar.default.open`. The shortcut was already clarified.
