### ISSUE TITLE
Question: Match editor token to vscode style for interoperability or convert in Oni

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1642]
@bryphe since you mentioned re down the line possibly being able to use `vscode` themes in oni as well as `vim` and `oni` ones I've looked into adding `editorTokenColors` from the vscode onedark theme.

Attempting this raised a question which is the format of vscode editor tokens is as follows.
```ts
interface VscodeToken {
	scope: string | *string[]*
	settings: {
	foreground: string
	background: string
	fontStyle: "italic" | "bold"
	...loads of other values which I currently dont know what they represent
}
```

Atm `Oni` expects scope to be a string and foregroundColor and backgroundColor as well as `italic: boolean` and `bold: boolean`. I've been working on converting tokens specified in the theme as per vscode into something oni can use i.e. `foreground` to `foregroundColor`. 

My question, finally, is do we want to be doing conversion there or changing our style to more closely match that so things just work ™️. On that note as far as I can see with scopes as an array that will always need some form of processing, at the moment locally I just split each scope specified into its own token based on the settings of the token it was grouped with.

**Comment by bryphe** [comment]
My goal is eventually to support VSCode plugins in Oni, so unless there is a compelling reason to be different - I think we should stick with the VSCode format (it'll make bringing in VSCode plugins down the road easier!)

**Comment by Akin909** [comment]
Asked and answered doesnt need to remain open I think
