### ISSUE TITLE
equivalent of gui_running?

### ISSUE THREAD

**Issue by trusktr** [onivim/oni#1651]
I have some config in my .vimrc like the following in which I set colorschemes:

```viml
                if &term == "xterm" || &term == "xterm-256color" || &term == "screen-256color" || (&term == "nvim" && !has("gui_running"))
                  " set 256 colorscheme
                elseif has("gui_running")
                  " set 24-bit colorscheme
                endif
```

However Oni is falling into the first category. I was hoping it would `has('gui_running')` or something similar to that I can do 24-bit color stuff.

How would we do this in OniVim?

**Comment by Akin909** [comment]
Oni sets a variable in vim called `g:gui_oni` see details [here](https://github.com/onivim/oni/wiki/Configuration#initvim), can be used like
```vim
if exists(g:gui_oni)
	"stuff here
```
