### ISSUE TITLE
make it posible to type tabs

### ISSUE THREAD

**Issue by Mukundan314** [onivim/oni#1656]
opening a file with tabs causes the tabs be shown as ^I and typing tab in oni causes me to have 4 spaces instead of a tab.

**Comment by CrossR** [comment]
Hi,

This is an issue with the settings that are currently in the default Oni vim config, which we need to sort...

Until then, if you add `"vim.setting.list": false,` to your `config.js` (accessible with `<Ctrl+P>` and typing User Config) it should be fixed.

**Comment by badosu** [comment]
@Mukundan314 Also see https://github.com/onivim/oni/wiki/How-To:-Make-Oni-closer-to-bare-Vim-experience to override Oni's defaults
