### ISSUE TITLE
Getting network error after 11mb downloaded on both latest windows .exe and .zip releases

### ISSUE THREAD

**Issue by drzel** [onivim/oni#1664]

**Comment by bryphe** [comment]
Hi @drzel - that's strange. I just tried them out and they seem to work (I tried the latest release here: https://github.com/onivim/oni/releases/download/v0.3.0/Oni-0.3.0-ia32-win.exe)

Might be a transient network issue - I'll close for now, but please let me know if you are still unable to download.

The binaries are also available directly from the AppVeyor machines so we could try that too as a backup.
