### ISSUE TITLE
Don't open a new tab for every specified file

### ISSUE THREAD

**Issue by Uroc327** [onivim/oni#1680]
Is there any way to prevent oni to open a tab for every file from the command line? I'd prefer it to just have a single tab, containing any single one of the provided files.

**Comment by franc0is** [comment]
I have the same issue. Would it be possible to get a configuration option to make "open" default to "open in new tab" or "open in active tab"?

**Comment by CrossR** [comment]
I think the original issue here (opening from the commandline opening in a new tab) should be fixed now with the swap to using vim-tabs.

@franc0is , are you using the commandline or the QuickOpen UI (`<Ctrl+P>`)? If its the QuickOpen UI, we could certainly add a config option for the default behaviour, but until then you can use `Ctrl+Enter` to open in the current buffer.

If its the commandline and the latest version of Oni (0.3.1) then it should work as expected. Pre 0.3.1 we were opening all files in new tabs, but now its only when `:tabe` is used, as expected.

**Comment by tmandry** [comment]
> If its the QuickOpen UI, we could certainly add a config option for the default behaviour, but until then you can use Ctrl+Enter to open in the current buffer.

Thank you! I was looking for this. A config option would be nice, not sure if that's another issue.

Also, Ctrl + click on a filename in the File Explorer doesn't open in the current buffer.

**Comment by franc0is** [comment]
> @franc0is , are you using the commandline or the QuickOpen UI (<Ctrl+P>)?

yep!

> If its the QuickOpen UI, we could certainly add a config option for the default behaviour

That would be *awesome*

> until then you can use Ctrl+Enter to open in the current buffer.

Oh! I tried a bunch of key combinations, but evidently I must have missed this one. Thank you!

**Comment by CrossR** [comment]
Bit of a delay due to work but with #2080 I've added a config option for rebinding the `Enter` and `Ctrl-Enter` keybinds.

```
    "editor.quickOpen.defaultOpenMode": Oni.FileOpenMode.ExistingTab,
    "editor.quickOpen.alternativeOpenMode": Oni.FileOpenMode.Edit,
```

Will invert the logic, such that `Enter` opens in the current buffer by default, and `Ctrl-Enter` will open in a new tab. (Edit is called edit since it dynamically picks what is the appropriate way to open the file based on the users tab mode, though is a slightly confusing name).

**Comment by CrossR** [comment]
I'll close this out for now, since I think everything is addressed.
