### ISSUE TITLE
Welcome screen doesn't release input

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1695]
In the latest master, I'm seeing the Welcome screen not giving up input to buffers.

By that I mean that `hjkl` etc work like normal there, but if I open a file with `Ctrl+P` or the Explorer or File > Open, or really any way that is done with Oni opening with the Welcome screen, the `hjkl` and any input at all doesn't work for me. (I'd try `:e` but that is swallowed by the Vim layer that provides the movement. Is it worth a ticket for that or general expansions to it like viability of adding `/` etc?)

I'd post the logs...but the keys don't even appear in the logs. They do on the welcome screen, but not once a file is opened.

If I disable the Welcome experience, or open a file directly (ie double click a file etc) so the welcome experience isn't shown, Oni works as expected.

**Comment by bryphe** [comment]
Might be a dup of #1413 or #1459 - there are definitely some input issues with the welcome experience

**Comment by CrossR** [comment]
Seems like both of those issues cover it! I'll close this one out and keep an eye on them in case anything needs testing or messing with.

**Comment by bryphe** [comment]
Cheers, thanks @CrossR !
