### ISSUE TITLE
support Rust??

### ISSUE THREAD

**Issue by Matrix-Zhang** [onivim/oni#1712]
does support rust?

**Comment by bryphe** [comment]
Hi @Matrix-Zhang ,

I think this is a dup of #385. Since Rust has a language server, it should be supported via the configuration settings we have documented here: https://github.com/onivim/oni/wiki/Language-Support#language-servers

Would be great to have someone try and see if it works 👍

**Comment by bryphe** [comment]
Closing this as a dup of #385
