### ISSUE TITLE
Can't type quotation mark(")

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1713]
Report from @finex:

Hi, I'm trying onivim (v0.3.0) and it doesn't accept quotation mark ( " ) which needs a three keys combination. Other chars like ~ (just two key combination) works as expected. I'm using the following keyboard settings (Archlinux/KDE):

    rules: evdev
    model: pc105
    layout: us
    variant: intl
    options: eurosign:

Please tell me if can give you more details. Thanks!

**Comment by CrossR** [comment]
Hmmm....I've had issues with `"` when I've swapped back and forth between keyboard settings (ie UK <-> US) #1058.

First thing to check would be the logs. Would you be able to run `Oni.log.enableDebugLogging()` in the Dev Tools console, and post the output of you trying to press `"`? (`Ctrl+Shift+P` then Dev Tools).

It should then start showing what keys Oni is attempting to resolve, so we have a bit more of an idea.
An example of the sort of output you should get can be seen in the ticket I linked above.

**Comment by finex** [comment]
Ok, I've just tried, this is the log while I press `"` (ctrl + shift + ')

```
[Key event] Code: ShiftRight Key: Shift CtrlKey: false ShiftKey: true AltKey: false | Resolution: null

bundle.js:1 [REDUX - NeovimEditor0][ACTION] SET_CURSOR_SCALE

bundle.js:1 [Key event] Code: ShiftRight Key: Shift CtrlKey: false ShiftKey: true AltKey: false | Resolution: null

bundle.js:1 [Key event] Code: AltRight Key: AltGraph CtrlKey: false ShiftKey: true AltKey: false | Resolution: null

bundle.js:1 [REDUX - NeovimEditor0][ACTION] SET_CURSOR_SCALE

bundle.js:1 [Key event] Code: AltRight Key: AltGraph CtrlKey: false ShiftKey: true AltKey: false | Resolution: null

bundle.js:1 [Key event] Code: Quote Key: " CtrlKey: false ShiftKey: true AltKey: false | Resolution: <s-">

bundle.js:1 [REDUX - NeovimEditor0][ACTION] SET_CURSOR_SCALE

bundle.js:1 [Key event] Code: Quote Key: " CtrlKey: false ShiftKey: true AltKey: false | Resolution: <s-">
```

**Comment by Cryza** [comment]
I've had the same issue on a Windows 7 machine with the US keyboard layout, i.e. the combination for the `"` key would only require shift+' for me and it also doesn't work. Maybe that helps narrow the source of the bug down

**Comment by GlassGruber** [comment]
Yea same very thing happened to me, and I use also a double language input on Windows 7.
Don't know if this can help, here is a little screen record.

![onivim](https://user-images.githubusercontent.com/1172428/38300814-1b9318a0-37fe-11e8-9210-6b9bc61c7e2a.gif)

**Comment by Kxze** [comment]
Same thing here. Fedora 27 if it helps.

**Comment by Svampson** [comment]
I have the same issue, I'm running a multi-language setup on Windows (Swedish/US) and when I'm using the US layout it won't recognize the quotation mark (`Shift` + `'`). My console output mirrors the one from @finex above.

For other people who are affected by this bug I simply added this hack
` oni.input.bind("<s-\">", () => Oni.editors.activeEditor.input("\""));`
to my config and now it seems to work.

(If you are not using US layout simply change the bind to whatever resolution the key event outputs after running `Oni.log.enableDebugLogging()` and trying to input a quotation mark)

**Comment by finex** [comment]
Hi, I've updated to 0.3.6 and the bug seems gone. Thanks :+1:

**Comment by Govinda-Fichtner** [comment]
I still have the same issue with onivim 0.3.6 on Ubuntu 18.04. Happens for me when I switch the keyboard layout from german to us and while having an onivim session open.

**Comment by badosu** [comment]
@finex particular problem is fixed, so ideally this thread would be closed.

However, it seems that other people have issues.

Can you elaborate your issues? Ideally on new threads so that we can differentiate distinct problems

**Comment by CrossR** [comment]
I think other people are having the same problem as my other issue: #1058.

Potentially we can close this and use my issue which has a bit more information in.

**Comment by badosu** [comment]
Ok, closing this in favor of #1058
