### ISSUE TITLE
Moving through snippet placeholders crashes editor

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1715]
Whilst tabbing through snippet placeholders (very cool functionality btw) I occasionally (well almost always eventually get an editor crashing error). Apologies for not enough detail will look into it more when I get a moment.

<img width="776" alt="screen shot 2018-03-04 at 22 15 49" src="https://user-images.githubusercontent.com/22454918/37024029-ae698254-211f-11e8-839d-c891d544e08f.png">

**Comment by bryphe** [comment]
Should be resolved now by #1718 . Hopefully you can actually use the snippets now!
