### ISSUE TITLE
Typing problems in StatusResize component

### ISSUE THREAD

**Issue by LucianBuzzo** [onivim/oni#1726]
In the [StatusResize](https://github.com/onivim/oni/blob/master/browser/src/UI/components/StatusResize.tsx) component an element is added to the `children` object here https://github.com/onivim/oni/blob/master/browser/src/UI/components/StatusResize.tsx#L109 but the object doesn't match the type declaration in state here https://github.com/onivim/oni/blob/master/browser/src/UI/components/StatusResize.tsx#L25
As you can see the `alignment` and `passWidth` attributes are not present. 
This will cause the build to fail if you install dependencies with `npm` instead of `yarn`.

I'm happy to send a PR to fix this issue if you like.

**Comment by bryphe** [comment]
Hi @LucianBuzzo ,

Nice catch! I've seen this pop up a few times but didn't know what the root cause was - really appreciate your investigation.

> I'm happy to send a PR to fix this issue if you like.

That would be great! 👍
