### ISSUE TITLE
VimNavigator: Allow editing the folder structure in explorer

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1737]
Having the ability to edit files and directories in the explorer using the vim commands would be very useful.

I'm not fully sure what makes the most sense but I see a few different things we'd need:
* New/Add File
* New/Add Folder
* Rename item
* Move Item
* Delete Item

Delete being `d` or `x` would make sense, same for using the normal `y`+`p` for moving/copying etc.
`a` or `i` possibly for adding a new file? I'm less sure on that, and how you can distinguish between a file and folder. Rename probably makes sense to be `r`.

Some parts of this have already been added by @Akin909, so we could potentially just call the code he has already written, at least for moving files etc.

That is all of the top of my head, if anyone has used the in Vim options more than I have, I'd be interested to know what you think makes more sense. We could also nick ideas from something like Ranger, which is a text based file explorer that has vim-style keybinds.

**Comment by Akin909** [comment]
@CrossR this seems like a really cool idea and much more *vim* than dragging and dropping 😆, yes the `moveFileOrFolder` function could definitely be re-used here all in all depending on how exactly the `vimNavigator` works this could potentially be easier to implement dragging and dropping since there are no moving parts. Was thinking of something similar/but not quite the same in #1536, but this I think would remove the need for a menu or icons just some visual indication when yanking or pasting.

**Comment by badosu** [comment]
I think this is a great idea, but I suggest adding a prefix character so that's not too easy to make mistakes. e.g. `<leader>d` to delete a file.

This prefix character can be used on all file changing commands.

**Comment by Akin909** [comment]
I think atm `Oni` can't take chorded input like `<leader>d` although the more oni commands we rack up the more of a need I think we have for it but think there's already an issue tracking it #1055. A simple alternative would be binding `<ctrl-d>` etc only whilst in the explorer.

**Comment by Akin909** [comment]
Regarding this functionality one thing I'm currently not clear on re possible implementation @bryphe is how or if the `vimNavigator` deals with `y`, `p` etc. commands?

**Comment by bryphe** [comment]
This would be awesome! If we can address these bullets in our explorer, we'll be in a great place to having full parity with NERDTree/netrw.

> Regarding this functionality one thing I'm currently not clear on re possible implementation @bryphe is how or if the vimNavigator deals with y, p etc. commands?

Right now, if we don't have a binding for those keys, we send them to the underlying `SharedNeovimInstance`, which would execute yank/paste, but we wouldn't act on it in anyway. The buffer _should_ be made not modifiable  too to enforce this.

There are two possibilities when it comes to implementing features like this:
- We add bindings for the explorer for `y` and `p` _above_ the SharedNeovimInstance - the neovim layer doesn't care about these, we add internal state to our redux store to track / do special rendering, etc. 
- We generalize `y` and `p` and listen to events from the SharedNeovimInstance (like `onYank`, `onPaste`), and then translate them over.

IMO the first one is probably the most straightforward. For example, yank and paste wouldn't make sense for the sidebar icons or welcome screen - so having it only in the explorer seems reasonable, and wouldn't be too bad to implement (on yank, we'd keep tracking of the selected file path, and on paste, we'd call the `moveFile` method that is backing the drag and drop). Same with new file/new folder, etc.

Oh and I forgot about this... but we actually have a delete file command (implemented in a similiar way as described above)
https://github.com/onivim/oni/blob/6d9cd90e1c20bc2c4ae3ce087f8695d5856457b0/browser/src/Services/Explorer/ExplorerSplit.tsx#L73

**Comment by badosu** [comment]
Since #1839 was merged and on stable releases for a while, this can be closed.
