### ISSUE TITLE
VimNavigator: Add h/l for expanding/closing folders in explorer.

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1738]
Hitting enter to open the folders and ....I'm not actually sure what to close them, isn't the best, at least coming from using stuff like Ranger.

Adding `h` to contract or `l` to expand would be pretty natural feeling, and make getting around the explorer easier I think.

**Comment by badosu** [comment]
Dullicate of #1442.

Good suggestion for h/l.

**Comment by CrossR** [comment]
More info over there, so I'll just copy my idea on to that ticket!
