### ISSUE TITLE
File explorer: no way to increase its size

### ISSUE THREAD

**Issue by magopian** [onivim/oni#1741]
The file explorer cannot be widened, preventing some files to be fully displayed. See the following screenshot where the root folder isn't visible:

<img width="327" alt="screen shot 2018-03-08 at 10 43 38" src="https://user-images.githubusercontent.com/167767/37144344-0b526e78-22be-11e8-9f64-628df2fa574e.png">

I'm not sure if the file explorer should be resizable, or scrollable horizontally, or even if hovering over an entry should display a tooltip.

**Comment by badosu** [comment]
Duplicate of https://github.com/onivim/oni/issues/1414
