### ISSUE TITLE
Suggestion: add builtin command to send open files to existing instance from command line

### ISSUE THREAD

**Issue by Lucas1993** [onivim/oni#1753]
Pretty much what's on the title. 

A major pet peeve with gui editors is the inconvenience that happens when you are running commands and exploring folders on the terminal and find a relevant file to open. There are solutions for this for neovim, but a builtin command (something like oni -send file.txt) would be great. 

I don't think a GUI editor can ever trully replace terminal vim for quick editing on terminal, but there a lot of times when this feature would come in handy!

**Comment by bryphe** [comment]
Thanks for the issue, @Lucas1993 ! It would be great to have an option like this - I believe this may already be captured by #1707

**Comment by CrossR** [comment]
I'm going to close this out since I'm tracking this over in #1707.
