### ISSUE TITLE
Fuzzy finder highlighting would look better with bold instead of underlining

### ISSUE THREAD

**Issue by rgehan** [onivim/oni#1767]
I find the underlining of separate letters a bit hard on the eye. It obfuscates the words a bit.

Let's compare how VSCode looks vs. how Oni looks:

![capture d ecran 2018-03-10 a 18 00 43](https://user-images.githubusercontent.com/793402/37244693-291b61e6-248d-11e8-9282-da8a03929cff.png)

![capture d ecran 2018-03-10 a 18 00 51](https://user-images.githubusercontent.com/793402/37244694-2ad957c2-248d-11e8-9f58-820ffbe9874f.png)

I think bolding the matches would look a bit more polished

**Comment by bryphe** [comment]
👍 , I'm open to changing this

If someone is up for taking a look at this - the component that handles the highlighting is around here:
https://github.com/onivim/oni/blob/3c88c847e3c55ac0f23bb945c9709deeb9021d02/browser/src/UI/components/HighlightText.tsx#L42

**Comment by chenglou** [comment]
Sublime Text bolds + uses another color: 
<img width="592" alt="screenshot 2018-03-13 22 37 36" src="https://user-images.githubusercontent.com/1909539/37385003-259926be-270f-11e8-94ab-e0c4d4ee2abd.png">

**Comment by badosu** [comment]
Seems like this is fixed in the latest release.
