### ISSUE TITLE
oni.statusbar.enabled

### ISSUE THREAD

**Issue by mg979** [onivim/oni#1771]
It seems there are two settings that control this, `oni.statusbar.enabled` and `statusbar.enabled`.

Setting the former to false doesn't do anything on its own. I have to set `statusbar.enabled` to false instead. Moreover, if statusbar is enabled but sidebar is not, the statusbar shows incomplete infos.

Just reporting this because it seems a bug, I don't use neither sidebar nor statusbar (please keep this possibility...).

**Comment by bryphe** [comment]
Thanks for catching this @mg979 ! Looks like it was an error on our features page:  https://github.com/onivim/oni/wiki/Features#status-bar

Just corrected it.

**Comment by mg979** [comment]
I think there is some general problem with `sidebar.enabled`. It seems it affects more than just sidebar, because if it's false, quickinfo doesn't work anymore, and also the statusbar infos are incomplete.

**Comment by mg979** [comment]
This is the config I'm using (the rest is defalult)

```
module.exports = {
    activate,
    deactivate,
    //add custom config here, such as

    //////////////////
    // default

    "ui.colorscheme": "nord",
    "oni.useDefaultConfig": true,
    "editor.fontFamily": "Monaco",
    "editor.clipboard.enabled": false,
    "ui.animations.enabled": true,
    "ui.fontSmoothing": "auto",

    //////////////////
    // working

    "statusbar.enabled": false,
    "oni.hideMenu": true,
    "tabs.mode": "native",
    "commandline.mode": false, // Do not override commandline UI
    "wildmenu.mode": false, // Do not override wildmenu UI

    ////////////////////////////////////
    // quickinfo not working

    //"oni.useDefaultConfig": false,
    //"oni.loadInitVim": true,
    //"sidebar.enabled": false,
}
```

**Comment by mg979** [comment]
If I set

    "oni.useDefaultConfig": false

this loads nvim init.vim, so not sure what

    oni.loadInitVim": true

would add to this.

In any case, loading my init.vim alone breaks quickinfo.

Also setting this alone breaks quickinfo:

    "sidebar.enabled": false

**Comment by CrossR** [comment]
What version of Oni are you running @mg979 ?

We have #1548 and #1562 relating to the issues you are seeing, where the first is fixed now in master. I think the second has an on-going fix as well.

As for the other bits, some users will want to have both the Oni default config + there own init.vim which is why there is two config options. Also, `oni.loadInitVim` accepts a path to an `init.vim` such that you can have an Oni specific config rather than using the system default.

**Comment by mg979** [comment]
Thanks. I'm running Oni 0.3.0 (latest release).
