### ISSUE TITLE
Marks window flicker

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1773]
With `    "sidebar.marks.enabled": true,`, I occasionally get a small flicker on swapping between tabs or splits. I'm assuming it is because of that setting, but I can't fully tell. The flicker seems to be the `:marks` menu opening for a moment.

Has anyone else noticed this sort of behaviour?

**Comment by bryphe** [comment]
Ah yes, this is a dup of #1461  - the problem is we use `nvim_command_output` to read the marks... but it actually causes some output to end up being rendered.

**Comment by bryphe** [comment]
I'll close this out, but feel free to re-open if #1461 doesn't capture it.
