### ISSUE TITLE
Enhancement/ Explorer-rename-functionality

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1840]
Oni currently is in a good position to add loads of functionality to the explorer menu one example of which is renaming a file.

Whilst working on #1839 it occurred to me that this could be done with `shelljs` though the biggest blocker here is that we currently dont have a confirm/input notification ui or perhaps we could reuse that of the `Rename Symbol` ui but given how that currently renders aka quite small with no clear ui for confirming or declining might need to be tweaked for more general use cases

**Comment by keforbes** [comment]
Addressed in #2115.  Closing.
