### ISSUE TITLE
Documentation: Configuration links to installation guide

### ISSUE THREAD

**Issue by city41** [onivim/oni#1859]
On the documentation site, https://onivim.github.io/oni-docs, the "Configuration" link in the left hand menu goes to https://onivim.github.io/oni-docs/#/./oni.wiki/Installation-Guide

I think it should go to https://onivim.github.io/oni-docs/#/./oni.wiki/Configuration

**Comment by bryphe** [comment]
Thanks for catching this, @city41 ! Looks like @599316527 fixed this for us in onivim/oni-docs#11 - just brought it in.
