### ISSUE TITLE
Explorer filepath not set when called from command line

### ISSUE THREAD

**Issue by importjake** [onivim/oni#1860]
Calling `oni .` for example from within a project does not set the explorer to be active on the supplied directory. Example (I was calling `oni .` in a project directory of mine named `cryptrack-client`) but when oni opened the explorer was active on my previous open project (a typescript workshop).

![screen shot 2018-03-20 at 8 24 31 am](https://user-images.githubusercontent.com/3849309/37664572-ce7948dc-2c18-11e8-93be-092b9c6c25c1.png)

**Comment by CrossR** [comment]
Hi,

The command line calling of Oni isn't quite where it should be yet...
There is a comprehensive list of proposed changes over in #1707, which I think addresses the issue you have here.

Setting `  "workspace.autoDetectWorkspace": "always",` will get you part of the way there - It will auto change the workspace to the current files project, but I think currently it doesn't support opening folders. Ie `oni .` won't change the explorer workspace until you load a file. `oni LICENSE` would auto change it.

We could use this ticket to track the small change of having that option work with folders, and use the other for the bigger changes that are needed to the commandline.

**Comment by badosu** [comment]
Closing this in favour of https://github.com/onivim/oni/issues/2163 and #1707 to track cli usage of Oni.
