### ISSUE TITLE
diff on windows 10 not working

### ISSUE THREAD

**Issue by fpn** [onivim/oni#1864]
![image](https://user-images.githubusercontent.com/1007715/37672943-459af09c-2c2c-11e8-909b-bba1d07ecbba.png)

oni version 0.3.1

**Comment by justinmk** [comment]
That would be a `nvim` bug. What version is oni currently using?

**Comment by bryphe** [comment]
Thanks @justinmk !

We currently package the `0.2.2` binaries (https://github.com/neovim/neovim/releases/tag/v0.2.2) with OSX and Windows (for Linux, we rely on a local installation).

@fpn - which OS are you using? Can you share the exact set of commands you used to reproduce this?

**Comment by fpn** [comment]
windows 10

I am a little bit baffled - now I can't reproduce it (after having it all day yesterday). Will keep an eye on it - at this point I am happy it works again ... will keep an eye on it

typically I do something like
```
:lcd C:\foo
:e .
#open a file
:diffthis
#<ctrl>w r
:diffthis
```

I feel somehow neovim couldn't get its temp folder - but no idea why / how that works / where to look.

**Comment by badosu** [comment]
@fpn Let us know if you can reproduce this error and we can reopen this issue (or delegate to a neovim issue).
