### ISSUE TITLE
Unable to scroll through autocomplete suggestions

### ISSUE THREAD

**Issue by ExpectationMax** [onivim/oni#1874]
It is not possible to scroll down to completion suggestions outside of the initial view of the completion box.
The view does not scroll down when elements further downward are selected, neither does the additional description field update.

Regular view:
<img width="657" alt="screen shot 2018-03-21 at 11 14 49 am" src="https://user-images.githubusercontent.com/1303655/37704473-2f027b8e-2cf9-11e8-9dfb-aa514699c5d0.png">

Pressing \<ctrl-n\> to scroll down
<img width="676" alt="screen shot 2018-03-21 at 11 15 07 am" src="https://user-images.githubusercontent.com/1303655/37704483-340a717c-2cf9-11e8-918a-8f43900da6d4.png">

I experienced this problem on macOS high Sierra using Oni version 0.3.1 .

**Comment by badosu** [comment]
Yes
