### ISSUE TITLE
Config.js ignored on master

### ISSUE THREAD

**Issue by TalAmuyal** [onivim/oni#1875]
Don't know if it's intended, but on `master`, my yet-to-be-converted configs arenp loaded.
Works fine with v0.3.1.
Tried on MacOS.

Can't do more that log it right now...

**Comment by bryphe** [comment]
This is likely due to #1792 - I think you'll have to move the `config.js` to ~/.config/oni .

**Comment by badosu** [comment]
Yes, this is not documented at the moment.

@bryphe Should we wait for the release or go ahead and change `README.md` and the wiki?

**Comment by TalAmuyal** [comment]
Thanks, will verify and close this issue.

**Comment by TalAmuyal** [comment]
Verified, thanks!

**Comment by TalAmuyal** [comment]
BTW (for reference), solved using `ln -s ~/original-path/config.js ~/.config/oni/config.js`.
Should work for all non-Windows OSs.
