### ISSUE TITLE
Typing :: quickly in command bar expands to output of pwd

### ISSUE THREAD

**Issue by hboon** [onivim/oni#1885]
In normal mode, after I type / (or :) (and the command bar shows up), if I type : twice quickly, it expands to the output of `pwd`. Is this a bug or if not, is there a way to disable it? (I search for :: often)

On v0.3.0

**Comment by Akin909** [comment]
@hboon I believe we used to have a `commandline` abbreviation in oni's default config which was recently removed in master so the next release should resolve this issue for you.

**Comment by hboon** [comment]
Verified fix in master. Thanks.
