### ISSUE TITLE
Reloading Oni with multiple instances makes the UI appear in the last instance.

### ISSUE THREAD

**Issue by muream** [onivim/oni#1916]
Hey, sorry for the bad title, couldn't find a short way to explain this.

Steps to reproduce:
* Open two or more Oni instances
* Reload any oni instance but the last
* the the reloaded one stays blank and the last one contains both UIs, like so:
![oni-bug](https://user-images.githubusercontent.com/3117205/37867851-a4fb69fc-2f9e-11e8-9c61-eeb8d398328c.PNG)

This adds up, the more instances of Oni you reload.

**Comment by CrossR** [comment]
Hey @muream!

Can I check what version of Oni you are running?
I made a change to how we reference the editors in the main process, so I think this should be fixed on master. (@Akin909 had a similar issue over here: #1696)

If that isn't the case, we should look into it some more.

**Comment by muream** [comment]
Oh, I only searched the open issues, I'm running 0.3.1.

**Comment by muream** [comment]
I just tested this in master and can confirm that it does not occur anymore
