### ISSUE TITLE
Typing : after bringing up the externalised command line with : or / is slow

### ISSUE THREAD

**Issue by hboon** [onivim/oni#1919]
Type `:` or `/` in normal mode to show the command bar and press `:` immediately. it takes ~2 seconds for the `:` to appear. Other keys seems to appear almost immediately.

i.e. in normal, mode type:

`:` followed by `:`, the command bar shows up immediately and it takes 2 secs for the `:` to appear
`/` followed by `:`, the command bar shows up immediately and it takes 2 secs for the `:` to appear
`:` followed by `x`, the command bar shows up immediately and the `x` appears immediately

v0.3.1.

Maybe related to #1885?

PS: is "command bar" the right terminology?

**Comment by hboon** [comment]
To answer my own question. It's called the [Externalised Command Line](https://github.com/onivim/oni/wiki/Configuration#externalised-command-line)

**Comment by Akin909** [comment]
@hboon re the delay in the startup we had some commandline abbreviations which have a timeout before expanding, so this could possibly have accounted for the delay.

We've since remove these from oni's `init.vim` so this should no longer be an issue are you running the latest release (where this issue might still be present) or running a build off of the master branch?

**Comment by hboon** [comment]
I haven’t checked if there’s a newer build, but I’m running the release dmg for v0.3.1. Maybe it’s no longer present in the master branch. Is the master branch generally stable enough to use as my main editor?

**Comment by Akin909** [comment]
I work off master and we work hard to keep it stable but development moves fast so I'd say it depends a little on how adventurous you are, although by working off master you'd get the latest features and fixes and could help by reporting any bugs, up to you. Either way @bryphe I believe tries to release every two weeks so should be one soon with the latest fixes which *hopefully* will resolve this issue

**Comment by hboon** [comment]
Thanks. I’ll see if it works for me. Might make it easier for everyone in case I reports issues that have already been worked on :)

**Comment by hboon** [comment]
Ok. Verified to be fixed on master. Thanks @Akin909
