### ISSUE TITLE
Tutorial improvements

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1924]
Just a few small notes on the tutorials, so they are written down somwhere:

* Currently, the tutorials themselves are not clickable or sneakable, which makes discovery of using them hard.
* The end screen of the tutorial doesn't respond to different screensizes, meaning it can overflow on certain machines.
* Currently, the `init.vim` seems to be loaded, which possibly isn't wanted. (Similarly, some are editable which may not be wanted).
* Swapping between tutorials doesn't work - Ie open tutorial 2 and select tutorial 1, it is re-focuses tutorial 2.
* The first tutorial has 10 lines, and can only fit 9 on screen, meaning its possible to scroll off and end up with the goal looking reached, when in reality its on line 1 and the cursor is on line 2. (See below).
![image](https://user-images.githubusercontent.com/10038688/37880894-53d8b2de-3087-11e8-8480-64e672d2d308.png)

Sorry for dumping a bunch of them! I'm actually really excited about this feature, and all the things above are small changes.

**Comment by bryphe** [comment]
Sorry, didn't mean to close this - only resolved a piece of it so far 😄
