### ISSUE TITLE
Go completion does not appear to be implemented

### ISSUE THREAD

**Issue by ijt** [onivim/oni#1928]
I ran `go get -u github.com/sourcegraph/go-langserver` and go-langserver was installed in my $PATH, but Oni doesn't seem to use it. When I edit a Go file and type `fmt.` somewhere in a function body, no menu of completions comes up. It also doesn't come up if I hit ctrl+space. I also tried adding 

```
    "language.go.languageServer.command": "go/bin/go-langserver",
```
to the 
```
export const configuration = {
```
section of the Oni config, but it seems not to have made any different. Is this broken or am I doing it wrong? Also, why can't this functionality just be included in Oni?

**Comment by Contextualist** [comment]
Some advice for troubleshooting:
1. Look at the bottom-left. Is there a rotating circle or a lighting bolt? If you see a rotating circle, the langserver isn't start properly.
2. In case you see a rotating circle, Oni might fail to find the langserver binary indicating in your config. Is your `$GOPATH/bin` in you `$PATH`? If not, you may use absolute path
```
    "language.go.languageServer.command": "/ABSOLUTE/PATH/TO/go-langserver",
```
3. A rotating circle can also mean that the langserver exit unexpectedly. You may wish to open devtool (hit `Shift-Ctrl/Command-P` and type `dev` enter) and check the console for error message.

Hope these would help.

**Comment by saibing** [comment]
@ijt 

```ts
    // language server configuration
    "language.go.languageServer.rootFiles": [".git"],
    "language.go.languageServer.command": ["go-langserver"],
    "language.go.languageServer.arguments": ["--gocodecompletion", "--freeosmemory", "false"],
```
You must set the --gocodecompletion parameter to enable the completion function

**Comment by Akin909** [comment]
Added your snippet @saibing to the documentation, thanks 👍

**Comment by ijt** [comment]
Thanks for that. I did indeed have a spinning circle before because my path
to the "language.go.languageServer.command" was wrong. So I restarted Oni
and opened a Go file, now seeing a lightning bolt. So far so good. But I
still have no indication of anything like Intellisense working in this
file. For example, I tried typing "os.<ctrl+space>" and "os.E" and didn't
see any menu of completions.

**Comment by ijt** [comment]
My bad -- I hadn't included these lines:

"language.go.languageServer.rootFiles": [".git"],

"language.go.languageServer.arguments": ["--gocodecompletion",
"--freeosmemory", "false"],

I added them and now completion works fine.

**Comment by badosu** [comment]
Since @ijt provided the fix and stated it's working, let's close this one.
