### ISSUE TITLE
vimtex plugin not properly loaded

### ISSUE THREAD

**Issue by saward** [onivim/oni#1938]
Hi,

I've tried to include vimtex as a plugin by adding it to ~/.oni/plugins.  Having done so, I can now run ':h vimtex' and see the help file inside oni.  However, when I try to run commands such as VimtexCompile, it tells me "Not an editor command: VimtexCompile".

Is there something else I'm supposed to do to make the commands for this plugin accessible?

Thanks

**Comment by CrossR** [comment]
Hi!

Shouldn't need to do anything extra to use the commands inside Oni.
I've got vimtex installed and have had no issues running the commands, though its odd you are unable to, especially if you can see the help files.

Have you tried using it whilst installed via a more traditional means (ie using the built in vim-plugin system or a plugin manager like `vim-plug)?

**Comment by saward** [comment]
@CrossR I haven't tried vim-plug yet.  Are you using a plugin system like that with oni yourself, or does it work for you just copying the files into the right folder?

**Comment by CrossR** [comment]
I'm using it via `vim-plug` since I use my config across some machines I can't easily use Oni on, though it should work in `~/.oni/plugins` (or `%APPDATA%/oni/plugins` folder on Windows).

I'll give it a try now and get back to you.

**Comment by CrossR** [comment]
Sorry for the massive delay, I've had a bunch of work...

Did you get any further with this?
I managed to get it working for both with a vim plugin manager and via Oni's plugin folder.

It should just be a case of copy and paste in there, and then done. The plugin won't activate until you load a latex file I think, but apart from that you should be fine.

**Comment by badosu** [comment]
@saward If you're using `>= 0.3.2` you should place your plugins on `.config/oni/plugins` now.

**Comment by badosu** [comment]
@saward Can you check if you still have this issue?

**Comment by saward** [comment]
Looks like it is working.  It may even have always been working and I wasn't operating things correctly.  Closing for now.
