### ISSUE TITLE
Weird infinite-loop 100% cpu usage interaction between oni and deoplete and HTML files

### ISSUE THREAD

**Issue by robin-pham** [onivim/oni#1940]
Reproduction steps:
1. Configure oni to use init.vim
2. Setup the init.vim with [deoplete](https://github.com/Shougo/deoplete.nvim#install) 
4. Edit an html file, try to prompt suggestions by going into insert mode and start to type inside an html tag, e.g.  `class="type here"`.

![screenshot_2018-03-26_22-47-20](https://user-images.githubusercontent.com/5697723/37949118-209052a8-3148-11e8-90d7-fd182415393b.png)
![screenshot_2018-03-26_22-47-54](https://user-images.githubusercontent.com/5697723/37949117-1f297b24-3148-11e8-8876-f664e4e1a9c4.png)
^ browser console keeps on complaining about 'No grammar found for language: html'

This is a pretty bizarre bug, just writing it down here in case other people encounter the same issue.

P.S: Oni is realllly coool.

**Comment by bryphe** [comment]
Thanks for reporting @robin-pham ! Yes, that's strange - we definitely shouldn't be trying to query for that grammar file so often.
