### ISSUE TITLE
cquery as default LSP for c++

### ISSUE THREAD

**Issue by ram535** [onivim/oni#1970]
It seems other editors like [emacs](https://github.com/cquery-project/cquery/wiki/Emacs), [neovim](https://github.com/cquery-project/cquery/wiki/Neovim), vscode, etc. are adapting faster [cquery](https://github.com/cquery-project/cquery) than clangd.
And it looks like cquery is mostly ready to be used and improving rapidly.

**Comment by free-easy** [comment]
+!

**Comment by MaskRay** [comment]
You may also consider https://github.com/MaskRay/ccls/wiki/Getting-started

Recent revamp to completion and diagnostics makes it pretty smooth. The cross reference support is also good https://github.com/MaskRay/ccls/wiki/LanguageClient-neovim#custom-cross-references
