### ISSUE TITLE
Can't repeat vim commands even though holding key down in normal mode

### ISSUE THREAD

**Issue by grezar** [onivim/oni#1974]
## Problem
In vim or pure neovim, while holding key down, vim commands are repeated. But oni doesn't work like that.
Vim commands mean like `e`, `w`, `j`, `k` in this case.
I don't know where this problem is caused.

## Expected
While holding key down, vim commands are repeated.

**Comment by grezar** [comment]
#1888 this issue seems to be same.

**Comment by CrossR** [comment]
Does the "fix" outlined on the wiki work for you? Ie running the following in the terminal:

`defaults write com.extropy.oni ApplePressAndHoldEnabled -bool false`

#1888 is to do with automating/making this process a bit easier, since its currently awkward.

**Comment by grezar** [comment]
I have just run it and works. I'm very looking forward to use oni.
Thanks! 😄
