### ISSUE TITLE
Tutorial Proposal: Finding within a line - `f`, `F`, `;`, and `,`

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1978]
A helpful tutorial to have would be in linewise-character finding, exercise the following commands:
`f` - find a character
`F` - find a character (reverse)
`;` - next match
`,` - previous match

A good example for this would be the `BasicMovementTutorial`: https://github.com/onivim/oni/blob/master/browser/src/Services/Learning/Tutorial/Tutorials/BasicMovementTutorial.tsx

We'd just need to figure out the set of text that makes sense, and add the appropriate `Stages.MoveToGoalStage` to exercise those motions.

The tutorials are relatively straightforward to add, so this would be a fun and visible `first issue` if anyone is up for it 👍

**Comment by robin-pham** [comment]
I'd be pretty happy contributing to this project. What does the `insider` tag mean though?

**Comment by bryphe** [comment]
@robin-pham - that would be great! Would ❤️ help here, and contributions are most welcome.

The bot tags issues with `insider` for people who've contributed to the project via Patreon/Bountysource/OpenCollective. Helps me as a maintainer figure out how to prioritize issues (I try to prioritize first). But there are lots of ways to contribute to the project, and a PR would be awesome.

If you need help getting started, let me know!

**Comment by keforbes** [comment]
@robin-pham, are you still working on this feature?  Do you need any help?

**Comment by keforbes** [comment]
There's no rush at all, I just wanted to see if you were actually working on it or if this was just a random flyby comment. :slightly_smiling_face:

**Comment by brian-yu** [comment]
Hey @robin-pham, are you still working on this issue? If so, no worries and good luck! If not, I'd like to pick this up.

**Comment by robin-pham** [comment]
@brian-yu ahh I completely forgot. Yeah I've been pretty bad at working on this, you can definitely take pick this up.

**Comment by keforbes** [comment]
#1978 has been merged in.
