### ISSUE TITLE
Tutorial Proposal: Find across a buffer - `/`, `?`, `n`, `N`

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1979]
A helpful tutorial to have would be in searching across a buffer, exercising the following commands:
`/` - find 
`?` - find (reverse)
`n` - next match
`N` - previous match

A good example for this would be the `BasicMovementTutorial`: https://github.com/onivim/oni/blob/master/browser/src/Services/Learning/Tutorial/Tutorials/BasicMovementTutorial.tsx

We'd just need to figure out the set of text that makes sense, and add the appropriate `Stages.MoveToGoalStage` to exercise those motions.

The tutorials are relatively straightforward to add, so this would be a fun and visible `first issue` if anyone is up for it 👍

**Comment by muream** [comment]
I'll give it a shot!

**Comment by keforbes** [comment]
This was merged in.
