### ISSUE TITLE
Opened folder does not update added and deleted files from outsite of Oni

### ISSUE THREAD

**Issue by RReivax** [onivim/oni#1987]
After opening a folder in the Oni explorer, if you add or delete some files in this folder outside of Oni, the Oni explorer is not updated. You currently have to reopen the folder, or restart Oni. This behavior also impacts file name changes: it leaves the non-existent file as an empty file and does not show the current file which name has been changed.

**Comment by CrossR** [comment]
Think this is covered over in #1506?

But yep, currently we've only got the basic implementation for the Explorer, though @Akin909 is working on a few improvements, including this issue I think.

**Comment by Akin909** [comment]
@RReivax @CrossR yep, been looking into getting a filesystem watcher hooked up in oni then linking that to the explorer currently just working through some outstanding PRs then will be having a look at that again

**Comment by CrossR** [comment]
I'll close this out since it should have been sorted with #2116.
