### ISSUE TITLE
GoLang language support example not working

### ISSUE THREAD

**Issue by ghost** [onivim/oni#2007]
1.- "language.go.languageServer.command": ["go-langserver"] doesn't work but
2.- "language.go.languageServer.command": "go-langserver" does.

Oni documentation has an example using the first one.

When I use the first option and reload oni, oni throws an error saying "endsWith function doesn't exist" and I can't open the oni config from oni anymore. I have to manually edit config.js and config.tsx and remove the line.

Also, "language.go.languageServer.rootFiles": [".git"] doesn't work when there is not a git repository.
Developer tools throws an error saying "unable to found root .csproj file"

[Here's a video showing both errors](https://streamable.com/1qh22)

**Comment by Akin909** [comment]
@LuciferDev thanks for raising this 👍

I added the example snippet at the end of #1929, which seemed to be the solution that fixed things for ppl in the thread but didn't manage to get any time to verify it in a `go` file thanks for catching that and pointing out the fix.

I've update the docs to show that.
Re. the rootFiles issue, the `unable to find root .csproj file` I believe that comes from an oni helper method that has that obscure error but what it tries to do is find a root file.

When you say it doesn't work other than the error do you still get `lsp` features?
my thinking there is if there is no root file identifiable then whatever is specified won't be found and oni looking for it will find nothing but if functionality remains then perhaps the preferable thing would not be to show that error but maybe rendering something else in the lsp status item

**Comment by badosu** [comment]
Well, it seems the issue owner was deleted, so we can't track if the issue was solved or expanded. As per #1928 and @Akin909's documentation we can close this one.
