### ISSUE TITLE
Question: how to add Textmate bundles?

### ISSUE THREAD

**Issue by bfulop** [onivim/oni#2030]
Hello,

I was trying to add a Textmate language grammar definition file for Twig to get syntax highlighting. Twig is templating language for HTML/PHP.

Here are the steps I went through:

1. Convert the language bundle from the [Textmate repo](https://github.com/textmate?language=&page=1&q=&type=&utf8=✓) as described in the [Atom docs](https://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/)
2. Convert CSON to JSON
3. Added this line to my `config.tsx`: 

```json
...
"ui.fontSize": "12px",
"language.twig.textMateGrammar": "[absolute path on my HD to]/twig/grammars/html (twig).json"
```

4. Restarted Oni as good mesure 😊

Is there anything I'm missing (the syntax highlighting still doesn't work...)? Once I get the correct workflow sorted out, I can reformat this question to serve as a reference for others.

**Comment by badosu** [comment]
@bfulop You can also try the vim syntax highlight if you have issues sorting this out (https://github.com/lumiliet/vim-twig).

In the future Oni will provide a mechanism to fetch vim plugins builtin, for the moment you can check the [Configuration](https://github.com/onivim/oni/wiki/Configuration) wiki page on how set your `init.vim` and use a plugin loader like [NeoBundle](https://github.com/Shougo/neobundle.vim).

**Comment by bfulop** [comment]
Thanks, I will try this method. Coming from Sublime with basically zero vim experience I was first looking for the familiar method... 😊

**Comment by bfulop** [comment]
Thanks @badosu, it worked great!

And installing was even easier: you just need to copy the plugin files (as described in the wiki – [installing a vim plugin](https://github.com/onivim/oni/wiki/Plugins#installing-a-vim-plugin)). The only difference is, that I think from v 0.3.2, the `.oni` location is no longer in `$HOME/.oni/plugins` as the Wiki says, but in `$HOME/.config/oni/plugins`, at least on the Mac.

**Comment by bfulop** [comment]
@badosu you were right to [suggest using the vim plugin](https://github.com/onivim/oni/issues/2030#issuecomment-378576537)–in general they contain more than just syntax highlighting but usually other extra features that helps vim understand that language e.g. folding, snippets. 

In the future I will always first start with the vim plugin.
