### ISSUE TITLE
font size won't change?

### ISSUE THREAD

**Issue by rjarow** [onivim/oni#2033]
![2018-04-04 15_03_52-config tsx _appdata_roaming_oni - oni](https://user-images.githubusercontent.com/5258620/38328680-83917684-3819-11e8-8937-d4beda2d9a50.png)
This is followup to my twitter post - https://twitter.com/oni_vim/status/981553549447331841

I am not able to change the font size

I followed the configurations page, and used the example and modified to my needs.

The following is my config.tsx in my %APPDATA%/oni on Windows 7

-----

export const activate = (oni: Oni.Plugin.Api) => {
   // Put your customizations here!
}

module.exports = {
	activate,
	// change configuration values here:
	"ui.fontSize": "16px",
	"editor.fontSize": "16px",
	"editor.completions.enabled": true
}

**Comment by bryphe** [comment]
Hi @rjarow , thanks for posting your config!

One thing to try might be switching the config to this:

```
export const activate = (oni) => {
// Put your customizations here!
}

export const configuration = {
// change configuration values here:
"ui.fontSize": "16px",
"editor.fontSize": "16px",
"editor.completions.enabled": true
}
```

Then try saving the config (`:w`).

I see two problems with the above config:
- The `Oni.Plugin.Api` typing is missing.
- TypeScript has a problem with the `module.exports` it seems.

If it still doesn't work, can you please check and see if there is a `config.js` generated in the %APPDATA%/oni? If so, can you share that? 

One more thing to try - you could try deleting both `config.tsx` and `config.js` from the %APPDATA%/oni folder, and then run `Configuration: Edit user config` from the command palette - that will re-generate it (and then modify the fontSize there).

Sorry that it's confusing with our configuration format change - let me know how those attempts go!

**Comment by rjarow** [comment]
I deleted, it regenerated and added my options to the bottom and that worked :)

Thanks so much!

**Comment by bryphe** [comment]
Awesome! Glad it finally worked @rjarow 👍
