### ISSUE TITLE
Autocomplete/Suggestions doesn't scroll

### ISSUE THREAD

**Issue by AUTplayed** [onivim/oni#2046]
Hi, if I write code like this: ![code](https://i.imgur.com/0FBRMks.png)

and scroll down the suggestions with the down arrow key, the suggestion window doesn't scroll down, but the highlighting disappears.

I am on windows 10 using v0.3.2

**Comment by AUTplayed** [comment]
bonus video: https://my.mixtape.moe/twlmzw.mp4

**Comment by Toxiapo** [comment]
Same for Mac running on 10.13.4 with the latest Oni version.

**Comment by badosu** [comment]
Duplicate of #1874
