### ISSUE TITLE
Tutorial - Infrastructure: Add 'real' game loop to tutorial

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#2050]
An issue was identified with #2045 that's really a bug in the tutorial infrastructure:

> Right now, we only `tick` on a very limited set of events - mode changed, cursor moved, and buffer changed. In the case of yanking, it doesn't fall into that narrow set of categories, and therefore we never tick - so the `WaitForRegisterState` never gets a chance to say its complete. If I move the cursor, it forces a tick, and then we hit the completion criteria.

> I think that as the tutorials get more involved, we'll need a 'real' game loop, like:
```
window.setInterval(() => {
   this._tick()
}, 250)
```

> (The alternative would be that we could keep hooking events... but that might get tricky!)

The only challenge there is we want to make sure to clear that interval when the tutorial is over or the buffer is closed.

This tracks setting up the 'game loop', as well as implementing proper clean / disposal logic. Ideally, we could get this class under unit test as well!

**Comment by keforbes** [comment]
Would it be possible to just run `tick` on every key press?  It should be safe to ignore any mouse events since using the mouse would go against the tutorial anyway. :smile:

**Comment by bryphe** [comment]
> Would it be possible to just run tick on every key press? It should be safe to ignore any mouse events since using the mouse would go against the tutorial anyway. 😄

Ah ya, I was thinking about that - I wasn't sure if there might be some race conditions (like if I press `yw` and query `getreg` immediately - will it be guaranteed to return? In that case it would - but perhaps there may be other cases where it wouldn't be true). So a dedicated 'game loop' would handle this in the general case.

> It should be safe to ignore any mouse events since using the mouse would go against the tutorial anyway. 😄

LOL, it's actually possible to win some of the tutorials with 0 keypresses using the mouse 😳 Interesting to compare times though... Need to think of a strategy for this - might be fun to have a big 'prohibited' logo show up over the tutorial surface if you move the mouse over it: https://fontawesome.com/icons/ban?style=solid
