### ISSUE TITLE
Common ground with deoplete?

### ISSUE THREAD

**Issue by xelra** [onivim/oni#206]
Would it be possible to have a common ground regarding syntax plugins with deoplete?

It would be great if the syntax plugins of deoplete were also to work with Oni. That way the wheel wouldn't have to be reinvented over and over.

Maybe even some kind of common framework can come from this?

**Comment by bert88sta** [comment]
Theoretically  as of now the pop-up menu from neovim will be in the oni
pop-up menu,  but it's quite slow.  We'll look into it :)

**Comment by extr0py** [comment]
:+1 Agree with @bert88sta - all the existing completion providers (deoplete, YCM, etc) should continue to be supported through our hook up with the external popupmenu UI. Any fix we make there will benefit all of these providers, so we should focus on improving the performance there and fixing any issues. Feel free to track specific issues you're having with that - having reproducible steps helps. Thanks for the feedback!

**Comment by xelra** [comment]
Just for reference, I'm also referencing the [Neovim LSP issue](https://github.com/neovim/neovim/issues/5522) here.

Maybe that would be the ideal way of communicating with a syntax backend. Not just for Oni's completion, but for any completion plugin there is.

The topic came up in a discussion with the main dev of Neovim on IRC about code completion, syntax highlighting, linting, refactoring and how there's just too much fragmentation around this.

**Comment by bryphe** [comment]
Similar discussion came up recently in #1000 - I'll close this out and we can track there.
