### ISSUE TITLE
tutorial screen become disorganized

### ISSUE THREAD

**Issue by pebble8888** [onivim/oni#2060]
macos 10.13.4
installed by `brew cask install oni`

<img width="1168" alt="2018-04-07 20 29 48" src="https://user-images.githubusercontent.com/1704383/38454449-a013ef5e-3aa2-11e8-87c7-c02cbeb28c23.png">

**Comment by bryphe** [comment]
Ah yes, thanks for raising this issue @pebble8888 !

We don't handle the tutorial screen well if the height is below a certain amount (you can repro this on all platforms by resizing the window).

We should implement a more 'responsive' layout - if the height is below a certain threshold, perhaps we can move the description over above the 'notes' column

**Comment by ShalokShalom** [comment]
Is this one by Electron?

**Comment by bryphe** [comment]
@ShalokShalom - actually no, it's our fault, we control the rendering / layout here - just not accounting for smaller heights. We should add some logic to detect if the screen size is under a certain threshold, and if so, move the description over.

**Comment by Akin909** [comment]
@bryphe would a media query work there?

```css
	@media (min-height:${smallDesktops}){
		flex-row: wrap;
	}
```
Making loads of assumptions about the layout, aka that its displaying flex etc.
might also be an interesting opportunity to try a css grid layout
