### ISSUE TITLE
ctrl+v doesn't work

### ISSUE THREAD

**Issue by SpaceWhite** [onivim/oni#2084]
### How to reproduce
1. open terminal
2. Paste copied text to terminal with ctrl+v

oni 0.32, linux mint

**Comment by TalAmuyal** [comment]
In Vim (and thus in Neovim and Oni), `Ctrl+v` is column-selection.
Pasting is done using `p` or `P`.
Do you have some special configs to change this behaviour?

BTW, I like setting `set clipboard+=unnamedplus` in my `init.vim` to make Vim use the clipboard.

**Comment by badosu** [comment]
Yes, the vim way should be:

Visual mode: `"+p` or `"*p`
Insert mode: `<C-r>+` or `<C-r>*`

**Comment by badosu** [comment]
Not sure if this is related to Oni though, seems like an issue using the normal clipboard.

If your terminal is `gnome-terminal` use `Ctrl-Shift-v` to paste from the clipboard.

Let us know if you find an issue with Oni and I'll reopen the issue.

**Comment by SpaceWhite** [comment]
@badosu Actually oni has paste from clipboard feature that can be triggered with `ctrl+v` key. Although this only works in editor mode, not in terminal mode and browser mode. It would be great if there is `ctrl+v` mode too in terminal and browser mode.

**Comment by SpaceWhite** [comment]
@CrossR I think `ctrl+v` key binding only works in vim insert mode. As @TalAmuyal mentioned `ctrl+v` in normal mode is column selection. But in browser and terminal, one can't use insert mode. Probably that's why the paste from clipboard didn't work.

**Comment by CrossR** [comment]
>But in browser and terminal, one can't use insert mode. Probably that's why the paste from clipboard didn't work.

Whoops, I somehow mentally corrected that to the command line, not the terminal.
Yep, I can reproduce this now.


The paste is gated with this check:
```
    const isInsertOrCommandMode = () =>
        editors.activeEditor.mode === "insert" || editors.activeEditor.mode === "cmdline_normal"
```

I guess the terminal isn't working since the mode never swaps to `insert` and its not the `cmdline`....That could be a bit more awkward to fix though.

Browser should be a bit easier at least, and I think is a bug? (Or more likely just wasn't added yet!)

**Comment by badosu** [comment]
Oh, I got it now. I never used the terminal functionality, sorry about that. I thought you were having issues pasting to a different application.

**Comment by scienceasdf** [comment]
You can append your init.vim with `runtime mswin.vim`, and you can copy/paste contents by ctrl+c/v
