### ISSUE TITLE
Does not read ~/.config/oni/config.js symlink

### ISSUE THREAD

**Issue by Nekroze** [onivim/oni#2087]
My dotfiles are all managed in a git repo and the real paths are symlinks into that repo.

When `~/.config/oni/config.js` is a symlink it appears to load the default config instead of the file the symlink is pointing too.

**Comment by josemarluedke** [comment]
I have been doing exactly that with the latest version of Oni and it works as expected. You can take a look in my symlink here: https://github.com/josemarluedke/dotfiles/blob/master/install.sh#L91

You might want to check if there is already a config file, if there is, remove it and then create the symlink.

**Comment by josemarluedke** [comment]
Also worth mentioning the recent changes of the configuration to TypeScript instead of JavaScript: https://github.com/onivim/oni/wiki/Migrating-Configuration-to-TypeScript

**Comment by Nekroze** [comment]
Hello,

Thanks for the welcome and swift responses.

I am using v0.3.2 however I was not aware of the typescript change. I just grabbed the minimal config from the [wiki](https://github.com/onivim/oni/wiki/How-To:-Minimal-Oni-Configuration) a couple of days ago and it said to place that in `~/.config/oni/config.js` perhaps [nix-home](https://github.com/sheenobu/nix-home) does something other than a simple simlink like you are doing. I will close this issue and migrate to typescript and only re-open if I get more information on the problem should it persist.

Much appreciated!

**Comment by parkerault** [comment]
Whoops, that's left over from before the config file was switched to tsx. I updated the wiki so nobody else will be led astray. 😄
