### ISSUE TITLE
Ctral+A doesn't work

### ISSUE THREAD

**Issue by scienceasdf** [onivim/oni#2092]
I configure the vim file so that it can behave mswin-like. Copy, paste and cut seem to work. But <C-A> is not working for selecting all. The relevant configuration is below:
```
noremap <C-A> gggH<C-O>G  
inoremap <C-A> <C-O>gg<C-O>gH<C-O>G  
cnoremap <C-A> <C-C>gggH<C-O>G  
onoremap <C-A> <C-C>gggH<C-O>G  
snoremap <C-A> <C-C>gggH<C-O>G  
xnoremap <C-A> <C-C>ggVG  
   
```

**Comment by TalAmuyal** [comment]
Just tried `nnoremap <c-a> ggVG` and it worked.
Oni: v0.3.2
OS: Ubuntu 17.10

Can you try a simpler binding, just to verify that <C-A> is executed?

**Comment by scienceasdf** [comment]
Ok, solved it. Append the init.vim with `runtime mswin.vim`

**Comment by badosu** [comment]
Is this config something necessary to keep compatibilitu with windows?

If that's the case we should add it to the installation instructions or to the default `init.vim` with a check for windows.

**Comment by CrossR** [comment]
>Is this config something necessary to keep compatibility with windows?

It doesn't seem to be:

https://github.com/neovim/neovim/blob/6e9f329d051cf6bf6d83dbe5335f86a1752ec45a/runtime/mswin.vim

Looks like a lot of default options to make N/vim closer to other Windows apps.
I've been using Oni fine for however long on Windows and haven't noticed anything wrong, but I did learn Vim on Linux.

That said, it seem very opinionated, so I wouldn't think we'd want it enabled by default.
Ie rebinding `Ctrl-v` to me would break my muscle memory for visual block mode etc. I think its a personal thing if you want vim to behave more like other Windows apps and so on.
