### ISSUE TITLE
ReasonML doesn't seem to integrate with vim quickfix

### ISSUE THREAD

**Issue by dvisztempacct** [onivim/oni#2097]
Oni's out-of-the-box integration with `ocaml-language-server` is nice! Thanks!

But it doesn't seem to integrate with vim's `quickfix` feature.

Any chance I'm mistaken or this is something I can enable?

I'm using Oni 0.3.2 for Mac OS X download from website.

I've seen other mentions of `quickfix` support in Oni, so I figure it must be there in some form.

If that integration is done directly with the language client, then I'd think if any other language supported by language client has this behavior in Oni, then my language would have it, too.

Any ideas would be appreciated :)

I'm looking under the hood now to see if I can find out what's going on, but I am new to Oni...

**Comment by Akin909** [comment]
@dvisztempacct when you say `quickfix` feature can I clarify what you mean?

Do you mean diagnostic output to the quickfix list? In which case that's not a feature that's been implemented yet(at least I think it hasn't), I personally would be keen to look into better qf integration once neovim externalises it, but as of right now the way in which the qf is used is for outpitting `findReferences` functionality or global search etc. (is that what isn't working?)

**Comment by dvisztempacct** [comment]
> Do you mean diagnostic output to the quickfix list?
Yes.

> right now the way in which the qf is used is for outpitting findReferences functionality or global search etc. (is that what isn't working?)

> I personally would be keen to look into better qf integration once neovim externalises it

What do you mean by "externalize?" :)

I assume this works but haven't tried it.

**Comment by dvisztempacct** [comment]
Ahh.. I ought to have guessed this is what you meant!

Is there a branch or a fork where this is being worked on?

Maybe some docs somewhere for someone who wants to help get this moving?

Thanks!

**Comment by TalAmuyal** [comment]
If you are talking about helping with externalizing UI part, then the first stage is supporting it on Neovim's side.
An issue that might be relevant is [this](https://github.com/neovim/neovim/pull/5686).

Aside from that, I'm closing this issue since it seems to have no definite goal.
@dvisztempacct, if I'm mistaken, please re-open this issue, or create a new one.

Cheers :)
