### ISSUE TITLE
fails to launch with Nvim 0.3 

### ISSUE THREAD

**Issue by justinmk** [onivim/oni#2102]
Oni fails to start Nvim 0.3 (HEAD). The version check here expects `patch >= 1`:

https://github.com/onivim/oni/blob/18f8546d88025718cf893f9f1b23fa16b067ce04/browser/src/neovim/NeovimInstance.ts#L1016

probably it should be something like:

    if (major > 0 || minor > 2 || (minor == 2 && patch >= 1)) {

**Comment by bryphe** [comment]
Thanks @justinmk for testing with `0.3.0` and logging the issue! Ya, that version check is busted - your proposed fix looks better.

I tested with `0.3.0` on Windows, and things are looking good.

**Comment by bryphe** [comment]
This should be addressed now with #2103 (and I'm running `nvim` 0.3.0 locally now 😎 ). Let me know if that's not the case and I'll re-open. Thanks @justinmk !
