### ISSUE TITLE
Hitting the c key is laggy (1 second) with init.vim

### ISSUE THREAD

**Issue by phaazon** [onivim/oni#2119]
I don’t really get what’s happening here. All the other keys work correctly, but this one is getting real lag. My `init.vim` doesn’t do anything special (it maps `c` to `move left`).

**Comment by parkerault** [comment]
Do you have another key mapping in your init.vim that uses `c` + some other character? Something like `nnoremap cc <esc>` will make vim pause for 1 second while it waits for you to press the second character.

**Comment by phaazon** [comment]
I’m having a look, but my conf for nvim is [here](https://github.com/phaazon/config/blob/master/archlinux/.config/nvim/init.vim) and [here](https://github.com/phaazon/config/blob/master/archlinux/.config/nvim/nvimrc.bepo).

**Comment by phaazon** [comment]
Is there a similar feature as in `atom` that shows every commands / functions triggered by a key when hitting it?

**Comment by parkerault** [comment]
So just to be sure, you are not getting the 1 second lag when you use nvim in the terminal?

**Comment by phaazon** [comment]
Seems to be fixed if I set the `defaultConfig` to `false`. And no, it’s in `Oni` that it’s logging.

**Comment by phaazon** [comment]
Well, not really, since now I have the `nvim` UI inside `Oni`. Dammit! :dancer:

**Comment by parkerault** [comment]
This wiki page has some instructions on how to make oni behave more like vanilla vim: https://github.com/onivim/oni/wiki/How-To:-Minimal-Oni-Configuration

If you set `defaultConfig` to false, you'll want to also include something like 
```
if exists('g:gui_oni')
  
  set nocompatible              " be iMproved, required
  filetype off                  " required

  set number
  set noswapfile
  set smartcase

  " Turn off statusbar, because it is externalized
  set noshowmode
  set noruler
  set laststatus=0
  set noshowcmd

  " Enable GUI mouse behavior
  set mouse=a
endif
```
... in your init.vim

**Comment by phaazon** [comment]
Thanks, I’ll try it!

**Comment by phaazon** [comment]
Ok, it’s definitely better, thanks! Final, not related issue: is there a way to remove the left-most panel? I use the `"sidebar.toggle"` command but it doesn’t remove the left-most panel, only the `Explorer`.

**Comment by phaazon** [comment]
It still keeps showing up. (the big one with icons)

**Comment by CrossR** [comment]
You'll need to reload Oni I think for that to take hold, but now that I've tried it out, there is a few bugs with it (that are being fixed over in #1564 and logged in #1562).

However, this is what it looks like once you've set it: 

![image](https://user-images.githubusercontent.com/10038688/39010916-eeca3306-4407-11e8-904b-1e1d9feed997.png)

**Comment by phaazon** [comment]
Yay, it worked after reloading! Thanks! :heart:

**Comment by badosu** [comment]
@phaazon Can you tell if hitting c is lagging in normal neovim?

**Comment by phaazon** [comment]
It’s not.

**Comment by phaazon** [comment]
I did the `:map c`, there’s only `* h`…

**Comment by CrossR** [comment]
Now that I think about it....this is probably due to https://github.com/tpope/vim-surround, which is loaded as part of the default config.

It contains a binding for `cs` which could be causing the delay @parkerault is talking about. This seems to be the case if disabling the default config fixes it, since that would stop loading the plugin. If we wanted to be certain, if you post the mapping you are using we could do some tests with that plugin installed for terminal vim etc.

**Comment by bryphe** [comment]
Good catch, @CrossR - that seems like a likely culprit!

**Comment by phaazon** [comment]
Oh yeah, it’s very likely!

**Comment by badosu** [comment]
Well, unless we are going to track the lagging issue that seems specific to Oni we can close this.

**Comment by phaazon** [comment]
Sure, thanks again!
