### ISSUE TITLE
Difficulty getting certain plugins to work

### ISSUE THREAD

**Issue by markhagemann** [onivim/oni#2125]
Having followed the guide at https://github.com/onivim/oni/wiki/Plugins where the example for vim-solarized8 worked, I then tried to install a few other themes such as hydrangea-vim and vim-theme-papaya. When trying to set the colorscheme it would return an error saying that it could not be found. 

I also tried to install vim-ss (SilverStripe support) and vim-vue the same way without success. 

What I found was the only way I could get it to work was copying these folders into the core folder of Oni which obviously isn't ideal. I assume I'm just missing a step somewhere. 

Thanks!

**Comment by CrossR** [comment]
Thats odd... I'd expect that cloning the projects into those folders would work fine.

Just to check, the process is :
* Open `~/.config/oni/plugins` on Linux/Mac or `%APPDATA%/oni/plugins`
* Close or unzip the plugin into this folder.
* Close Oni fully and restart it.

If that doesn't work...I'd be interested what the Dev Tools says for `Oni.plugins.getAllRuntimePaths()`. (That is Help > Developer Tools > Swap to Console.

I'd expect something like this: 

![image](https://user-images.githubusercontent.com/10038688/39075537-29718e6e-44ee-11e8-8b19-46f8144b19ee.png)

Which has an awful lot in it...but the important bit is the last 4 lines, where you can see `hydrangea-vim` and `vim-solarized8`.

As a separate note, if you happen to already use neovim you can load your `init.vim` and use a normal vim plugin manager. That is done with `    "oni.loadInitVim": true,` and it will load from `~/.config/nvim/init.vim` or `%LOCALAPPDATA%/nvim/init.vim`.

**Comment by markhagemann** [comment]
Well that's embarassing.. I didn't see the light gray text for windows users to put it in %APPDATA%. Classic after midnight configuring. 

This has been resolved. Thanks a lot for the help :)

**Comment by bryphe** [comment]
Glad you got it worked, @markhagemann ! And thanks @CrossR for the help! 💯 I'll close this out-
