### ISSUE TITLE
Auto-closing pairs does not work well with macros

### ISSUE THREAD

**Issue by powermosfet** [onivim/oni#2131]
If you record a macro that triggers auto-closing, the macro does not "play" correctly.

Minimal example:

record the macro to insert `f(x)`: `qqif(x<ESC>q`

The text you just entered displays as `f(x)`, but playing the macro will insert `f()x`

**Comment by CrossR** [comment]
I think this is covered by #1200, so it might be worth adding something on that?

**Comment by powermosfet** [comment]
That's right - I tried searching for this before creating an issue, but i missed that. Will close this issue then, since #1200 was exactly the same
