### ISSUE TITLE
Oni exits without prompting to save

### ISSUE THREAD

**Issue by ArthurZ** [onivim/oni#2137]
Please allow salvaging unsaved data - presently Oni exits disregarding whether a file is persisted to disk/saved.
Prevent valuable data and thus work lost by prompting to save a file.

Thank you!

**Comment by TalAmuyal** [comment]
Hi, thanks for logging this issue and trying out Oni!

Could you please list the steps for reproduction?

**Comment by keforbes** [comment]
Yeah, this was filed as #264.  I agree, it does need to be fixed.  Personally, I think this is one of those things that prevents Oni from being a daily use text editor since if you accidentally close an edited file there's nothing you can do.

**Comment by badosu** [comment]
@keforbes I think we can close this one, right?

**Comment by TalAmuyal** [comment]
I think so too - closing since #264 tracks this.
Just for the record, `:q<CR>` does warn you.

**Comment by badosu** [comment]
@TalAmuyal Indeed, I tried on another machine and this behaviour is preserved, I'll investigate what's the difference, thanks!
