### ISSUE TITLE
No linux tar.gz release for 0.3.3

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2144]
No linux release was created for the 0.3.3 version.

Is it 0.3.3 or 0.3.3-1?

**Comment by CrossR** [comment]
I think currently its in pre-release, which would explain the missing Linux and Win 64 binaries.

**Comment by badosu** [comment]
Ok, released with the tag `v0.3.3-1` on AUR. Will revert it when the release tags are stable again.
