### ISSUE TITLE
closed splits eating window space

### ISSUE THREAD

**Issue by mellotanica** [onivim/oni#2147]
I noticed that when you combine vertical and horizontal splits, after closing some of them, the space occupied by the last closed split remains unusable:

![oni_split](https://user-images.githubusercontent.com/3792661/39397227-f4f686d0-4afb-11e8-9e2e-92d798b86eea.gif)

in the demonstration I used default config with `"editor.split.mode": "oni"` as the only override and the sequence executed was:
```
<c-w><c-v>
<c-w><c-s>
<c-w><c-q>
<c-w><c-q>
```

**Comment by bryphe** [comment]
Ah ya, this looks familiar 😄 Thanks for logging the issue, @mellotanica .

 Actually had a workaround in the demo branch - you'll notice the website demo doesn't have this issue!

I'm factoring out the change in #2159
