### ISSUE TITLE
No display on Ubuntu 18.04 in Virtualbox

### ISSUE THREAD

**Issue by kevingill1966** [onivim/oni#2150]
Hi,
I installed version 0.3.2 into my new Ubuntu 18.04 instance. I am running in a virtualbox.
I started oni.
It runs at 100% CPU for about 30 seconds.
It displays an icon in the launcher. 
It never draws/shows a main window.
It creates .config/oni folder.
I installed libcanberra-gtk-module the first time I ran it as it gave an error.
nvim runs OK.

**Comment by parkerault** [comment]
I had a similar issue, maybe the comments here will help resolve it: https://github.com/onivim/oni/issues/2101

**Comment by kevingill1966** [comment]
@parkerault  - thanks for the suggestion - I tried it but it had no impact on the problem.

@MarcusE1W - thanks for the suggestion - I have 4gigs real memory and 8 gigs swap in the VM.

**Comment by kevingill1966** [comment]
It may be relevant. I have vscode working fine in the VM.

**Comment by TalAmuyal** [comment]
Just tried Ubuntu 18.04 (minimal installation) with latest Neovim (0.3.0?) and latest Oni (0.3.3) and it worked fine (after installing the missing packages).
For what it worth, it is the latest VirtualBox on Windows 10.

**Comment by kevingill1966** [comment]
This is very embarrassing. Oni started fine to day. I am guessing that it was drawing its window on virtual display/screen that I was not seeing and now it is displaying on the main screen. 

Sorry  to waste peoples time and thanks to everyone who helped.
