### ISSUE TITLE
[Feature Request] Ability to focus on open/close File Explorer with key bindings

### ISSUE THREAD

**Issue by josemarluedke** [onivim/oni#2151]
Although we have the key bindings to toggle the sidebar, I would love to have a shortcut that would open the file explore and focus on it so I can use `j`,`k` navigation. The same shortcut should close the sidebar and focus on the editor. 

Today it is possible by using `ctrl + w + h`, but that is not specific to the File Explorer and also it does not work well when you have the sidebar closed, as it will focus in the sidebar navigation (explorer icon, search icon, etc.) instead of the Explorer. 

My desired workflow is: 

Have the explorer closed, hit a shortcut (today I have `leader + m`) to open the file explorer and focus on it. Choose a file to open, then close the explorer with the same key shortcut and have the focus in the editor.

**Comment by parkerault** [comment]
Maybe <c-s-e> would be a good shortcut.

**Comment by tw1t611** [comment]
Hi, I would appreciate this feature too.
Furthermore, what do you think of focus the file, you are actually working on to focus by default?
You could than easily move ```j, k``` to files in the same directory.
This is what vscode does with <C-0>

**Comment by CrossR** [comment]
Hey @tw1t611 I've added this feature now in an open PR, but I can look at adding a "Focus current File" option as well, since I think its been requested elsewhere.
