### ISSUE TITLE
Markdown toggle only after activating preview window

### ISSUE THREAD

**Issue by MarcusE1W** [onivim/oni#2152]
Hi.

I have turned on the experimental markdown preview and added key F8 to toggle the preview on and of as described in the Wiki Config.

Now just pressing F8 (or use command palette toggle) in the .md file does not work.
What works is to mark the preview window and then the .md window with the mouse.
Then F8 (or the command palette) works.

Is this an error in my setup or is this an Issue?

Linux: Archlinux
WM: SpectrWM
Oni: 0.3.3

**Comment by TalAmuyal** [comment]
Confirmed.
Seems that it is an issue that is new in v0.3.3.
When the preview's split is opened, it gets the focus.
Seems that while it has the focus on it, it ignores the binding.

Will take a look at it.
In the meantime, if anyone has an idea how to auto-remove the focus from it I'd be happy to hear about it ;)

**Comment by CrossR** [comment]
Looks like this is fixed for me.

I'll assume that #2282 fixed it since I changed the focusing on the markdown preview as well as making the toggle code a bit more robust.
