### ISSUE TITLE
FileExplorer: <C-w><l> does not change focused window

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2156]
When focused on the FileExplorer, the window navigation shortcuts do not work, they are being overriden by the new folder navigation ones or did not work previously as well.

**Comment by Akin909** [comment]
@badosu I've just tried using `<c-w>h` and `<c-w>l` locally with the new folder navigation commands and both seem to work to navigate around windows and within windows?, any chance the bindings have otherwise been overwritten or are conflicting with some vim ones?

**Comment by badosu** [comment]
@Akin909 It seems that typing the three strokes together works fine `<C-w-l>` but not separately as I am used to in vim `<C-w>l`.

**Comment by Akin909** [comment]
@badosu the new commands in the explorer basically use oni's keybinding api rather than vim's so I think because of the delay in the input it's reading the `l` and `h` bindings we have for collapse and expand, depending on how many user's hit this it might be worth rebinding these although I think @bryphe intended changes for oni bindings will eventually include something like a `ttimeoutlen` so we might eventually get this kind of behaviour here

**Comment by badosu** [comment]
@Akin909 Great, thanks for the heads up!

**Comment by abs-zero** [comment]
I have this issue too. It works on split panes correctly as the vim. But it does not in file explorer

**Comment by badosu** [comment]
@abs-zero You can try keeping the Ctrl key pressed, this way it works. I forgot about this and instinctively felt navigation still did not work on File Explorer though, muscle memory is hard.

**Comment by abs-zero** [comment]
oh thanks! I did not understand from above conversation.

**Comment by abs-zero** [comment]
This poses a small problem however. My bindings `map <C-j> <C-w>j` does not work in filetree.

**Comment by badosu** [comment]
You can change `<C-w>j` to `<C-w><C-j>` or perhaps `<C-w-j>`

**Comment by abs-zero** [comment]
Tried both. Didn't work.

**Comment by CrossR** [comment]
This works for me as an Oni keybind: 

```
    // Move about splits easier.
    oni.input.bind("<c-h>", () =>
        oni.editors.activeEditor.neovim.command(`call OniNextWindow('h')<CR>`)
    )
    oni.input.bind("<c-j>", () =>
        oni.editors.activeEditor.neovim.command(`call OniNextWindow('j')<CR>`)
    )
    oni.input.bind("<c-k>", () =>
        oni.editors.activeEditor.neovim.command(`call OniNextWindow('k')<CR>`)
    )
    oni.input.bind("<c-l>", () =>
        oni.editors.activeEditor.neovim.command(`call OniNextWindow('l')<CR>`)
    )
```

**Comment by abs-zero** [comment]
@CrossR Thanks! It worked. May I ask where I can get full reference for bindings in oni like `OniNextWindow('k')<CR>`?

**Comment by badosu** [comment]
@Akin909 I am not sure we'll ever be able to emulate vim's behaviour here, you can close this one unless this is a desirable goal.

**Comment by badosu** [comment]
I am closing this, unless the input model changes to replicate better vim's sequential keybindings this is not feasible.

**Comment by badosu** [comment]
@abs-zero See: https://github.com/onivim/oni/wiki/API-Examples

There are some examples there, but unfortunately no integrated documentation on the available Oni commands.
