### ISSUE TITLE
Prettier plugin statusline item highlighted weirdly

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2157]
Using the [neodark](https://github.com/KeitaNakamura/neodark.vim) theme with dark background.

![screenshot from 2018-04-30 20-56-22](https://user-images.githubusercontent.com/347552/39455852-24477534-4cb9-11e8-916a-5f132d0974ed.png)

It used to work without problems before 0.3.3

**Comment by josemarluedke** [comment]
I'm having the same but with a different theme (`base16-nord`).

**Comment by Akin909** [comment]
@badosu the prettier status item derives its color from the `"highlight.mode.normal.background"` which is set in the `theme.json` but if the theme being used isn't an `oni` theme then it uses a color that oni derives, not entirely sure how tbh (@brype?) but the color you get I believe is a result of that. it's a tricky issue to solve for none oni themes as the highlight color I believe should fallback to something that is somehow derived from the user's colorscheme.

**Comment by parkerault** [comment]
I think a good workaround would be to use the same derived theme colors that the language server status tab uses, at least that way it would be consistent.

**Comment by badosu** [comment]
@parkerault @Akin909 I was taking a look at using `Oni.colors.getColor("highlight.mode.normal.background")` to set the background color but this does not seem like a good choice, it's a light blue similar to the mode indicator, see:

![screenshot from 2018-05-27 18-02-34](https://user-images.githubusercontent.com/347552/40590626-2a6d7a1a-61d8-11e8-9bbe-25bff5a87e01.png)

The color being used by statusbar items is hardcoded as `rgb(35, 35, 35)`, at least for the language client ones, [see here](https://github.com/onivim/oni/blob/master/browser/src/Services/Language/LanguageClientStatusBar.tsx#L87).

We have some options:

- Remove the hardcoded setting and define a new theme color or use some other that I could not find that is reused by all statusbar items
- Hardcode `rgb(35, 35, 35)` for the prettier plugin to keep consistency
- Use `"highlight.mode.normal.background"`

**Comment by Akin909** [comment]
@badosu I think the first option is the best of the three as you point out the normal mode color is a bit distracting in multiple places as I believe it tends to be a brighter color.

I think if we defined a color for status items then future status items could use it, problem with that though is that *all* the color schemes will need to have a color chosen for them which would make that bit of work a bit frustrating as it'd involve picking colors for 5+ colorschemes.

Another alternative which isn't up there is, doing the same thing we have for the git plugin atm which is no color i.e. just removing the background color. Precedent wise vscode (not that we should feel obliged to copy them) don't seem to color their status bar items at all and tbh in this case its the most minimal solution and I don't think many people will notice a difference

**Comment by badosu** [comment]
@Bergiu If this is fixed for you on master then yes.

**Comment by Bergiu** [comment]
Its fixed for me on 0.3.7-beta3.

**Comment by badosu** [comment]
Thanks for testing!
