### ISSUE TITLE
Oni runs only as root on archlinux

### ISSUE THREAD

**Issue by daxid** [onivim/oni#2158]
Hi,
`oni --debug` reports the following error (with AUR package on Archlinux):

```
Uncaught (in promise) Error: watch /home/daxid/.config/oni ENOSPC
    at exports._errnoException (util.js:1024)
    at FSWatcher.start (fs.js:1394)
    at Object.fs.watch (fs.js:1420)
    at new _ (vendor.bundle.js:1)
    at O.addConfigurationFile (vendor.bundle.js:1)
    at O.start (vendor.bundle.js:1)
    at bundle.js:1
    at Generator.next (<anonymous>)
    at s (bundle.js:1)
    at <anonymous>
```

Runing it as root works fine...
Any hint ?
Best regards
++
David

**Comment by badosu** [comment]
Hello @daxid, what is the output of `ls ~/.config/oni`?

Seems like there is some issue with the file watcher, it can be a bug, limit of open file descriptors or disk size.

**Comment by Akin909** [comment]
@daxid @bryphe has recently added a config option to prevent the FSWatcher from being on by default till we work out all the kinks, but I believe the issue you're having is that you config is located in directory where the oni process does not have permission but it is attempting to watch the directory.

Re. solutions the filesystem watcher can take a configuration option (on the development side) to have it [`ignorePermissionErrors`](https://github.com/paulmillr/chokidar) which we can set so it fails silently if it attempts to read a directory it doesn't have permissions for

**Comment by badosu** [comment]
@Akin909 Perhaps some autogenerated electron files have permission issues and @daxid's current dir is `.config/oni`?

**Comment by daxid** [comment]
Thanks for your kind answers !
@badosu :

```
$ ls -al ~/.config/oni
total 20
drwx------  3 daxid users 4096  2 mai   16:44 .
drwxr-xr-x 64 daxid users 4096  2 mai   16:44 ..
drwx------  2 daxid users 4096  2 mai   16:44 GPUCache
-rw-------  1 daxid users   69  2 mai   16:44 Preferences
-rw-r--r--  1 daxid users  106  2 mai   16:44 Settings
```
I supposed a permission pb so I did suppress this config folder so it is created anew wen relaunching Oni, but no success...
I also compared with a working instance on another machine, it seems ok to me !
++

**Comment by badosu** [comment]
Well, there's no `config.{j,t}s` there.

If you run `echo "module.exports = {}" > .config/oni/config.js` and run Oni as your user, does it work?

**Comment by daxid** [comment]
Nope, still same symptoms with config.js present (detail of the permissions beneath).

```
$ ls -al ~/.config/oni
total 28
drwx------  4 daxid users 4096  3 mai   15:08  .
drwxr-xr-x 64 daxid users 4096  2 mai   16:44  ..
-rw-r--r--  1 daxid users   20  3 mai   15:08  config.js
drwx------  2 daxid users 4096  2 mai   16:44  GPUCache
drwx------  2 daxid users 4096  3 mai   15:08 'Local Storage'
-rw-------  1 daxid users  429  3 mai   15:08  Preferences
-rw-r--r--  1 daxid users  105  3 mai   15:08  Settings
```

**Comment by badosu** [comment]
This is weird, permissions seem fine, except for group permissions but should not be an issue if processes are spawned with `daxid` user. Does not seem an issue with the presence of `config.js` as well.

**Comment by dkns** [comment]
FYI: I had similar issue (on ubuntu 16.04) when trying to run developmen build i.e. `yarn run start` and running command from linked issue `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` 'fixed' it for me.

**Comment by daxid** [comment]
Ho, sorry for late feedback, I was away for a while.
The proposed command indeed worked ! Thanks a lot @badosu  !

I think I had other inotify related issues on my system (Nautilus file manager not updating folder content and stuff).
Well, I'm so happy right now, I finally get to give Oni a shot !

**Comment by badosu** [comment]
So, the issue here is with the inotify config, the workaround is to increase the file limit as per @dkns's comment.

We'll close this one, reopen if you think there's something we can do on Oni's side.
