### ISSUE TITLE
Errors with python language server

### ISSUE THREAD

**Issue by Bretley** [onivim/oni#2180]
On OSX, using the prebuilt binary:

<img width="598" alt="screen shot 2018-05-07 at 11 36 57 am" src="https://user-images.githubusercontent.com/8421641/39710522-0af098fe-51eb-11e8-99de-f0e1ca78bb97.png">

Is this maybe a dependency problem, or something that I could have messed up outside of oni?

**Comment by CrossR** [comment]
I've been using it a bit on my machine, and confirm it does work, but does need manually installing.

There is a seperate issue I've raised already about checking the existence of the LS before attempting to load it (#1531).

**Comment by Bretley** [comment]
as per @CrossR I'm going to close this out, no need to clutter the issue list if there's another one that addresses checking/alerting instead of failing indefinitely.
