### ISSUE TITLE
Multiple windows of same buffer shares scrolling position

### ISSUE THREAD

**Issue by cjohansson** [onivim/oni#2185]
If you start Vi/Vim/Neovim and open a buffer and then split the window `C-w` `v` or `C-w` `s` then both windows have separate scrolling positions, you can for instance have the top of a large file in one window and the bottom part in the other. But in Neovim if you scroll one of the windows, the other is scrolled as well. Is this intentional behaviour?

**Comment by Bretley** [comment]
@cjohansson Probably not. I've noticed this behavior too.

**Easy Repro:**
choose "edit user config" in the command pallate.
From there, scroll in the window that has the cursor in it.

Probably worth mentioning that I have vim-style tabs enabled.
If this doesn't reproduce it, I will post a minimal vimrc and oni configuration file.

Thanks for the bug report!

**Comment by Akin909** [comment]
@Bretley the behaviour in the user config with the reference buffer is intentional it uses vim's `scrollbind` functionality I added that and discussed having it be configurable as I wasn't sure if it was desirable or not, re @cjohansson issue not sure I understand what is happening is it that oni buffers exhibit unexpected scrollbind functionality or that it is present and undesirable?

**Comment by cjohansson** [comment]
@Akin909 you were right, I can't reproduce the behaviour in a normal buffer, only in the user config file, closing this. My `init.vim` was not causing this issue

**Comment by city41** [comment]
I am having a similar issue. I just installed Oni 0.3.4.

repro:
1. open a file
2. ^W ^S to open a split
3. in the second split open a different file, so each split has a different buffer
4. scroll in one split using j and k. Once that split starts scrolling, so does the other split.

When I launch neovim in a terminal and do the same repro, I don't have this problem.

**Comment by oroulet** [comment]
I also got this behaviour with oni.  I had to set manually noscrollbind. Somewhere oni is messing with that setting....

**Comment by cjohansson** [comment]
Opening this issue again since people seems to experience it, if I remember correctly I experienced this behaviour in a normal buffer but last time I tried to reproduce with latest Oni I wasn't able to. Tried again now with latest Oni and I can't reproduce. Tried different files in different windows and didn't get the issue there either.

**Comment by Akin909** [comment]
A good and permanent solution to this I think on the off chance that the scroll bind feature is persisting would be to remove it from the buffer reference file, which is the only place where the command is invoked in the oni repo, with it removed there should be no further scrollbind quirks I think

**Comment by oroulet** [comment]
@Akin909 I was trying oni today for the first time and the scrollbind there was surprising/disturbing so I guess not having it would only help...

**Comment by parkerault** [comment]
I will also vote to remove scrollbind from user settings, as the user config.tsx has no structural relation to the reference buffer. All it does is make it impossible to look at the reference entries when you are editing the config split.
