### ISSUE TITLE
WebGL Renderer Issues

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#2220]
Oni Version: ecc6c4a5482f691633fee04fbd1562de12f5652f
Neovim Version (Linux only): n/a
Operating System: Windows 10 Pro

#### Describe your issue

Upon launching Oni with the `webgl` rendering strategy, I get 10+ errors of the following error,
as well as no text rendered on screen except the char under the cursor.

![image](https://user-images.githubusercontent.com/10038688/40234044-207d7704-5a9d-11e8-8b90-e83dd755f83e.png)

#### Expected behaviour

Text to be shown correctly.

#### Steps to reproduce

Simply launching Oni with `"editor.renderer": "webgl",` seems to cause the issue.

I've attempted to run a debug build but when I do that I get a different error which is entirely unrelated, but makes me running a debug build for some more info much harder.

![image](https://user-images.githubusercontent.com/10038688/40234232-f5f64898-5a9d-11e8-8f09-8524d5fa4c74.png)

**Comment by Cryza** [comment]
Thanks for testing this so quickly!

For documentational reasons, I would like to add that a non-integer `devicePixelRatio` is also required to reproduce the issue. This can be achieved e.g. by setting the DPI scaling to 150% in the windows control panel. I don't know a way of doing this on Mac OS unfortunately. Maybe setting a view zoom in electron could produce the same result, but I don't know how to set this without the chrome UI.

In any case, I opened a PR which should fix the issue. It would be great if you found the time to test it again, @CrossR 

Cheers!
