### ISSUE TITLE
OSX: Homebrew distributed version does not load config

### ISSUE THREAD

**Issue by deepflame** [onivim/oni#2222]
Oni Version: 0.3.4
Operating System: Mac OSX 10.13.4

#### Describe your issue

Seems that the homebrew distributed version does not load the config from `~/.config/oni`

#### Steps to reproduce

Install homebrew version and change the config (e.g. change theme).

**Comment by CrossR** [comment]
That is odd, I don't think the homebrew version should have any form of different config.

One thing to check is when you change the `config.tsx`, does the `config.js` update as well? That is, on saving your `config.tsx`, it is compiled into a `.js` file in `~/.config/oni/config.js`. If that file is never made/updated, then your config wouldn't be being saved, so can't be loaded.

A quick sanity check could also be just making a bare `config.js` at `~/.config/oni/config.js` with the following default config in : https://github.com/onivim/oni/blob/master/configuration/config.default.js, but change the theme outlined in that to something else ie `"gruvbox_dark"`. If its loading that, then it may instead be an issue in the compiling of your `config.tsx` to Javascript.

**Comment by deepflame** [comment]
@CrossR thanks a lot for your inputs.

I am actually not sure what happened. When I try to use the Homebrew distributed version now it is working as expected. Maybe just a hickup on first install?

Anyways, thanks. I will close the ticket now.
