### ISSUE TITLE
Autocomplete case insensitivity in command bar (:e, :tabe etc)

### ISSUE THREAD

**Issue by hboon** [onivim/oni#2241]
Oni Version: 0.3.4 (also tested and reproducible with 0.3.2)
Operating System: macOS 10.13.4

#### Describe your issue

Enter a command:

1. `:e ~/desk`
2. Hit tab

#### Expected behaviour

Command becomes `:e ~/Desktop/`

#### Actual behaviour

No completion/suggestion because of case sensitivity.

Not sure if this is more on neovim's side (maybe related to https://github.com/neovim/neovim/issues/8211). But it works as expected with MacVim.

**Comment by badosu** [comment]
In vim's side `:set wildignorecase`, does it work for you?

**Comment by badosu** [comment]
As far as I can see there is no way that Oni should override the behaviour of wildmenu, unless a configuration option is provided that would have the same effect as adding the aforementioned line in `init.vim`.

**Comment by hboon** [comment]
`:set wildignorecase` in `init.vim` works indeed. Thanks

Hmm.. strange. I was looking through my `.vimrc` (for MacVim) line by line and didn't see, and didn't know about `wildignorecase`. And I just check it's off on MacVim, yet completion was case-insensitive. But I guess that's off-topic.

Sorry for the noise.
