### ISSUE TITLE
Snippets don't auto indent

### ISSUE THREAD

**Issue by Goldie643** [onivim/oni#2242]
Inserting a snippet on anything but col 1 doesn't preserve indentation beyond first line.
Example:
Snippet code:
![image](https://user-images.githubusercontent.com/15697667/40439175-17260b26-5eb2-11e8-81ab-f755a28716ab.png)

From col 1:
![image](https://user-images.githubusercontent.com/15697667/40439199-2468ea56-5eb2-11e8-93e6-c48a051b1e5c.png)

From col 5:
![image](https://user-images.githubusercontent.com/15697667/40439239-379b42ea-5eb2-11e8-9348-bf180ec92613.png)

**Comment by CrossR** [comment]
I can confirm from a quick test in VSCode that it should be auto-indenting the subsequent lines.

The code looks to take the first lines character position into consideration, but then after that just fits the rest of the snippet in with no formatting.

https://github.com/onivim/oni/blob/38566d92489ebce97d82a899a1fda8467eff786c/browser/src/Services/Snippets/SnippetSession.ts#L146-L158

We'd instead want to use the start of the prefix position as the starting point for the rest of the lines.

**Comment by Akin909** [comment]
@CrossR we use a package called `detectIndent` somewhere else for setting lines i think in the `BufferManager` file so perhaps that could be reused or maybe it isn't actually working correctly as it's I think used in the setLines function and maybe should already be indenting insertions correctly?

**Comment by CrossR** [comment]
Added a PR for this now (#2394 ), using `detect-indent`.

It looks like `setLines` is just a wrapper for the neovim API function to set lines, it doesn't apply any other logic which is why no indents were being applied. The first lines indent is maintained by using the `prefix`, and the rest are left untouched.
