### ISSUE TITLE
File explorer: Hitting <C-d> deletes file/folder

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2245]
In vim I typically use `<C-d>` and `<C-u>` to scroll through the page, however it's deleting files.

The fix can be as simple as just deleting when only the d key is stroked. It would be good if we could have the same behaviour as in vim, but it's fine if that makes it too hard.

**Comment by Akin909** [comment]
Atm `d` is bound to persistable delete and `c-d` to permanent delete so a fix for this would be to change that binding, ideally if oni had the concept of a leader key it would allow us to namespace some default oni bindings

**Comment by badosu** [comment]
Not sure what we should do, to be frank I think this is very dangerous as this is a commonly used keybinding for navigation.

If the goal is to keep it we can close this issue.

**Comment by Akin909** [comment]
@badosu it can definitely be changed maybe to `c-s-d` just seemed a bit difficult to hit but the idea isn't for it to be an often used binding i.e. my hope was that ppl would tend towards using the undoable delete so can definitely remap it if breaks pre-existing scroll functionality

**Comment by nwneisen** [comment]
I'd like to take a look at this

**Comment by nwneisen** [comment]
I've created a pull request for this change:
#2265

**Comment by CrossR** [comment]
I'll close this out now that #2245 is merged. Cheers @nwneisen !
