### ISSUE TITLE
autocomplete breaks insert command

### ISSUE THREAD

**Issue by escorponox** [onivim/oni#2257]
Oni Version: 0.3.4
Neovim Version (Linux only): 0.2.2
Operating System: Linux Mint

#### Describe your issue
When I write `al`, autocomplete to `alignItems` and back to normal mode, if I hit `.` it inserts only `al`.

#### Expected behaviour
Insert all the inserted text

#### Actual behaviour
It only inserts the typed text, not the whole autocompleted text.

#### Steps to reproduce
Use autocomplete and try to repeat that insert.

**Comment by CrossR** [comment]
Hey! Thanks for raising this issue, I know I've started to run into it a bunch recently.

It looks like we have an issue already to cover both it and the same issue with the auto insertion of parens (#1200), so I'll close this out for now. Might be worth sticking +1 on that issue as well though, but I know it is annoying to do a macro and then find either it half typed, or with weird parenthesis.
