### ISSUE TITLE
 libcanberra-gtk-module on Ubuntu

### ISSUE THREAD

**Issue by davclark** [onivim/oni#2268]
Oni Version: 0.3.4
Neovim Version (Linux only): 0.2.2
Operating System: Ubuntu 18.04

#### Describe your issue

After successful installation, including `apt install -f`, Oni complains about ` libcanberra-gtk-module`. This can be installed easily and should probably be a dependency (perhaps a "recommends").

#### Expected behaviour

Installation of Oni on LTS Ubuntu followed by `apt install -f` should result in a fully-configured Oni with all dependencies installed.

#### Actual behaviour

    $ oni init.vim 
    Gtk-Message: 12:17:06.515: Failed to load module "canberra-gtk-module"

(Oni still appears to run successfully)

#### Steps to reproduce

Install Oni on Ubuntu via the deb (see above)

**Comment by bennybobw** [comment]
I believe this is in the installation notes:
https://github.com/onivim/oni/wiki/Installation-Guide#linux

**Comment by badosu** [comment]
Unless there's any way whe can fix the deb package rasily I suggest following the tutorial and closing this.
