### ISSUE TITLE
Line copy/pasting does not work like vim

### ISSUE THREAD

**Issue by lparry** [onivim/oni#2275]
Oni Version: 0.3.4
Operating System: Mac OS 10.13.4

#### Describe your issue

Either line highlight, yank, or paste seems broken

#### Expected behaviour

`V` + `y` + `p` should result in the current line being duplicated below the current line, as it does in vi/vim/neovim/etc

#### Actual behaviour

`V` + `y` + `p` results in the current line being copied and inserted again on the same line, 1 character into the line

#### Steps to reproduce

`V` + `y` + `p`

**Comment by TalAmuyal** [comment]
Hi!
There is an active issue on the subject here: https://github.com/onivim/oni/issues/2267
It is not completely verified yet, but I think that setting `"editor.clipboard.enabled": false,` solves that with the cost of loosing <C-V> in insert-mode.

Do you mind checking and reporting back?
Also, did you set `clipboard` in your Vim config?

**Comment by Galbar** [comment]
I have the same issue.
I have set the `clipboard` option to `unnamed`.

`setting "editor.clipboard.enabled": false,` fixed it for me 👍

**Comment by TalAmuyal** [comment]
Should be fixed now in master :)
