### ISSUE TITLE
[FR] Shortcut for settings file

### ISSUE THREAD

**Issue by gatesn** [onivim/oni#2276]
cmd + , should bring up settings file on Mac. This is canonical settings shortcut in most applications

**Comment by Akin909** [comment]
@gatesn thanks for the issue, I agree re. having a shortcut to access the settings menu although do you mean `M-,` command and comma in which case yep definitely agree or if you mean `cmd-+` I usually associate that with some sort of zoom which I think is what atom, vscode (haven't used either in a while could be wrong) and the browsers do

**Comment by CrossR** [comment]
I'll close this out since as far as I can tell it was merged with #2280. Cheers @ayohan !
