### ISSUE TITLE
A suggestion of markdown preview

### ISSUE THREAD

**Issue by TillLindemann** [onivim/oni#2293]
as we all know,vim-markdown-preview plugin will open a chrome browser to preview the current editing md file,but in oni,it should be better with embedded browser,but I don't know how to do that,can you support that?Or alternatively,you can write your own markdown-preview plugin,specially designed for oni.

and if embedded browser supports proxy,it would be great!

**Comment by CrossR** [comment]
Its technically still in the experimental phase, so you need to enable it explicitly with `    "experimental.markdownPreview.enabled": true,` in your Oni config.

Then if you reload you should get options for Toggle/Open/Close markdown preview when inside a markdown file.
You'll end up with something like this:

![image](https://user-images.githubusercontent.com/10038688/41064067-61a0475e-69d2-11e8-89e6-c3f74c2f6a97.png)

There is a few small bugs that I'm addressing in #2282. I'm also looking into getting syntax highlighting in code blocks hooked up, as well as inline latex.

**Comment by TillLindemann** [comment]
@CrossR OK,I enabled the feature,everything works fine,this issue can be closed,thank you so much @CrossR  @Akin909
