### ISSUE TITLE
Unable to use HJKL when typing an address in browser

### ISSUE THREAD

**Issue by matipan** [onivim/oni#2311]
Oni Version: 0.3.4
Neovim Version (Linux only):
Operating System: macOS 10.13.5

#### Describe your issue
When I open a browser, go into the field for typing the address and try to use any of the `h j k l` keys they are not being typed in, it is instead acting as navegation.

#### Expected behaviour
I would expect for them to be typed in as all other keys.

#### Actual behaviour
Here is a short GIF of what is happening
![onivim-browser](https://media.giphy.com/media/5z3V2cSj3L089w6LTS/giphy.gif)

#### Steps to reproduce
I don't know if this is configuration specific, but I'll leave my neovim and onivim configs here just in case.  
Onivim
```typescript
const activate = (oni) => {
  oni.input.bind("<f9>", "markdown.togglePreview")
}

module.exports = {
    activate,

	"oni.hideMenu": true,
	"oni.loadInitVim": "/Users/matipan/.config/oni/init.vim",
	"oni.useDefaultConfig": false,

	"ui.colorscheme": "deep-space",
	"ui.fontFamily": "'SauceCodePro Nerd Font'",

	"editor.textMateHighlighting.enabled": false,
	"editor.typingPrediction": false,
	"editor.fontFamily": "SauceCodeProNerdFontComplete-Regular",
	"editor.fontSize": "12px",
	"editor.fontLigatures": false,
	"editor.renderer": "webgl",

	"language.go.languageServer.rootFiles": [".git"],
	"language.go.languageServer.command": "go-langserver",
	"language.go.languageServer.arguments": ["--freeosmemory", "false"],

	"tabs.mode": "buffers",
	"sidebar.default.open": false,
	"workspace.autoDetectWorkspace": "always",
	"autoClosingPairs.enabled": false,
	"commandline.mode": false,
	"wildmenu.mode": false,
	"learning.enabled": false,
	"achievements.enabled": false,
	"experimental.markdownPreview.enabled": true
}
```
My neovim config is quite large and can be seen [here](https://github.com/matipan/dotfiles/blob/master/oni.vim)

**Comment by CrossR** [comment]
Hey,

I think this is covered over in #2136.

Its not due to your config, but rather the oni default keybinds not turning off when entering somewhere  you input text.

I'll close this out, but I've definitely hit this, so I'll stick a follow up on the other issue to see if somebody has any ideas that I can add.
