### ISSUE TITLE
[Feature request] Go to Definition

### ISSUE THREAD

**Issue by SamHH** [onivim/oni#2317]
Oni Version: 0.3.4
Neovim Version (Linux only): 0.3.0
Operating System: Arch

In VSCode you can go directly to the definition of a symbol in some languages such as TypeScript. You can find a short description and screenshot of this feature [here](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition).

As far as I can tell this isn't yet supported in Oni. I'd really love for it to be implemented! Cheers :smiley:

**Comment by CrossR** [comment]
Hey!

Oni does that have this (when the LSP supports it, so TS/JS works out the box).
By default its bound to F12, and its the command pallete as well, which is `Ctrl-Shift-P`.

**Comment by TalAmuyal** [comment]
Also works with `pyls` for Python.
`gd` also triggers the feature (and is easy to remember).

Closing, but if you are not satisfied with the answers, please reopen.

Cheers :)

**Comment by SamHH** [comment]
Thanks guys!

My only query is whether there's any way to make it open the definition in a new tab?

**Comment by badosu** [comment]
The vim only way to trigger this is by `<C-]>`, if you have the tags ran for the current file.

I wonder if there's a way to remaps this keybinding for a specific file if a LSP with Go to definition feature is enabled.

**Comment by CrossR** [comment]
>My only query is whether there's any way to make it open the definition in a new tab?

Currently I don't think so, though it should be simple enough to change / add an option for it if needed?

**Comment by badosu** [comment]
> Currently I don't think so, though it should be simple enough to change / add an option for it if needed?

@SamHH Alternatively, after inspecting the definition you can type `<C-^>` to get back to the previous file.
