### ISSUE TITLE
Upcoming release?

### ISSUE THREAD

**Issue by Siilwyn** [onivim/oni#2333]
Stupid question, will there be a new release soon?

Since https://github.com/onivim/oni/issues/2047 is fixed I've been checking there releases page eagerly.
:)

**Comment by CrossR** [comment]
Hey!

There should be a release fairly soon, to go with the recent release of Neovim 0.3.0 and all the other changes that have been added to Oni since the last release!

**Comment by Siilwyn** [comment]
Okay, cheers!
