### ISSUE TITLE
Plugins not loaded

### ISSUE THREAD

**Issue by stuartellis** [onivim/oni#2351]
**Oni Version:** 0.3.4
**Neovim Version (Linux only):** N/A
**Operating System:** macOS 10.12.6

**Issue:** Oni does not load plugins, as documented: https://onivim.github.io/oni-docs/#/./oni.wiki/Plugins?id=installing-a-vim-plugin

**Expected behavior:** Oni should automatically load vim plugins.

**Actual behavior:** Nothing :) - the plugins were not loaded. Once I created an `init.vim` file and installed the plugins with vim-plug, Oni detected the init.vim as expected and loaded the plugins correctly.

**Steps to reproduce:**

    cd ~/.oni
    mkdir -p plugins
    cd plugins
    git clone https://github.com/lifepillar/vim-solarized8

The command `:colorscheme solarized8_light` reported that the color scheme was not found. I also tried  using the directory `~/.config/oni/plugins`, and the directory `~/.config/nvim/plugins` (as a wild guess, just because `~/.config/nvim` is on the runtimepath, and `~/.oni/plugins` is not).

**Comment by stuartellis** [comment]
Hello @CrossR,

Thanks for the quick response! Following your post, I deleted everything Vim-related from my home directory, made sure to close Oni, followed the steps on the Wiki to install into `~/.config/oni/plugins`, then started Oni...and it works: plugins load correctly. I have tested with the vim-solarized8 plugin and the vim-go plugin.

Before, the plugins loaded once I used init.vim and a plugins directory managed by vim-plug, but they did not load from `~/.config/oni/plugins`. I suspect that you are right, and that I did not actually fully shutdown Oni whilst setting up this directory.

**Comment by CrossR** [comment]
Glad you got it sorted!

I'll leave this issue open for now, as we should get that documentation updated. I'll also update our release docs to include that step, since the Wiki follows master, so the site should be updated once we make a new release.

**Comment by CrossR** [comment]
Closing this out now since the website was updated.
