### ISSUE TITLE
Weird tearing artifacts with proportional fonts

### ISSUE THREAD

**Issue by mbeach42** [onivim/oni#2359]
**Oni Version:** 0.36
**Neovim Version (Linux only):** 0.3.0
**Operating System:** Antergos OS (Arch derivative)

**Issue:** Weird tearing artifacts with proportional fonts

**Expected behavior:** Display font correctly like VS-Code, Atom, Sublime, etc.

**Actual behavior:** Almost works, but displays weird horizontal lines as artifacts.
![2018-06-26-073546_2560x1440_scrot](https://user-images.githubusercontent.com/8442696/41909255-8c5d335c-7914-11e8-857d-1395927ff304.png)

**Steps to reproduce:** Set  "editor.fontFamily": "Input", (Input is a proportional font)

**Comment by CrossR** [comment]
Hey!

Thats interesting! I'd be interested to see if its still reproducible with `    "editor.renderer": "webgl",`, since that fixed a bunch of these styles of issues caused by subpixel-antialiasing.

**Comment by mbeach42** [comment]
Looks like "webgl" works! Thanks!

**Comment by badosu** [comment]
@CrossR @mbeach42 Since webgl is not the default renderer yet, should'nt we keep this keep this issue open?

**Comment by CrossR** [comment]
We've got more focused issues on the remaining items in the webgl renderer, and other issues with more details on what caused this and why the webgl renderer fixes it, so I think its fine to close this off.
