### ISSUE TITLE
i see it no chinese document ,please wirte document  of someone

### ISSUE THREAD

**Issue by Lneedy** [onivim/oni#2362]
**Oni Version:**
**Neovim Version (Linux only):**
**Operating System:**

**Issue:**

**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Comment by badosu** [comment]
Hello, we are a very diverse group of programmers, but unfortunately we don't have (yet) a frequent contributor who knows Chinese.

As there isn't too much we can do for now I'll close this issue.

The Wiki is free for anyone to edit and add chinese translations, thanks!
