### ISSUE TITLE
Oni does not open selected folder from the command-line 

### ISSUE THREAD

**Issue by stuartellis** [onivim/oni#2376]
**Oni Version:** 0.3.4
**Neovim Version (Linux only):** N/A
**Operating System:** macOS 10.12.6

**Issue:** My workflow is based around the command-line, so my habit is to navigate to a directory in the shell, then launch the code editor if I need to edit files. Oni always opens with the same directory  in the Explorer that was open the last time that it was closed, and ignores the command-line if a directory is specified.

**Expected behavior:**

If Oni is called in a shell, open Oni with the specified folder in the Explorer, e.g.:

    oni mydirectory
    oni .

**Actual behavior:**

Oni always opens with the same folder in the Explorer that was open when it was closed, and ignores the command-line if a directory name is specified.

If Oni is started from the command-line with a specific file, the editor pane opens with the correct file, but the Explorer shows the same directory in the Explorer that was open the last time that Oni was closed.

**Steps to reproduce:**

1. Type ```oni .``` in a shell.
2. Be momentarily confused when Oni opens, showing a different directory :)

**Comment by CrossR** [comment]
Hey,

The CLI for Oni has caused a few people to raise some issues, the biggest of which is this one: #1707.
It sounds like you agree with what is outlined over in the "Workspace detection" section of that RFC?

I've actually just started the work on getting the stuff in that RFC implemented over in #2372, so I'd be interested in any comments on it before I start implementing the workspace detection bit (I'm sorting the ability to detach from the shell first, which you may have also bumped into).

That said, there was a few changes to the workspace detection logic in the past few releases, so it may be worth you updating to `0.3.6` as well. From a quick look, that has #2264 in, which I think solves this specific issue.

**Comment by stuartellis** [comment]
Hello @CrossR - I've now read #1707, and yes, it describes the behaviour that I would expect. I had missed that there was a new version of Oni, and the upgrade has fixed this issue, so I've now closed this ticket.

I have a sacrificial Linux box, so I'll see if I can get your WIP for #2372 running there.
