### ISSUE TITLE
How to set background of colorscheme in the editor ?

### ISSUE THREAD

**Issue by babbarshaer** [onivim/oni#2383]
I am trying to set the dark background on gruvbox colorscheme. I am unable to locate the corresponding setting in the config.js documentation. Can someone point me to the same ?

**Comment by CrossR** [comment]
To my knowledge, this should be done with `"colours.background": "#ffffff",` in your config.js as outlined over in https://github.com/onivim/oni/wiki/Configuration#colors.

However, when I tried this for the background...that didn't work, and the override didn't work. @bryphe has this changed recently?

If you weren't talking about manually overwriting colours, but rather setting the colourscheme in the first place, you should just be able to use `    "ui.colorscheme": "gruvbox_dark",` in your config.js.

**Comment by babbarshaer** [comment]
@CrossR : I was confused about setting the colorscheme only. But should we keep this issue opened up for the clarification of the question you asked ?

**Comment by CrossR** [comment]
I'll create an issue with a bit more details in, so its a bit clearer!

Thanks for the follow up and for checking though!
