### ISSUE TITLE
Browser won't open for me

### ISSUE THREAD

**Issue by vlurgio** [onivim/oni#2401]
**Oni Version:**  
**Neovim Version (Linux only):**
**Operating System:**
 Mac osx

**Issue:**
Typing Browser: Open Vertical isn't doing anything for me. Also is there a way to hold j and k and have it scroll up continuously. repeated keys work with all my other keys but not the movement keys. (Upon further testing it seems none of the oni commands are working like Browser, Terminal, etc.)
**Expected behavior:**
The browser opens. 
**Actual behavior:**
Nothing happens
**Steps to reproduce:**
install oni via homebrew 
open oni
press cmd-p 
type Browser: Open Vertical

**Comment by CrossR** [comment]
I'm not able to repro this on Windows, so I'll give it a test on macOS as well. Do you have any custom Oni or Neovim config that could be conflicting?

For the repeated keypresses, have you ran this command from the[ install guide](https://github.com/onivim/oni/wiki/Installation-Guide#mac)?

```
defaults write com.extropy.oni ApplePressAndHoldEnabled -bool false
```

We've an ongoing PR to automate this, but its not merged yet.

**Comment by vlurgio** [comment]
I was definitely using the command pallet and not the fuzzy file finder. However I ended up switching to vscode as it was much easier to just have vim key bindings there and get everything to work.

**Comment by badosu** [comment]
Closing it until someone can reproduce and provide more detailed information
