### ISSUE TITLE
yarn install fails with node v10.6.0

### ISSUE THREAD

**Issue by Muream** [onivim/oni#2430]
**Oni Version:** Master
**Neovim Version (Linux only):** 0.3.0
**Operating System:** Arch Linux

**Issue:**
I basically had this issue: https://github.com/facebook/create-react-app/issues/4367
running `yarn --ignore-engines install` did the trick but it might be worth updating the upath version since 
it seems the latest version doesn't have this problem.

**Steps to reproduce:**
Simply follow what the wiki says to build Oni with node v10.6.0

**Comment by Prior99** [comment]
This is due to the dependency `upath` not being the latest version. According to https://github.com/anodynos/upath/issues/24, it needs to be upgraded in order to resolve this.

**Comment by light2yellow** [comment]
Not fixed? On openSUSE Tumbleweed:
```
% git describe --tags --long
v0.3.7-beta2-37-gc7b11e46
```

```
% yarn install  
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.13.0"
```

**Comment by saitonakamura** [comment]
Not working for me also. Despite having `ignore-engines` in `.yarnrc`, yarn doesn't seem to peek this settings (maybe a windows issue). By the way, `upath` was [updated to `1.0.5`](https://github.com/anodynos/upath/commit/8c5f4e10376ed1cd4553d9432297d39a34410c69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) where it doesn't have this issue. We can use [yarn resolutions](https://yarnpkg.com/en/docs/package-json#toc-resolutions) to fix it now.
