### ISSUE TITLE
Language Extensibility: Add quick fix support

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#245]

**Comment by extr0py** [comment]
- Need to figure out what the UI would look like. The quick fix might make sense in both `insert` and `normal` mode. In both modes, maybe we could re-use the quick info paradigm? Or, if there is both quickinfo + a fix, show the fix listed in the quickinfo box?

**Comment by bryphe** [comment]
Tracked this also in #474 , and that has more info - closing this as a dup.

**Comment by CrossR** [comment]
Was just looking at the bountysource website, looks like there is a bounty pointing at this issue, should probably update it to point at the newer issue?
