### ISSUE TITLE
terminal command menu just opens panel without terminal

### ISSUE THREAD

**Issue by razcore-art** [onivim/oni#2450]
onivim 0.3.6
When opening the terminal with the command menu (eg. `Terminal: Open Horizontal`) the actual terminal emulator doesn't open, I'm forced to manually open it with `:term`, see attached picture. I'm using `"editor.split.mode": "oni"`, but I've tried with normal behavior and is the same issue.

I'm on `Linux alienware 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

![image](https://user-images.githubusercontent.com/1177508/43114128-244331ce-8f06-11e8-928e-76ad3d56ff38.png)

**Comment by Akin909** [comment]
@razcore-art I've just tried this on mac os and it works for me, as far as I can see its opening a buffer titled bash it could be that the command that we use to open a terminal on linux doesnt work @CrossR (I know you run a linux machine sometimes) have you encountered this error as well?

**Comment by razcore-art** [comment]
@Akin909 hey there, so now that you made me think about it, it might got to do with the fact that I'm running tmux in the terminal (it's set-up to autostart via `.bashrc`), I'll try without tmux and see what happens.

**Comment by CrossR** [comment]
The shell that is called is done via [neovim's shell variable](https://github.com/onivim/oni/blob/ee134d3e0519b78daad94fc9c93d0fdcbf3dca73/browser/src/Services/Terminal.ts#L19-L23), which you can check with `:set shell?`.

It might be worth checking that variable, or setting `terminal.shellCommand` to a different value?

**Comment by razcore-art** [comment]
I tried changing `terminal.shellCommand` and checked `:set shell?` (which gives `/bin/bash`) but nothing helps, there's no info regarding this stuff in the dev console either so I'm kinda' stuck.

**Comment by razcore-art** [comment]
Oh I should probably mention that oni does try to open the terminal (in my case with bash) but I'm not exactly sure what goes wrong, so at the bottom in the status bar of the tab it says:
![image](https://user-images.githubusercontent.com/1177508/43354159-8847ab40-924f-11e8-8e5b-696d433ddb43.png)
while for the buffer with the actual terminal (after executing `:term`):
![image](https://user-images.githubusercontent.com/1177508/43354160-9eb45e96-924f-11e8-8db2-10cbd875eed2.png)
Seem like in the first case the terminal is opened as a regular file, I can edit it etc. - haven't tried saving yet :)

**Comment by CrossR** [comment]
As per `:help terminal`: `- By editing a file with a name matching `term://(.{-}//(\d+:)?)?\zs.*`.`, so it should work... At least I use it on Windows with `term://cmd` or `term://bash`.

Technically though, like you've said Oni does start it differently to normal term, with `:w term://...` not `:term`. Not the best way, but I'd try debugging by manually calling a few different things.

That is, try calling `:w term://bash`, `:w term:///bin/bash` etc. I'm not sure if term (at least in the way Oni starts it) supports a full path. I use 4 terminals, but they all start with a command first (`cmd`, `powershell`, `bash`...). If we figure out that, you can at least set `terminal.shellCommand` for now, and we can look for a more robust solution based on that.

**Comment by razcore-art** [comment]
@CrossR hm! well, I tried both `:w term://bash` and `:w term:///bin/bash` (and with `:e` - as in the neovim docs) in both oni and neovim and it seems it's a neovim bug as it just tries opening up a file instead of the shell. If I use `:term` there's no problem but with the stuff mentioned in the docs it doesn't work, I'll report this to neovim, don't think it's oni's fault but if you have a workaround using that `terminal.shellCommand` that'd be great!, I already tried `'terminal.shellCommand': '/bin/bash'` but that doesn't work either. Is there any other way I can use this config entry?

**Comment by CrossR** [comment]
>(and with :e - as in the neovim docs)

Whoops, yeah sorry, not `:w`.

I've given it a test on my Arch machine and it works fine on there calling `:e term:///bin/bash` so it should work... I'd maybe see if its your config somehow, and since you are on Linux, that your Neovim version is   up-to date.

>I already tried 'terminal.shellCommand': '/bin/bash' but that doesn't work either. Is there any other way I can use this config entry?

I don't think so....If it is not set, it should just get the shell from nvim, and use that, but since calling that manually isn't working for you, I guess that isn't going to work either. We could potentially swap the logic, and if `terminal.shellCommand` is null, we just call `:term` instead, so we don't have to deal with this.

**Comment by razcore-art** [comment]
Well, I up to date (from the stable ppa at least), in any case this seems to be a neovim/neovim config problem not oni so I'm closing this issue, thanks!
