### ISSUE TITLE
No help on command line

### ISSUE THREAD

**Issue by xelra** [onivim/oni#246]
When typing `oni --help` or `oni -h` on the command line, no help appears that explains options. Instead it just starts ONI.

**Comment by extr0py** [comment]
Good point, thanks for tracking this.

**Comment by extr0py** [comment]
We can potentially do the following:
- add `minimist` library to `main.js`
- look for `-h, --help` options
- print out some canonical help text with our current supported options

**Comment by keforbes** [comment]
Are there any flags/options Oni currently supports?  It seems to me the help would just be:
```
Oni [filename]
       launch Oni with or without a filename
```
I agree we should have some help output but what else would go in the help?

**Comment by CrossR** [comment]
Looks like this was added now by @someguynamedmatt in #1509.
Cheers!

I'll close now then.
