### ISSUE TITLE
Auto completion "hint" has no scrolling bar...

### ISSUE THREAD

**Issue by EvgeniyUS** [onivim/oni#2467]
![list](https://user-images.githubusercontent.com/25228686/43275472-8aef2756-910a-11e8-9178-f4baa7a49222.jpg)

**Oni Version:** 0.3.6
**Operating System:** Win10
**Language:** Python

**Issue:** Auto completion "hint" has no scrolling bar. When N_rows > 10 then not possible to view all of them without typing something.

OR its a feature??

p.s. Taking this opportunity, I want to say that you are doing an excellent job! Many thanks!

**Comment by dkns** [comment]
Duplicate of https://github.com/onivim/oni/issues/2046 I believe.

I noticed this behaviour but not for every filetype. IIRC I did have scrollbar when using python but was having the same issue as posted here with javascript/typescript.

**Comment by badosu** [comment]
Yes, this is duplicate of #2046.
