### ISSUE TITLE
Add electron to Oni api dependencies

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#2474]
**Issue:**
We currently add react as a dependency on the oni api, I suggest also adding electron to the dependencies, the reason being that for plugins that aim to add electron based functionality such as https://github.com/jordan-arenstein/oni-plugin-touchbar @jordan-arenstein's amazing touchbar plugin (for macOS) the plugin maker must add electron as a dependency which bloats the plugin's size

**Comment by TalAmuyal** [comment]
@Akin909, correct me if I'm wrong, but wouldn't it mean that Electron will be downloaded anyway as part of the API?
Aside from that, running `npm install electron --save-dev` will install Electron as a dev-dependency (thus not polluting the release) and add Electron's definition (https://electronjs.org/blog/typescript) - will it be enough?

**Comment by Akin909** [comment]
@TalAmuyal I didn't realise electron was a dev dependency you're right it wouldn't solve the bloat problem would instead just move it `Oni` instead which is less good, as using save dev that wouldn't help with plugin or allow us to export it as a dependency I think 😢 in which case with no clear solution I think ill close this
