### ISSUE TITLE
Onivim Fold

### ISSUE THREAD

**Issue by Sandee022** [onivim/oni#2486]
Persistent folding not working need some help!

augroup AutoSaveFolds
  autocmd!
  autocmd BufWinLeave * mkview
  autocmd BufWinEnter * silent loadview
augroup END

This gives error in onivim.

**Comment by dkns** [comment]
It's hard to debug if we don't know what is the error message.

**Comment by badosu** [comment]
@Sandee022 Any help? It's not clear what the issue is and how to reproduce.
