### ISSUE TITLE
OpenSuse Support

### ISSUE THREAD

**Issue by midnio** [onivim/oni#2498]
**Issue:** I'm using OpenSuse Tumbleweed. I want to use Oni but I can't install on here. Is there a way to install it one OpenSuse?

**Comment by dkns** [comment]
Why can't you install it? What did you try? What happened? Did you get any error messages?

**Comment by midnio** [comment]
Is there a "building" Oni Editor Tutorial?

**Comment by dkns** [comment]
Can you try instructions found on this page under `setup` and `building`? https://github.com/onivim/oni/wiki/Development

**Comment by midnio** [comment]
Thanks, I'll test it, if it doesn't work I'll reopen the issue.

**Comment by badosu** [comment]
@midnio Altenatively you can try the rpm listed here: https://github.com/onivim/oni/releases/tag/v0.3.6

Not sure if it's target is compatible with suse though.
