### ISSUE TITLE
Make scrollbar clickable

### ISSUE THREAD

**Issue by keforbes** [onivim/oni#251]
This is one of those annoyances that I hit multiple times per day.  I keep thinking I can click and drag on the scrollbar to move it but instead this is registered as a mouse click in NeoVim and moves into Visual mode.  I know this won't be fixed anytime soon but I just wanted to file it.

![scrollbar](https://cloud.githubusercontent.com/assets/817509/23273155/27c998b0-f9bb-11e6-95a1-77ecaee8e84b.gif)

**Comment by gildean** [comment]
The missing grip stops me from even trying out this program.

**Comment by bryphe** [comment]
Looks like @aefimenko might be looking at this 👍

**Comment by bryphe** [comment]
@jordan-arenstein , thank you so much for fixing this! 

FYI, there was a bounty associated with this item - make sure to collect it here: https://www.bountysource.com/issues/42373618-make-scrollbar-clickable 

Click 'Solve Issue' on that screen to submit the fix, and we'll approve it! 😄

**Comment by Akin909** [comment]
Can this be closed since its now implemented @keforbes @jordan-arenstein ?

**Comment by keforbes** [comment]
Yep, that's fine.  Go ahead and give @jordan-arenstein that bounty!
