### ISSUE TITLE
Oni's file explorer is much harder to read than in other editors

### ISSUE THREAD

**Issue by GoAwayPeter** [onivim/oni#2510]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):** 0.2.2
**Operating System:** Ubuntu 16.04

**Issue:** Compared to other editors such as VSCode, or LightTable, Oni's file explorer indentation is almost nonexistent, the spacing between elements is large, and the distance between the caret and text in an element of the file explorer is also very large. This makes the file tree structure much harder to read, as shown below; 

![file-explorer-change](https://user-images.githubusercontent.com/6030503/44313450-f90af400-a400-11e8-88c3-ce5ff8271ef5.png)

The current (labelled 'Old') file explorer is on the left. As you can see, VSCode is much clearer in terms of readability. On the right (labelled 'New') is an attempt to copy the spacing of VSCode's file explorer in Oni.

**Expected behavior:** Easy to differentiate between a file inside a folder and one outside it

**Actual behavior:** It isn't

**Steps to reproduce:**

**Comment by badosu** [comment]
@GoAwayPeter Does #2511 address this?

**Comment by GoAwayPeter** [comment]
@badosu Whoops! Yes, it does :)
