### ISSUE TITLE
Documentation for sidebar

### ISSUE THREAD

**Issue by iamkarlson** [onivim/oni#2512]
Is there any documentation how to take control over the sidebar? For my particular example, sidebar is not always synchronized with a directory of the open solution. Although, I don't know did I do anything wrong or it's expected behavior. Also, it's very helpful might be for those who want to adjust that sidebar to be similar to one which is in VSCode. I tried some standard place like 'help sidebar' but it's probably not the case for Oni, is it?

**Comment by badosu** [comment]
@iamkarlson The sidebar should use the directory you opened Oni with (if opened from the terminal).

If opened from the launcher it will probably be in your home directory, you can then use `cd path/to/code`.

**Comment by iamkarlson** [comment]
@badosu many thanks for the explanation. can it be navigated and operated with hotkeys only?

**Comment by badosu** [comment]
Ctrl+Shift+b - Toggle file explorer visibility
Ctrl+w,Ctrl+h - Go to left pane
Ctrl+w,Ctrl+l - Go to right pane

Added these to the shortcuts wiki page. Let me know if there's anything else missing.
