### ISSUE TITLE
Visual stutter on file explorer sidebar

### ISSUE THREAD

**Issue by unr** [onivim/oni#2517]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):** v0.2.2
**Operating System:** Mac OS High Sierra 10.13.6 (17G65)

**Issue:**
When browsing a large folder, and scrolling the pane, it glitches out and jumps around. Kind of makes it unusable unless I hand `:cd folder/` each time

**Expected behavior:**
That the panel scrolls.

**Actual behavior:**
It scrolls jank af. [Here's a video example](http://unr.im/260S1a420z47)

**Steps to reproduce:**
`:cd node_modules`, go to file explorer, hold J

**Comment by CrossR** [comment]
It sounds like this is https://github.com/onivim/oni/pull/2182?

I'm not too sure on the current status of that PR though.

**Comment by Akin909** [comment]
@unr @CrossR it is a known issue (#2314) which #2182 aims to solve, @CrossR that PR unfortunately has a very sporadic/rare/annoying bug as the react-virtualized logic has unfortunately become a bit complicated (trying to address a suggestion of @bryphe re. avoiding arbitrary height values, more discussion on the PR thread)

**Comment by Akin909** [comment]
I'm going to close this in favour of #2314 so we don't get confused having both open either of you feel free to re-open (please 🙏 ) if that issue doesnt cover things

**Comment by unr** [comment]
Awww, I tried to find a related issue to share my clip too.

Thanks guys, as long as this is logged somewhere I'm happy.

---

Also, wow guys. Oni Issue response time is probably one of the fastest I've seen haha.
