### ISSUE TITLE
Is there any development for elixir plugin and terminal integration in Oni? 

### ISSUE THREAD

**Issue by rokfrog** [onivim/oni#2521]
**Oni Version:** oni version 0.3.6
**Neovim Version (Linux only):** NVIM v0.2.2
**Operating System:** LinuxMint

**Issue:** Kindly can we have Elixir plugin available for Oni

**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Comment by badosu** [comment]
Vim is officially supported by the Elixir team: https://github.com/elixir-editors/vim-elixir

Specific language support is too much to be expected for upstream development. Contributions are very welcome though.

Oni supports language servers natively, so you can try configuring https://github.com/JakeBecker/elixir-ls and contributing with your results. See: https://github.com/onivim/oni/wiki/Language-Support#language-servers
