### ISSUE TITLE
Cannot read or write temp files / Error detected while processing function

### ISSUE THREAD

**Issue by fpn** [onivim/oni#2563]
**Oni Version: 0.3.6**
**Operating System: Microsoft Windows 10 Pro Version 10.0.17134 Build 17134**

![image](https://user-images.githubusercontent.com/1007715/45313356-924e9700-b4e3-11e8-98ed-3f5972c33e76.png)

![image](https://user-images.githubusercontent.com/1007715/45313384-a0041c80-b4e3-11e8-915b-6c0ed16cadd7.png)

**Issue:**
When running ONI for a while I always end up in a state where Gdiff or Ack don't work anymore.

It seems to be something about read/writing temp files.

Feels like a temp dir that was created by oni is gone?

**Comment by badosu** [comment]
Is this something that might warrant a section in the README or wiki?

**Comment by fpn** [comment]
no I think it is a bug


If you keep a handle open the directory will not go away.

**Comment by badosu** [comment]
Any pointers on how to reproduce?

**Comment by fpn** [comment]
Hmm, now I am curious what deletes it. Let's see whether I can run procmon that long...

**Comment by fpn** [comment]
Well the quick developer test is:
* cd %TEMP%
* delete all oni temp directories
* open oni
* run Ack or Gdiff or...
* delete the newly created nvim temp directory

good case: directory is in use and can not be deleted

# run Ack or Gdiff or ... again - it should work

**Comment by justinmk** [comment]
I think we may want to change Nvim core to manage its temp files somewhere in the users's cache directory (see `:help xdg`). That would fix this particular case, although Nvim should still probably be able to handle the case where the temp directory goes missing.

**Comment by badosu** [comment]
Well, was the deletion of the temp directory made by Oni?

**Comment by badosu** [comment]
Ok, closing this as this should be handled by neovim
