### ISSUE TITLE
Error Opening Files `A JavaScript error occurred in the main process`

### ISSUE THREAD

**Issue by ArthurZ** [onivim/oni#2586]
**Oni Version:**
0.3.6
**Neovim Version (Linux only):**
**Operating System:**
Mac 10.13.6
**Issue:**
Error opening files
**Expected behavior:**
File opens
**Actual behavior:**
Error Title
`A JavaScript error occurred in the main process`
Error text
```
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createWindow (/Applications/Oni.app/Contents/Resources/app/lib/main/src/main.js:128:25)
    at App.electron_1.app.on (/Applications/Oni.app/Contents/Resources/app/lib/main/src/main.js:197:9)
    at emitTwo (events.js:126:13)
    at App.emit (events.js:214:7)
```
**Steps to reproduce:**
Open a file from within Finder (Mac)

**Comment by CrossR** [comment]
Hey, sorry for the slow reply!

I think this was fixed just after the latest release over in https://github.com/onivim/oni/pull/2366!
We're looking at getting 0.3.7 out fairly soon I think, so I'll pre-emptively close this since it should be fixed. If not, can reopen and debug it a bit more.
