### ISSUE TITLE
Tutorial: key to start next lesson

### ISSUE THREAD

**Issue by aeosynth** [onivim/oni#2597]
**Oni Version:** 3.6
**Operating System:** Solus Linux

**Expected behavior:** Pressing Space or Enter after a complete tutorial moves to the next tutorial

**Actual behavior:** The current tutorial is restarted

How are we supposed to go through the tutorial without using the mouse, by pressing Ctrl-g to sneak the ui?

**Comment by keforbes** [comment]
After completing a tutorial there should be a message saying:
```
Press ENTER to continue or SPACE to restart
```
Are you pressing <kbd>Enter</kbd> or <kbd>Space</kbd>?  Only <kbd>Enter</kbd> will move on to the next tutorial.

**Comment by aeosynth** [comment]
ah, whoops, you're right

**Comment by sixtyfive** [comment]
@aeosynth, how did you get Onivim to run in Solus? All I'm getting is a segfault :-/

**Comment by aeosynth** [comment]
sorry I'm on Arch now
