### ISSUE TITLE
"Create File" and "Create Folder" functions have same title in command pallet

### ISSUE THREAD

**Issue by jabocg** [onivim/oni#2607]
**Oni Version:**
0.3.6
**Operating System:** 
Windows 7 32-bit

**Issue:**
The command pallet functions for creating a new file and creating a new folder [have the same title](https://i.imgur.com/I9iEX0r.png).

**Expected behavior:**
There should be a function titled "Create A New File in the Explorer" and one titled "Create A New Folder in the Explorer."

**Actual behavior:**
There are two functions titled "Create A New File in the Explorer", despite them doing different things(one creates a file, one creates a folder).

**Steps to reproduce:**
1) Focus sidebar
2) Open explorer
3) Open command pallet(ctrl-shift-p)
4) Type "new"
5) Options include "Create A New File in the Explorer" and "Create A New File in the Explorer"

**Comment by badosu** [comment]
Weird, I wasn't able to reproduce this bug in `0.3.7-beta3`.

This is what I see, also tried with just 'new':
![screenshot from 2018-10-03 22-06-30](https://user-images.githubusercontent.com/347552/46447559-f79b4e00-c758-11e8-94f2-10a79875012a.png)

This is [the place](https://github.com/onivim/oni/blob/c96d4e4bf0e0a0caca5879dceb134d35be8948d7/browser/src/Services/Commands/GlobalCommands.ts#L64-L66) that registers the command, was not able to find the one for the folder.

**Comment by CrossR** [comment]
@badosu since it is an explorer command, its only active once you are inside the explorer.

It looks like this was fixed over in #2460, so I'll close this!
