### ISSUE TITLE
Unable to open neovim instance in oni

### ISSUE THREAD

**Issue by pranphy** [onivim/oni#2609]
**Oni Version:** 0.3.7
**Neovim Version (Linux only):** NVIM v0.3.2-dev
**Operating System:** Ubuntu 16.04

**Issue:** Cannot edit files. Oni starts normally. But the embeded editor is not started. Doesn't show "Oh no!" screen either as other have reported. Checked on `Help > Developer Tools > Console ` and started to edit a file or click one of the vim tutorials shows this.

![image](https://user-images.githubusercontent.com/10902216/46471925-7ddf8080-c7a9-11e8-813c-1c6b7bc4b74c.png)

**Comment by CrossR** [comment]
Hey, we have an issue for this over at #2580, which looks like it covers this!

I'll close this for now, but feel free to reopen if it doesn't cover it.
