### ISSUE TITLE
spread operator ligatures not rendering correctly using webgl renderer

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#2610]
**Oni Version:** Master
**Neovim Version (Linux only):** 3.1.0
**Operating System:** MacOS

**Issue:**
(cc @Cryza) 	
The ligature for the spread operator in js `...` does not render as one whole if inside of an array `[...obj]` whilst the cursor is elsewhere in the page. If the cursor however is one character before the operator then it correctly renders as one ligature character. If used elsewhere i.e. in an obj or in a multiline block it works as expected

**Expected behavior:**
Character consistently renders a ligature

**Actual behavior:**
<img width="175" alt="screen shot 2018-10-04 at 12 46 49" src="https://user-images.githubusercontent.com/22454918/46472361-d5471600-c7d4-11e8-8a3c-b4f041c33710.png">

**Steps to reproduce:**
* Open a `js/ts` file.
* create an array
* just inside type `...variableName`
* move the cursor to another line

**Comment by Cryza** [comment]
Thanks for notifying me, @Akin909 ! This was an issue with our custom additions to the `fontkit` logic in our branch, `oni-fontkit`. I was able to fix it within https://github.com/Cryza/oni-fontkit/commit/3f06f1aa9e300db25f4313b6d0792c42d55d79f4 and released the new version to npm. I'll open a PR for bumping our dependency and that should fix the issue :)
