### ISSUE TITLE
Can't open file OniVim

### ISSUE THREAD

**Issue by kazukazuinaina** [onivim/oni#2675]
**Oni Version:**
0.3.6
**Neovim Version (Linux only):**
**Operating System:**
Mac OS Sierra ver10.12.6
**Issue:**
Hi, I find to one ploblem.
For example, I write "$ oni test.js" in terminal but the file can't be open OniVim.
Please check it.
**Actual behavior:**
OniVim can't make specific file in terminal.

**Comment by samvv** [comment]
I am looking in to this one. This shouldn't be too difficult to add.

**Comment by bryphe** [comment]
Thanks for the help @samvv ! This would be great functionality to have.
