### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by marcrib** [onivim/oni#2677]
Copy and past vscode source? or atom? Changed only the names of the variables?
Why not contribute an editor already exists?
What is the purpose of creating other editor?

**Comment by samvv** [comment]
There really isn't anything like Oni, except perhaps for [NyaoVim](https://github.com/rhysd/NyaoVim). In theory, it allows to **easily** build any GUI interface that you can think of that interacts with Vim without having to resort to C++ source code. What editor are you expecting us to contribute to? And what do you mean with "changed the name of the variables"? As far as I know there isn't any code shared with any of these other projects.

Sorry if I misunderstood you.

**Comment by badosu** [comment]
See: https://github.com/onivim/oni#goals
