### ISSUE TITLE
TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by samvv** [onivim/oni#2681]
**Issue:**

Seems like the build on `master` is broken.

**Expected behavior:**

The build passing all tests in pull request #2679. See also #2673 and #2680.

**Actual behavior:**

Travis CI build failing.

**Comment by samvv** [comment]
Seems like @bryphe already solved the issue. Closing this one.

**Comment by bryphe** [comment]
Thanks for looking at this / logging the issue @samvv ! Ya, unfortunately our build cache was out of date... I cleaned it up and restarted your builds. Change looks good!
