### ISSUE TITLE
wpgtk.vim colour scheme does not work in Oni

### ISSUE THREAD

**Issue by lachlantula** [onivim/oni#2696]
**Oni Version:** 0.3.9
**Neovim Version (Linux only):** 0.3.1
**Operating System:** Manjaro Linux (kernel 4.14.90-1-MANJARO)

**Issue:** The [wpgtk.vim](https://github.com/deviantfero/wpgtk.vim) colour scheme (similar to [wal.vim](https://github.com/dylanaraps/wal.vim)) is not working properly with Oni. Instead, it displays default colours (not to be confused with the Nord theme).

**Expected behavior:**

I would expect Oni to somewhat resemble what the theme looks like with standard nvim or vim in my terminal (Alacritty):

![A screenshot of the expected behaviour.](https://i.imgur.com/ufJaaOx.png)

**Actual behavior:**

![A screenshot of the actual behaviour.](https://i.imgur.com/zteRUAw.png)

I thought I would mention that you may have seen the Dracula theme being imported in my ~/.vimrc. Yes, this theme does work correctly in Oni for me.

**Steps to reproduce:**

1. Download and install the aforementioned wpgtk.vim theme; I used vim-plug to do this.
2. Set the theme within your ~/.vimrc (or nvim config) with `colorscheme wpgtk`.
3. Load `init.vim` with Oni.
4. In Oni config, set "ui.colorscheme" to "wpgtk".

**Comment by badosu** [comment]
Hello @lachlantula, please take a look at https://github.com/onivim/oni/wiki/How-To:-Minimal-Oni-Configuration, in particular the `ui.colorscheme` section.

If that does not fix your issue, please reopen.

**Comment by lachlantula** [comment]
Unfortunately, this did not resolve my issue (as you can see, I'm also having some troubles with a ligature version of Operator Mono, but that's an issue for another day after I've done more testing).

![2018-12-29-170438_1920x1056_scrot](https://user-images.githubusercontent.com/12870244/50534105-d72e3480-0b8b-11e9-876f-7c1b8bcea372.png)

My `init.vim` reads as follows:

```vim
" Set Oni settings.

set nocompatible              " be iMproved, required
filetype off                  " required

set number
set noswapfile
set smartcase

" Enable GUI mouse behavior
set mouse=a

" If using Oni's externalized statusline, hide vim's native statusline, 
set noshowmode
set noruler
set laststatus=0
set noshowcmd

" Load ~/.vimrc.

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

My ~/.vimrc:

```
"   /\/|   __       _                       
"  |/\/   / /      (_)                      
"        / /__   __ _  _ __ ___   _ __  ___ 
"       / / \ \ / /| || '_ ` _ \ | '__|/ __|
"      / / _ \ V / | || | | | | || |  | (__ 
"     /_/ (_) \_/  |_||_| |_| |_||_|   \___|
"
"     ~/.vimrc by Lachlan Shoesmith (lachlantula).
"     Last updated: 27/12/18.

syntax on

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'posva/vim-vue'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'mattn/emmet-vim'
Plug 'rstacruz/vim-closer'
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/goyo.vim'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'deviantfero/wpgtk.vim'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Set theme.

colorscheme wpgtk 

" Make Vim read .md files as Markdown (.markdown) files.

au BufNewFile,BufFilePre,BufRead *.md set

" Change the cursor to my personal terminal one.
set guicursor=a:ver20-blinkon1

" Open a file tree with Ctrl+T.

map <C-T> :NERDTreeToggle<CR>

" Display relative line numbers

set number relativenumber

" Indentation

set expandtab
set shiftwidth=2
set autoindent
set smartindent
set tabstop=2
set softtabstop=2
```

**Comment by garetmckinley** [comment]
I found another theme that refuses to work in oni: https://github.com/arzg/vim-colors-xcode

colorscheme works perfect in standalone vim, but loads blank theme (same theme that loads when you have a misspelled/invalid colorscheme in the settings). The more themes we find that are broken, the better chance we can find a common link that could be breaking it.
