### ISSUE TITLE
A basic setup for oni-language-csharp

### ISSUE THREAD

**Issue by Zundrium** [onivim/oni#2701]
**Oni Version:0.3.6**
**Operating System: Windows 10 x64**

**Issue: Showing 'no language server registered' after installing the oni-language-csharp plugin.**

**Expected behavior: auto-complete working**

**Actual behavior: 'no language server registered' shown in the developer tools**

**Steps to reproduce: Install Oni, clone the csharp repo to `~/.oni/plugins`, npm install, restart oni as administrator**

I'm guessing I need to manually register the language server, but I've never seen where and how this can be done, could someone help me please?

**Comment by TalAmuyal** [comment]
Hi, sorry for the late reply!

Took a look at the default configuration.
As far as I can tell, for C# there is a grammar configuration but none for LSP.

You can look at [the C configuration](https://github.com/onivim/oni/blob/master/browser/src/Services/Configuration/DefaultConfiguration.ts#L199) and add one for C#.

Also, make sure that the C# LSP command is globally accessible (try to run it from your shell).

Aside from that, someone from the Discord channel might have already done so and can copy-paste a snippet for you.

When you succeed, feel free to post a PR that adds it to the default configs :)

**Comment by Zundrium** [comment]
Hey, Thanks for a reply none the less! 

As far as I can tell, you don't install global commands using `npm install`, which is the way the c# plugin is installed. 

Other than that I think I found my way using omnisharp-vim and nvim-qt. I'm kind of demotivated fixing this because the main developer of this project is going for a new version even though this version is half done. I know it's an experiment but still I'd rather use something stable and I'm already having lots of issues with the omni-completion crashing in multiple versions for example. 

I hope Oni v2 will get the attention it deserves!

**Comment by TalAmuyal** [comment]
Best of luck :)
