### ISSUE TITLE
[Question] Why oni2 ?  Why it needs to rewrite everything from scratch ? 

### ISSUE THREAD

**Issue by v3ss0n** [onivim/oni#2716]
I can't understand the direction Oni is going.
Rewriting whole editor from scratch with OCaml will be very very costly and it is not cross platform. 
Why Oni need to be rewrite everything from scratch with a programming language that used by very few people .

**Comment by Akin909** [comment]
@v3ss0n the best explanation is here -> https://github.com/onivim/oni2/blob/master/docs/MOTIVATION.md

A couple of things to note, v2 will be *cross-platform*, the *costliness* of v2 is weighed up against Oni's goal to a __lightning fast, performant__ editor.

Also its actually going to be written in [reasonml](https://reasonml.github.io) which is actually a syntax on top of ocaml that is *very* similar to javascript

hope that helps answer your questions

NOTE: @bryphe think we might need to surface the motivation doc better either here as a link or in the v2 repo (id suggest here as its where there is the most traffic)
