### ISSUE TITLE
Disable Oni autocomplete contextMenu?

### ISSUE THREAD

**Issue by cj** [onivim/oni#2720]
Is it possible to disable/remove the Oni autocomplete context menu?  i.e. tabs has a 'native' option to use vim's tabs instead of Oni's https://github.com/onivim/oni/wiki/Features#tabs.  Is that possible with the autocomplete context menu?  If there is no hidden option, would you be able to point me in the right direction to disable it in the source code?

Cheers!

**Comment by CrossR** [comment]
It sounds like you want `editor.completions.mode` from https://github.com/onivim/oni/wiki/Configuration#editor?

Though its been a while since I've tested that options, so I'm not 100%.

**Comment by cj** [comment]
@CrossR Thanks for the response -- It must be broken as I tried that option before with no luck, and I just tried it again; it still uses the Oni one, no matter what I set it as.

**Comment by CrossR** [comment]
Hm, setting to `    "editor.completions.mode": "native",` for me seems to work, at least after I restarted Oni (since the externalised menu is done via a neovim flag, we have to restart Oni for it. Technically it can be updated on the fly, but Oni hasn't implemented that yet.).

The easiest way to make sure Oni has fully restarted is via Cmd/Ctrl-shift-P, reload Oni.

**Comment by cj** [comment]
@CrossR I tried restarting Oni etc.... but it still uses Oni and not native vim:

![image 2019-02-10 at 4 07 23 pm](https://user-images.githubusercontent.com/1819/52540341-197f8f80-2d4e-11e9-8622-0d7897fdd72b.png)

**Comment by cj** [comment]
I'm running `v0.3.9`

**Comment by CrossR** [comment]
I have a feeling Oni's completion loading may be fairly stupid, so the fact you have a space at the end of the config option may be confusing it, ie `mode "` vs `mode"`.

**Comment by cj** [comment]
@CrossR ha, I knew you would mention that 😄  the space wasn't meant to be there, I actually updated the screen shot.

**Comment by cj** [comment]
@CrossR here's the output from the developer logs if that helps.... https://gist.github.com/cj/747841840c3e44189603a0b9730bb6fc

**Comment by cj** [comment]
@CrossR So it looks like I found the issue, removing `"editor.renderer": "webgl"` made it use the native context menu!  The issue now is, I need webql mode so that my nerd tree webdev icons display properly https://github.com/onivim/oni/issues/2299#issuecomment-396262406.

`"editor.renderer": "canvas"`:

![image 2019-02-10 at 4 22 28 pm](https://user-images.githubusercontent.com/1819/52540534-1a192580-2d50-11e9-8cf8-debe46907f87.png)

`"editor.renderer": "webgl"`:

![image 2019-02-10 at 4 23 50 pm](https://user-images.githubusercontent.com/1819/52540550-4a60c400-2d50-11e9-962b-aa6e9f72d62d.png)

**Comment by cj** [comment]
So it now seems to be working with `webgl`, once I removed the option, restarted again; it used native context and then I set `"editor.renderer": "webgl"` back, restarted and it appears to all work the way it should now.  I'm going to close this for now, I'll re-open it if it stops working.

Thank you for helping!
