### ISSUE TITLE
oni is loading somehow around 6 seconds in the best case

### ISSUE THREAD

**Issue by iamkarlson** [onivim/oni#2721]
**Oni Version:** 0.3.9
**Neovim Version (Linux only):**
**Operating System:** Windows

**Issue:** Loading time takes at least 6 seconds in general

**Expected behavior:** Oni is loaded less then 1s.

**Actual behavior:** Oni is loaded longer then 6s.

**Steps to reproduce:** Open oni

**Comment by CrossR** [comment]
There is certainly some things we can do to speed up the performance of startup, both to actually make it load faster by deferring some things, and by having some UI load before others so it seems faster.

That said, there is also a rewrite of Oni linked in the README: https://github.com/onivim/oni2.
This is written in [Reason](https://reasonml.github.io/) on top of [revery](https://github.com/revery-ui/revery), which is a platform for building native, high-performance tools (also written by a lot of the Oni devs!).

As great as electron has been for speed of development and lots of cool features, its also very heavy to carry around a full browser essentially, especially when a user may not ever benefit from it. Using `revery`, we will be able to get much much better performance.

>Revery is kind of like super-fast, native Electron - with bundled React-like/Redux-like libraries and a fast build system - all ready to go!
>
>Revery is built with reasonml, which is a javascript-like syntax on top of OCaml This means that the language is accessible to JS developers.
>
>Your apps are compiled to native code with the Reason / OCaml toolchain - with **instant startup** and **performance comparable to native C code**. Revery also features GPU-accelerated rendering. The compiler itself is fast, too!

The goals of Oni2 are outlined in its readme, but a key part it is speed/performance:

> The goal of this project is to build an editor that doesn't exist today - **the speed of a native code editor like Sublime**, the power of modal editing, and the rich tooling that comes with a lighweight editor like VSCode.

(Emphasis mine)

Hopefully that at least gives you some hope that we are working on making the performance in Oni much better!

**Comment by iamkarlson** [comment]
Yeah, it left me some hope that eventually, I'll switch to *nix based system to get builds of alpha versions earlier.
