### ISSUE TITLE
Oni / dein / git issue on Windows 7 with Mingw

### ISSUE THREAD

**Issue by kheaactua** [onivim/oni#2737]
**Oni Version:** v0.3.9

**Operating System:** Windows 7

**Issue:** Cannot install Dein packages due to Windows Git error.  At first I thought this was a Dein issue so I [posted the issue there](https://github.com/Shougo/dein.vim/issues/332), it contains screen shots and error logs.

**Expected behavior:** To install packages

**Actual behavior:** Fails while looking for commands such as `basename`

```
[dein] Cloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...Cloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...Cloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...Cloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...Cloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...Cloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...
[dein] C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: basename: command not foundCloning into 'C:/Users/mrussell/dotfiles/bundles/dein/repos/github.com/tpope/vim-fugitive'...
```

**Steps to reproduce:**

Attempt to use the `vimrc`
```vim
set runtimepath^=C:\Users\mrussell\dotfiles\bundles\dein\repos\github.com\Shougo\dein.vim
call dein#begin(expand('~/dotfiles/bundles/dein/'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim', {'build' : 'make'})

call dein#add('tpope/vim-fugitive')

call dein#end()
if dein#check_install()
    call dein#install()
endif
```

**Comment by TalAmuyal** [comment]
Hi, I guess that `sed` and `basename` are not available globally.
Does it work in plain cmd & PowerShell?

**Comment by kheaactua** [comment]
Umm, I haven't tried.  I don't have vim installed locally.. Can I run Oni's neovim independently to check?

**Comment by TalAmuyal** [comment]
I think you can, but I don't know how.
Mayber @bryphe or @CrossR know where the exe is located.
Also, you can ask on the Discord channel (more people read the messages there, I think).

**Comment by kheaactua** [comment]
oh, nice., wasn't aware of that, what's the URL to the Discord channel?

And, `basename` exists on my computer, sort of, but in the msys2/mingw environments (`c:\msys64\usr\bin\basename.exe`, and `c:\Program Files\Git\usr\bin\basename.exe`, I even have a `C:\Program Files\Git\mingw64\libexec\git-core` but that doesn't have a `basename.exe` in it), which I installed weeks before Oni.  While I assumed Oni would use msys2 stuff for git, I didn't think it's concern it self with anything I previously had installed on the computer.

**Comment by CrossR** [comment]
The neovim executable is stored in `C:\Program Files (x86)\Oni\resources\app\node_modules\oni-neovim-binaries\bin\Neovim\bin".

I've not really got any experience with using `mingw64` and Git, but I do know that plugin managers should work in Oni. I use one on Windows at least, but my Git is installed globally (ie directly in Program Files I think).

**Comment by kheaactua** [comment]
I haven't checked the Discord yet, but, so far I think I fixed some of my issues by modifying the PATH that Oni uses.  I did this by redirecting the path in the pinned start menu item to a `cmd` file I wrote:

```sh
C:\Windows\System32\cmd.exe /c set PATH=C:\Progra~1\Git\mingw64\libexec\git-core;C:\Progra~2\Oni && start C:\Progra~2\Oni\Oni.exe"
```

That seemed to have given access to all the missing base tools.

**Comment by TalAmuyal** [comment]
Glad it worked out
