### ISSUE TITLE
Build OSX version of Neovim as part of Oni

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#326]
Similiar to how VimR works, we should be building Neovim from source instead of including all the binaries.

For now, #325 is a quick-fix to check in the binaries to the enlistment, but we'll need a better solution long-term.

**Comment by extr0py** [comment]
As part of the build, we should be adding the `gui_oni` feature, such that `has("gui_oni")` returns `1`

**Comment by bryphe** [comment]
Since we now have OSX binaries bundled as part of `oni-neovim-binaries`, this is no longer necessary. We can still consider doing a manual build if there is a demand for it to include a `has("gui_oni")` variable.
