### ISSUE TITLE
Get rid of "Hit Enter To Continue"

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#38]
This is one of those things that are *terrible* *terrible* user experiences that the Vim community seems to not think is a big deal. It is a big deal to people who are expecting a modern editor experience. The goodness of vim should not come with terrible user experiences that are only present because terminals 30 years ago didn't offer better solutions. Does it sound like Oni is the right project to try to correct this? Based on your description, it sounds like it might be. One approach is to create a special plugin that always ensures the `cmdheight` is `5`, even if someone's vim config sets it to something smaller. This prevents that annoying message, but makes the command area far too large. Then, at render time you *artificially* render the command area as smaller, and detect any command output larger than one line. Then you have another solution for scanning the `:messages` log and deciding which messages warrant some kind of a modal dialog for errors, or perhaps something even [better](https://github.com/extr0py/oni/issues/39). Does NeoVim provide a better way for detecting errors (perhaps the new external UI protocol?)

**Comment by extr0py** [comment]
> The goodness of vim should not come with terrible user experiences that are only present because terminals 30 years ago didn't offer better solutions.

Yes, you hit the nail on the head here - this is really one of the implicit goals I had in mind, but didn't call out. This is an important goal of the project, so I added it in the README.

It would be great to improve that 'Hit enter to continue' experience. Need to check the msgpack-rpc API and see if there is a way today to get errors. That extended UI PR (https://github.com/neovim/neovim/pull/5686) seems like it will help here, by decoupling additional parts of the UI to allow us to choose how to render them.

In terms of errors specifically, there is definitely a problem with errors on startup not being reported by neovim to external UIs: https://github.com/neovim/neovim/issues/3901. Past startup, need to check and see if the msgpack-RPC API supports an event/notification for this. If there is a notification in parallel, we could potentially start the UI for this and implicit press enter for the user, until the external UI work is complete.

**Comment by CrossR** [comment]
I think this is an issue I occasionally run in to.

I've got some Latex plugins that work fine on Linux, but they probably aren't defined properly on Windows, so if I open a .tex file on Windows Oni loads to a black screen. I hit enter and carry on like normal, using :messages if I think the message should be checked.

Not an issue for me yet, and it looks like the linked issues are still not merged, but just thought I should add on some support to this.
