### ISSUE TITLE
Facing issues with Youcompleteme

### ISSUE THREAD

**Issue by Waqar144** [onivim/oni#414]
**YouCompleteMe** works fine except for a small issue I am facing. If a completion pops up it won't until close until I select an option. So even if I have typed the word completely, the completion popup won't go away until 
- I press `enter` to select an option
- I type `->`
-  Go back to **Normal Mode**

Other than this it sometimes pops up automatically.

--------------------------------------------------------------------------------------

**P.S:** I am running Linux and using the provided binary.

**Comment by extr0py** [comment]
Hi @Waqar144 ,

Thanks for the issue report! A couple questions:
- Would it be possible to get a screenshot or a gif/video if the repro? I'm wondering in particular how many entries are being shown in the completion dialog. Is it only a single item?
- Can you please run `:set completeopt` in Oni and let me know what is returned? There could be a conflicting setting there.

Thanks!
Bryan

**Comment by Waqar144** [comment]
Gif:
![Imgur](http://i.imgur.com/S9Auu0l.gif)

`:set completeopt` returns `menuone`

**How many entries are shown?**
The num of max entries are 10. It can be less but I haven't seen more. This is opposed to normal Vim/Nvim behavior.

One thing you may notice is that **YCM** isn't triggered until you press `Ctrl+Space` [For `php`] in NVim. Here it's being triggered automatically.

**Comment by GeorgeTG** [comment]
I have the same issue with youcomplete me.
I installed the regular way with install.py
When suggestions are displayed, typing the whole word or pressing enter
wont close the window.
So if i try to press Enter to get a new line, the keyword is inserted again.
I have to manually press Esc for the window to close and then press enter to get a new line.
I have `let g:ycm_autoclose_preview_window_after_completion=1`
in my init.vim file, but it seems it is ignored.

**Comment by bryphe** [comment]
PR #1022 by @CrossR may help here, once it's in - by setting the `editor.completions.mode` to `'native'`

**Comment by bryphe** [comment]
I'll close this out as much has changed in the completions framework since the initial issue - the `native` setting for `editor.completions.mode` should address this. But feel free to reopen or log a new issue if there are still challenges here!
