### ISSUE TITLE
Lowering the Bar: Gamify & Improve Vimtutor

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#430]
This came about from discussion with @JosephFerano in the gitter channel. The idea is to have an improved vimtutor experience - a way to teach users modal editing in a fun, paced environment.

It is generally accepted that the way to start learning vim is to open up vimtutor and spend 45 minutes or so getting a feel for the keys, but having an actual game and measured objectives / achievements around it would make it much more fun and enjoyable for new users to pick up Oni. The existence of other experiences like https://vim-adventures.com/ show that there is a demand for this.

This would fit in well with Oni's goal of lowering the bar to modal editing, and help funnel new users that are curious about modal editing to Oni.

**Comment by CrossR** [comment]
@bryphe with the recent tutor bits we've added I think this issue can be closed?
We've still got other tutorials to make, but it looks like specific issues are raised for them each time.

**Comment by bryphe** [comment]
@CrossR , sounds good to me! Agreed, any other issues we can track separately 👍
