### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#451]
Having native git (and later, more general source control) integration capabilities is very valuable.

Initially, I wanted to start by having a git branch in Oni's statusline - so this issue is split out from #201 which is the general Oni statusline implementation.

After the status line, there are several opportunities to explore - a `git blame` overlay is specifically called out in #362 

Atom seems to have some nice functionality around git integration as well: http://blog.atom.io/2014/03/13/git-integration.html

Here some specific capabilities I'd like to see:
- Git branch info in statusline
- Git blame overlay that can be called up
- Quick and easy diffs
- Quick and easy exploration of history - I remember seeing a post in hackernews / reddit where the git history could be scrolled with the mouse wheel. That was pretty cool.
- Merge conflict

I use only the basic functionality of [vim-fugitive](https://github.com/tpope/vim-fugitive), so exploring that would be helpful. I also have heard great things about [Magit](https://magit.vc/) for Emacs, so I'd like to explore that too for inspiration.

**Comment by v3ss0n** [comment]
i wonder if it is best for 0ni to fork and base upon VSCode/Atom's platform. They have done all the Git / Mercurial integration works can you guys can just tap into it.
It will save alot of work and 0ni's  focuse will mainly only be to build perfect neovim-on-electron app. 
Right now 0ni's line rendering is alot slower than those editors.

**Comment by jonaspm** [comment]
How about making it a plugin?

**Comment by v3ss0n** [comment]
@jonaspm , good news on VSCode , VSCodeVim developers are switching to nvim. the branch have all ex commands available now . 
But still , tight total integration still needs a dedicated vim editor , which the way 0ni doing is awesome.
But i really think , reusing already avaliable editors is a good idea , they have full plugin systems , themeing , extensions/package management ,  and most important of all , VSCode and Atom upcoming rendering system are very high performance.

**Comment by cyansprite** [comment]
I don't think it's necessary to integrate with atom or vs code, you get some nice features but you also take all of their bugs with you and you are limited to their preferences and philosophy.

**Comment by bryphe** [comment]
Realized this is more thoroughly tracked now in #2110, so I'll close this out in lieu of that one-
