### ISSUE TITLE
Autocompletion: Reduce flicker

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#463]
The completion menu flickers as typing occurs:

![borderless](https://cloud.githubusercontent.com/assets/13532591/26358344/1c2db862-3f87-11e7-8911-452e6ac6f5ba.gif)

It looks like this is because we are closing and reopening the completion menu for each keypress, likely due to some handling in the redux store of the cursor change event. This definitely hurts the fit & finish of Oni and the completion scenario.

**Comment by CrossR** [comment]
I'm just going through the 0.3 milestone at the mo and looking at issues.
This seems to be a lot better now, is this still an issue?

**Comment by bryphe** [comment]
Yes, thanks! This should be addressed by the latest completion changes - we're re-querying and re-rendering a lot less frequently now. I'll close this out, we can track in a new issue if we see any more flickering. I'll close this out - thanks for going through the 0.3 issues!
