### ISSUE TITLE
Feature request: Open a file by dragging the file to the panel

### ISSUE THREAD

**Issue by gynet** [onivim/oni#471]
It would be nice that ONI support opening a file by dragging the file over to the panel

**Comment by keforbes** [comment]
Seems simple enough.  I've created pull request #472 to do it.

**Comment by keforbes** [comment]
Hey @gynet, this feature has been merged in.  You could build from source (`npm run build`) or download the latest v0.2.5-rc to give it a try.  Thanks!

**Comment by mjedmonds** [comment]
Hi all, I am suggesting this be reopened per the discussion at #472. This issue was closed but the feature has now disappeared.

**Comment by CrossR** [comment]
Just a note @mjedmonds that this should have been fixed now again over in #1882.
