### ISSUE TITLE
Live Evaluation Enhancements

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#475]
Live evaluation hasn't received a lot of love currently, in favor of some of the other LSP features. But this is something that we should re-invest in, especially in terms of generalizing to other languages.

Being able to tighten up that feedback loop of writing code -> seeing results is huge for productivity, which is why technology like live reloading and hot reloading is so useful.

The challenge of making this more generally useful is that, often in some languages, there are a huge amount of dependencies that need to be scaffolded just to run a single function. However, perhaps we could isolate this to pure functions that don't have side effects.

A couple of things to revisit:
- What should the syntax / entry point for live evaluation be? The entry point right now is awkward.
- How to extend to other languages? How should the plugin API be updated? Could this be something added to the language server protocol?

I'd like to implement a canonical example in JavaScript/TypeScript, or perhaps a functional language like OCaml, and then look at extending it from there.

There are some enhancements I'd also like to see:
- Better UI for evaluating results
- Ability to specify arguments via named parameters
- Performance information - this would be helpful for lightweight benchmarks

**Comment by extr0py** [comment]
I'm thinking for compile-to-JS languages, it might make sense to have an export like `live` that is available. This could be set as a configuration value per-language. There might be additional configuration needed, like the source/compilation path, for resolving imports.

**Comment by extr0py** [comment]
Also, the live eval functionality should not be responsible for managing compilation - it should be using an existing pipeline.

**Comment by bryphe** [comment]
For now, I'm planning on having this be superseded by #1349  - the preview is a more tractable and useful short-term goal.
