### ISSUE TITLE
Feature - Snippets

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#55]
Snippet support is huge in saving people typing. It's a prominent feature in every major text editor, for good reason.

UltiSnips is the de-facto standard in the VIM community, and ideally we would reuse that. The problem is that it requires Python support and at least Neovim binaries aren't built with Python on Windows.

_Python interpolation_ is a really cool feature UltiSnips has - in the spirit of this project, with a JavaScript-driven plugin API, it would make sense to introduce javascript interpolation. There are some potentially really neat integrations there - like showing the current date in specific formats, showing the lines in a buffer, expanding github issues by ID in a TODO comment, etc

So for those reasons, I believe it might make sense to create a UI-driven shell approach to snippets.

We would need to recognize multiple snippets formats:
- Existing Ultisnips formats
- TextMate snippet syntax (which would give us (VSCode Snippet support)[https://github.com/neovim/neovim/pull/5686]

**Comment by bryphe** [comment]
This is in the latest build now! Will use new issues to track remaining work.

**Comment by badosu** [comment]
@bryphe What are the snippets formats supported? Can it be disabled?

**Comment by bryphe** [comment]
> What are the snippet formats supported?

Yes, I need to document this - it's the same snippet format as VSCode (which is basically the same as TextMate): https://code.visualstudio.com/docs/editor/userdefinedsnippets

> Can it be disabled?

There isn't a configuration setting at the moment - it might make sense to add one. The only entry point for it is Oni's completion menu:
![image](https://user-images.githubusercontent.com/13532591/37055475-ac3de7f6-2136-11e8-8791-9989ab21ae1e.png)

So it gets implicitly disabled if that is off. Let me know if it'll interfere with the native config we have: https://github.com/onivim/oni/wiki/How-To:-Make-Oni-closer-to-bare-Vim-experience

**Comment by badosu** [comment]
I have the completion menu open, but I'd like to not have the snippets enabled (for stability and avoiding distractions).

WDYT of opening an issue for providing an option to disable snippets?

**Comment by bryphe** [comment]
> WDYT of opening an issue for providing an option to disable snippets?

Sounds great! Makes sense to have it - easy fix too 👍

**Comment by badosu** [comment]
@bryphe https://github.com/onivim/oni/issues/1719

**Comment by bryphe** [comment]
Cheers, thanks @badosu ! I should get to it today
