### ISSUE TITLE
Reduce installation size and footprint

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#560]
- Includes work for #350, which will decrease size / footprint on disk. Will be easier to fix that after the full set of fixes.

There are several other places we need to optimize the package size, though:
- Are all the node_modules needed? Are they being pruned correctly? Should they be flattened? This is a pretty huge culprit, at ~150MB.
- Remove unbuilt sources from package
- Does all of font awesome need to be included?
- Some of the images can be excluded

Long term, some packages should not be included by default - like `oni-plugin-csharp`. This is a contributing factor to the size of the `node_modules`. This will be easier once there is a plugin story for Oni.

I would like the install size to be on par with some of the other Electron editors (~50 MB), and the footprint ideally to be under 100MB.

**Comment by extr0py** [comment]
`lodash` seems pretty huge too - we should only include the subset needed, and remove it from `node_modules` entirely - it's getting double-packed, both in `node_modules` and in the webpack bundle.

**Comment by bryphe** [comment]
The initial set of pruning is done - we should track further items individually.
