### ISSUE TITLE
Open Folder: Persist opened folder on launch

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#571]
If the user has opened a folder, and then launches Oni again from an install directory, we should persist that and default to opening from their previous folder.

This fits in with persisting other editor settings - like window size (#452), open files, etc.

**Comment by cyansprite** [comment]
This should be a setting...
I don't like this in vscode/sublime I hated whenever I closed it it would reopen what I was doing last.

**Comment by timhughes** [comment]
Just making the "Open Folder" menu item start from the current open folder would be good.
