### ISSUE TITLE
Synchronize title bar color with tabbar background color

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#63]
This is probably low priority because there's a lot more important things that need to be done to make the UI smooth, but I'm just making this task because someone might already know how to do this, and might thing it's fun.

<img width="742" alt="screen shot 2016-12-08 at 2 36 06 pm" src="https://cloud.githubusercontent.com/assets/977348/21030606/578f0632-bd54-11e6-859d-5d120add41b2.png">

I think a good default would be to synchronize the color of the title with the vim colorscheme's tabbar background color. Then of course, as we've discussed elsewhere, colorschemes/themes could specify special support for coloring the title bar.

**Comment by extr0py** [comment]
We might be able to use the work done in this electron PR:
https://github.com/electron/electron/pull/2776

Use the 'hidden' or 'hidden-insert' option for the titlebar - will need to try it out
