### ISSUE TITLE
Preference Tab won't close

### ISSUE THREAD

**Issue by Syenta** [onivim/oni#641]
There appears to be an issue with the Preferences tab. When clicking on the X to close it nothing happens.

I have tried opening a few tabs to see if it had something to do with it being the only open tab but it makes no difference how many tabs are open the Preference tab still won't close.

Hope it helps

**Comment by lukeberry99** [comment]
The first time you open the Oni preferences it will create a new buffer and set the lines to be the default config, at this point it is an unsaved file and exists entirely in memory. You will notice that the 'x' at the top of the screen is in fact a circle, indicating that there are unsaved changes. If you save the file you will then be able to press the 'x' and the file will close, as expected.

Perhaps there should be a confirmation dialog when attempting to close a file with unsaved changes, in the same vein as `:q!`, just more visual.

**Comment by CrossR** [comment]
There is also #264 in a similar vein to this, which looks to be waiting on an update to neovim-core. Though since we know if the buffer is or isn't modified, we could implement an oni version for now.

**Comment by bryphe** [comment]
This should be fixed now that we use `set hidden` by default. Feel free to reopen if that isn't the case.
