### ISSUE TITLE
Enable autocompletion and quickinfo for config.js

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#685]
Editing the configuration is non-trivial because it involves some coding, as well as domain knowledge on the Oni API and what it providers.

We should make it easier to explore this interface via quick info and completion. At the minimum, we should hook up `Oni.d.ts` so that it gets picked up and resolves. We may have to special case this and bake-in some optimizations, but it is already asking a lot for users to configure their editor through code - this process should be streamlined as much as possible.

**Comment by extr0py** [comment]
We need to make it very easy to diagnose and fix errors here too (and improve robustness)
