### ISSUE TITLE
Question: are per-project lint configs possible?

### ISSUE THREAD

**Issue by someguynamedmatt** [onivim/oni#686]
I think the title is self-explanatory, different projects may have different linting rules. Does Oni handle this currently?

**Comment by extr0py** [comment]
Definitely - out of the box, the typescript language server is loaded by default to handle typescript / javascript (errors mostly). and then there is also a tslint plugin:
https://github.com/extr0py/oni-plugin-tslint

Both of these strategies work by looking for a `tsconfig.json` (typescript) or a `tslint.json` upwards in the directory tree from the open file. So it is basically configurable by these settings.

There was some discussion in #659 about eslint / flow, and I'd expect these to work the same way (I know eslint is configured by an `.eslintrc` file).

There is also some (undocumented) functionality on per-project configuration loading - where you can provide a `config.js` for a project directory (in `.oni`) and override settings, too. I'd like to integrate this more deeply with `Open Folder` prior to documenting it, but it's on-deck.

Is there a particular linting tool you are using? Or a case not working the way you'd expect?

**Comment by someguynamedmatt** [comment]
@extr0py awesome! No, I'm still figuring all of Oni's capabilities out, tbh.

**Comment by bryphe** [comment]
I think this is tracked / duplicated by #1259 . Feel free to reopen if there is something not captured there, though!
