### ISSUE TITLE
Use `nvim_call_atomic` for requests

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#702]
There are several cases we make multiple requests to Neovim in a row:
- Sizing up the current windows in the app
- In the fix for #649, setting multiple values at once
- Getting buffer information

In all of these cases, it can be unnecessarily slow, because we send a request to neovim, wait for a response, send another one, etc. There are several cases where the input of one call does not rely on the output of previous, and as such, could be batched.

Neovim has a call specifically for this - `nvim_call_atomic` - which would help with this use case. This would improve latency / responsiveness for some cases in Oni (like sizing up the windows), since we would not incur the roundtrip tax for each individual request.

**Comment by extr0py** [comment]
It might be helpful on the session object to have an abstraction like `startBatch` and `endBatch`

**Comment by Bretley** [comment]
I haven't stayed too up to date on the codebase since classes started, but what files specifically would you suggest need edited for this?

**Comment by bryphe** [comment]
No worries, there's a lot in flux at the moment 😄 Hope classes are off to a good start!

I started tagging a few places with `// TODO: #702` - pretty much any place where we fire off multiple requests to Neovim. Here's a couple examples:
https://github.com/bryphe/oni/blob/1da1104f6a6b5cd744a658dedffbce2265c56fd9/browser/src/neovim/NeovimInstance.ts#L277
https://github.com/bryphe/oni/blob/1da1104f6a6b5cd744a658dedffbce2265c56fd9/browser/src/neovim/NeovimWindowManager.ts#L29

It'd be useful to think of how the API could look for this, too - ideally we could abstract the fact that we are batching, or make it simple, like:
```
this._neovimInstance.startAtomicBatch(...)
...make a bunch of api calls
this._neovimInstance.endAtomicBatch(...)
```

It might make sense to have that be at a lower level though (against the actual `Session` object), have to think about it some more..

**Comment by bryphe** [comment]
This is too vague to be actionable IMO - I'll close this out in favor of identifying specific bottlenecks we should investigate
