### ISSUE TITLE
Scrolling with the mouse does not update the scrollbar

### ISSUE THREAD

**Issue by badosu** [onivim/oni#745]
See the following 3 images on each scroll step of the mouse:

### Initial State

![screenshot from 2017-10-03 00-22-39](https://user-images.githubusercontent.com/347552/31108741-75bdd0b2-a7d1-11e7-8896-6080f600cf3e.png)

### First scroll step

The screen scrolls but the scrollbar is not updated

![screenshot from 2017-10-03 00-22-50](https://user-images.githubusercontent.com/347552/31108740-75b2a700-a7d1-11e7-8a9c-daeaafd9b226.png)

### Second scroll step

After the cursor reaches the bottom of the screen, as it changes position then the refresh is done on the scrollbar and it inverts sudenly

![screenshot from 2017-10-03 00-25-55](https://user-images.githubusercontent.com/347552/31108739-75672f50-a7d1-11e7-8ab7-40ce3ea2941d.png)

**Comment by bryphe** [comment]
Seems related to #543 (different manifestation) - when only the cursor moves, we're not updating the viewport information for some reason.

**Comment by bryphe** [comment]
Looks like this is addressed now (via the fix for #543). Still some scrollbar issues being tracked in #1007 , though. I'll close this, but feel free to reopen if this is still manifesting.
