### ISSUE TITLE
Golang langserver not starting

### ISSUE THREAD

**Issue by josemarluedke** [onivim/oni#750]
The golang language server is not starting (langserver-go)

![screen shot 2017-10-03 at 9 11 52 am](https://user-images.githubusercontent.com/230476/31135833-1b463de6-a81b-11e7-85f3-1de78b741be2.png)

It might be related to changes in here: https://github.com/sourcegraph/go-langserver/pull/198

**Comment by bryphe** [comment]
Thanks for the screenshot, @josemarluedke , that helps a lot! I'll take a look at this with the language service work I'm starting shortly. It does look like there is some sort of escaping issue with the `file:///` rootPath.

**Comment by bryphe** [comment]
I believe this should be fixed now, along with #1178 on OSX, via PR #1185 . Let me know if there is still an issue here, though!
