### ISSUE TITLE
Expanding menu on command gets glitched

### ISSUE THREAD

**Issue by badosu** [onivim/oni#775]
Using Oni v0.2.12, never had this issue previously.

## How to reproduce

Start typing a command:

![screenshot from 2017-10-10 00-32-20](https://user-images.githubusercontent.com/347552/31368683-b63986c0-ad55-11e7-8eaa-4826d5809e1c.png)

Type `<C-d>` and then the screen scrolls down and the wildmenu gets glitched:

![screenshot from 2017-10-10 00-32-35](https://user-images.githubusercontent.com/347552/31368698-c74efe7c-ad55-11e7-9601-d07a24277a3c.png)

**Comment by bryphe** [comment]
Thanks for logging the issue, @badosu ! 

Unfortunately I can't repro this - I tried on Windows and my Ubuntu machine but am not seeing this. It looks like it could be potentially an `nvim` issue (depends on what it is sending us back). Are you running Oni against the nightly build?

Also, are you seeing the scroll happen when you press the `<tab>` key? Does it reproduce consistently?

**Comment by badosu** [comment]
@bryphe  I just noticed now that `<C-v>` (without the backticks) was not being displayed, I am sorry.

**Comment by badosu** [comment]
@bryphe Let me know if there's any clarification I can add to disambiguate this issue.

**Comment by badosu** [comment]
@bryphe The glitching issue is resolved, there's still a minor issue with the output of each command getting stacked on top of each other but it's much better now.
