### ISSUE TITLE
Overriding buffer when using LSP's go-to-definition

### ISSUE THREAD

**Issue by TalAmuyal** [onivim/oni#778]
Tried with `master` (`c0cd0e4c3e65c4f7d4ce2ed406f39c384056f3a3`) and `clangd` as the server.

# Steps

1. Open Oni: `> oni`
2. Create a new buffer w/o a file in the file system`:e new_file.cpp`
3. Fill with a bit of code:
```
static int ab = 0;
void bc() { ++ab; }
```
4. Move the cursor to the `ab` usage inside of `bc`: `2ggfa`
5. Invoke "go to definition" (`<F4>` for me)

# Issue

'clangd' instructs Oni that `ab` is defined at `./new_file.cpp`, so the file is opened form the file system.

If the file doesn't exist, the buffer is replaced by an empty one.
If we saved it in some point, but not right before invoking "go to definition", then an old version of the file is loaded to the buffer.

For now I'm just reporting it, might try to have a go at it later on.

**Comment by bryphe** [comment]
Thanks for logging the issue, @TalAmuyal ! I think this is a general issue with the language integration (not specific to `clangd` ) - I believe I hit this occasionally with TypeScript as well.

**Comment by bryphe** [comment]
Looks like this is fixed in the latest version of Oni. 

Closing, but feel free to reopen if you're still seeing this!
