### ISSUE TITLE
The application exit directly

### ISSUE THREAD

**Issue by jay763190097** [onivim/oni#801]
Point something on the menu bar, and then application exit directly , and then open the application each time are directly out, uninstall are the same. I do not know where there is a hidden file.
in windows platform.

**Comment by bryphe** [comment]
Hi @jay763190097 ,

Thanks for trying out Oni, sorry you're hitting that issue. Unfortunately I'm not able to repro as described - which option did you choose in the menu bar?

Oni does have a cache located in `C:\users\<your user\AppData\Roaming\oni` - you could try deleting that and see if that addresses the issue.

**Comment by bryphe** [comment]
Hi @jay763190097 ,

Just wanted to follow up - did you try deleting your cache in the `%APPDATA%` folder?

**Comment by bryphe** [comment]
I'll close this out since there isn't anything new here, but feel free to reopen this @jay763190097 if you're still hitting this after clearing the `%APPDATA%` folder and using the latest version of Oni.
