### ISSUE TITLE
Weird keybinding of <M-e> on mac

### ISSUE THREAD

**Issue by MikaAK** [onivim/oni#816]
In my old config I use `<M-e>` to expand ultisnippets. However for some reason `<M-e>` does this weird behavior where in insert mode it takes the character before the cursor and moves it to the end of the line, I can't find a reference to `<D-e>` or `<M-e>` anywhere else asides for ultisnips expansion

**Comment by bryphe** [comment]
Weird, I'm not able to reproduce it (but I don't have Ultisnips installed at the moment). As you mentioned Oni doesn't bind `<m-e>` by default so it should just pass through to Neovim.

What do you have `oni.loadInitVim` set to? And is `oni.useDefaultConfig` set? I'm wondering if there could be conflict between Ultisnips and one of the default plugins.

**Comment by MikaAK** [comment]
I do not have defaults set and I am loading my init.vim I suppose I can do a better and test neovim itself to see if it's maybe a plugin or other config

**Comment by badosu** [comment]
@MikaAK Any update on this issue?
