### ISSUE TITLE
"Edit with Oni" menu item

### ISSUE THREAD

**Issue by topher96** [onivim/oni#820]
Vim on Windows installs an "Edit with Vim" right click menu I always found very useful as it was on the top level menu and applies to every filetype.  Could you add a similar menu for Oni?

**Comment by badosu** [comment]
I would just label this as specific to windows or mac if not available there, as the specification for the `.desktop` file we have for linux (on Arch at least) knows the MIME types oni can handle.

**Comment by CrossR** [comment]
I've submitted a PR for adding this for Windows.

A second point I realised is that we could potentially also have this work for Folders as well as files.
Then you could "open a folder" with Oni, and it would open oni with the current folder set to that one.

**Comment by keforbes** [comment]
This was resolved in #823, which has been merged in.  Closing issue.

**Comment by bryphe** [comment]
Thanks @keforbes !
