### ISSUE TITLE
Consider Open Collective

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#821]
Hi,

I was curious if you were considering Open Collective for funding. BountySource is great but its fees are higher (from what I can tell BountySource charges 10% fees, and Open Collective charges 5%). Open Collective seems to be gaining more popularity as a way to sponsor entire projects as opposed to sponsoring individual tasks/features.
(BountySource does have one advantage in that bounties don't receive a percentage fee until its withdrawn to cash, so you can re-bounty income to another project/task without paying any fees - that's useful in some cases but maybe not for general purpose project funding).

**Comment by bryphe** [comment]
Hi @jordwalke ,

Thanks for opening the issue, really appreciate you calling this out! 

Yes, I agree 100% - having an Open Collective for Oni makes a lot of sense. I'd like to make this a sustainable project and fundraising will be crucial to accomplish that.

I've started to research some fundraising options (and set up some better funnels, like a landing page, clarifying the roadmap, etc).  It seems like projects like Webpack have had tremendous success with Open Collective, and I like the transparency they provide in the platform - it's important for backers and sponsors to know where the money is going!

I really like BountySource's model too - it's unfortunate that it didn't quite catch on in the same way... being able to fund open source by contributing/voting with $$ for issues you want fixed seems like a cool approach to me. The advantage you call out, being able to transfer bounties without a fee, is important as I would like to contribute back to Neovim core - so  it makes sense to keep it around too.

I'm working on a website for Oni right now, and I'll expose a few options for funding there:
- Open Collective
- PayPal
- Bitcoin
- BountySource

I'm starting to look into the registration process for Open Collective. I'll keep this issue updated with progress (and post the website for feedback when it's ready 😄 )

**Comment by bryphe** [comment]
FYI, just a progress update - have a WIP site here: http://onivim.io/ A bunch of things to tidy up (and need to fix up the hero video) but it's a starting point.

I also started the process of onboarding with OpenCollective, but unfortunately hit opencollective/opencollective#555 - once that's set and I have it linked in our website, it'll be ready for launch 😄 

I mentioned this in the chat too, but I'm planning on moving this repo to the onivim organization: https://github.com/onivim

**Comment by jordwalke** [comment]
Great!

**Comment by keforbes** [comment]
I think everything @bryphe mentioned in his previous comment is now done.  Closing issue.
