### ISSUE TITLE
UI - Autocompletion: If the completed word is part of a larger word, the autocomplete dialog keeps popping up

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#83]
Repro:
1) Open up Oni in the Oni project directory
2) Press Ctrl-P and open `CanvasRenderer.ts`
3) Above `export class CanvasRenderer`, start typing: `_.last` and press enter

Expected: Autocompletion should be dismissed
Actual: Autocompletion keeps popping up, because it tries to suggest _lastIndexOf

![autocompletion bug](https://cloud.githubusercontent.com/assets/13532591/21076973/1db93cd2-bef0-11e6-8c98-4fc9cf93a1bc.gif)

**Comment by extr0py** [comment]
We should keep track of the last accepted suggestion / cursor position and not pop up the menu in that case

**Comment by bryphe** [comment]
This should be fixed now, but I still see one minor issue that is jarring - if you type out the word completely, the first enter gets swallowed. Need to see what's happening there..

**Comment by bryphe** [comment]
This was fixed by the autocompletion fixes in 0.2.15.
