### ISSUE TITLE
Completion menu and case interaction.

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#830]
I've noticed an "issue" with using both `ignorecase` and `smartcase` in my `init.vim`.
Both of these apply to the completion menu, as expected.

The problem is that in some cases Oni will sometimes expand out the word and then offer changes from there. This then causes an issue when certain selections are chosen as the index the completion is applied to is wrong.

Test case:

```
Main
max
Main_Function
max_function


```

Now, typing `M`  on a new line and hitting `<Ctrl - P>` works as expected, it offers both `Main` and `Main_Function`. 

Typing `m` on a new line causes some weird behaviour for me. After hitting `<Ctrl - P>`, the text will be expanded out into `ma`. Selecting either `max` or `max_function` works as expected, but selecting `Main`  or `Main_Function` results in `mMain` or `mMain_Function`.

I'm assuming that on hitting `<Ctrl - P>`, Oni  sees that "all" the results have `ma` at the start, expands to that and then resets the search index. This then causes issues when it tries to make the word `Main` out of `ma`.

The same action works as expected in nvim-qt, leading me to assume this is an Oni issue.
nvim-qt doesn't expand `m` to `ma` which is probably how it gets around this issue.

Despite maybe sounding a bit of a weird edge case, I hit this a decent amount daily, as I'll have say a `Bank` class and a `bank` object, and trying to expand into the class version leaves me with `bBank`.

**Comment by bryphe** [comment]
Thanks for the repro, @CrossR ! Yes, this seems to be a bug in how we figure out the `completion meet` - the logic we are using thinks the `m` is part of a different word, and appends `Main` after it.

I'm in the process of revising this in PR (#819) which basically guts and revises the completion logic. I'll test this scenario with the new code (I still need to wire up the Neovim completion events as well)

**Comment by CrossR** [comment]
Looks like some version of this is happening for the video on the onivim website.

**Comment by bryphe** [comment]
Ah ya, the bug in the video was fixed in this PR #845 (the base would be off-by-one so we'd complete in the wrong spot). I need to record a new video that doesn't have that bug 😄

I believe this scenario should work better now, at least for the Neovim popup completion (because we defer to neovim for the case handling in that scenario).

**Comment by bryphe** [comment]
This should be addressed by the fix for #845 and the previous completion work done in 0.2.15.

I'll close this for now, but let me know fi there is still a case that isn't working!
