### ISSUE TITLE
Font size in .oni/config.js requires "px" after the number

### ISSUE THREAD

**Issue by FredChores** [onivim/oni#837]
![screen shot 2017-10-28 at 4 25 06 pm](https://user-images.githubusercontent.com/13815851/32139058-aaded766-bbfc-11e7-9515-9be45295de05.jpg)

Only the default font size works.  Attempting to change it, even to a value identical to default, causes the font to change to something else and borks the rendering.  The cursor element seems to show the proper rendering underneath it, I think.  This is with the current head on a current build of osx, and also with the most recent release.  I don't know if it's using the packed nvim or the one on my system.

**Comment by CrossR** [comment]
Are you using "15" or "15px" as the font option?
If I miss out the "px" on the end I get something very similar to you.

I have noticed this before as well when not especially paying attention, and then with the messed up view it is awkward to swap back.

**Comment by FredChores** [comment]
That did it, thanks.  I'll leave this open since it's an improvement than can be made.

**Comment by CrossR** [comment]
The font config options could probably do with being improved in general.
I understand and quite like the JSON file for config changes, but I think there should be some other ways to interface with that config file as well.

Font could do with a menu option/bindable command that allows you to make it bigger and smaller, that auto updates the config option as this happens. I find myself quite often attempting to show people code and realising that I have size 12px font, and its easier to swap editor and zoom than jump into the config file and edit it there, and then go back and edit it again when I'm finished showing them.

I did have a quick look into adding that, but then I realised I don't think there is any way of saving back to the config file currently, so it seemed like something that should have a bit more thought than me just poking around and attempting to add it.

**Comment by TalAmuyal** [comment]
Just my thought:
I too experienced the case of complaints of "small text" when showing code to co-workers.
Having a way of instantly scaling it would be great for this scenario.
However, I personally prefer it to be a temporary thing only.

**Comment by bryphe** [comment]
Nice catch @CrossR on the `px` setting 👍 

Sounds like there are a couple issues here:
- It's easy to mess up the font-size setting. To make it more intuitive, perhaps we could add a default set of units if not specified - perhaps just using `px` if there are no units? I think that would solve the core issue. It also touches on #704, which is about making it easier to troubleshoot and understand our programmatic configuration.
- There isn't an easy way to set zoom level today - I moved this out to to #840 . It definitely sounds like a pain point! Agree with the difficulty too in saving back to the config - I added some thoughts in #840.

**Comment by badosu** [comment]
Is it worthy to enable arbitrary numbers for size settings?

I mean, 15 could mean `15em`, `15px`, `15%` or even `15vh`, this property is the literal that is sent to the css property, I am not sure much benefit is gained from having to parse this.

If the benefit in easy-to-use is enough though, then I think this *sanitization* should be shared between all settings that use a logic like this.

**Comment by CrossR** [comment]
Since #1097 fixed the default font unit, and there is #704 / #840 for the remaining two issues, think this ticket can be closed now.

**Comment by bryphe** [comment]
Perfect, sounds good!
