### ISSUE TITLE
Vertical split line has no consistent width

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#838]
![2017-10-29-113628_2058x1409_scrot](https://user-images.githubusercontent.com/163128/32142737-99a9a42a-bc9d-11e7-8db6-328feafab0bf.png)

At the current line in left pane the split border is 1px smaller than normal. This happens also to other lines as you can see in screenshot. I don't see a pattern and it looks random.

**Comment by hoschi** [comment]
Could this be happen because the cursor is 1px bigger than the width of a vim column? As you can see here the cursor is bigger than the "visual block" selection:

![2017-10-29-114415_2058x1409_scrot](https://user-images.githubusercontent.com/163128/32142800-a860535a-bc9e-11e7-8096-ae016a6af630.png)

**Comment by bryphe** [comment]
Thanks for logging the issue and the screenshots, @hoschi !

I think this may be more sub-pixel rendering issues in the `CanvasRenderer` - probably a related issue to #162 and #731

**Comment by CrossR** [comment]
I'm going to optimistically close this out now we have the `WebGL` renderer.... if this doesn't end up being fixed we can re-open it, but every other instance of sub-pixel rendering issues seems to have been sorted!
