### ISSUE TITLE
Bold and italic font not working

### ISSUE THREAD

**Issue by kristijanhusak** [onivim/oni#878]
Hi,

I just installed oni, and it really works good. I just noticed that both bold and italic font are not showing.
Here's screenshot from neovim:
![neovim](https://i.imgur.com/xkViIaj.png)

And a screenshot from oni
![oni](https://i.imgur.com/z0CIWAh.png)

I'm using [Iosevka Term](https://github.com/be5invis/Iosevka) font.

**Comment by bryphe** [comment]
Hi @kristijanhusak ,

Thanks for trying out Oni, and taking the time to report the issue! Appreciate the screenshots.

Yes, looks like we are ignoring the bold / italic font info coming from Neovim - definitely a bug.

**Comment by superquest** [comment]
I might be able to fix this if you could point me in right direction @bryphe.

Where exactly does Oni receive this info?

**Comment by bryphe** [comment]
That would be great to have help, @superquest !

Here's a few places to look:
- `NeovimInstance` handles the `redraw` event from Neovim here: https://github.com/onivim/oni/blob/18a7bff99f9cc9e0164e40b6274d3ff134d10b26/browser/src/neovim/NeovimInstance.ts#L515 (there's info on how these events look, like: `:help ui-event-highlight_set`. We might be ignoring the `bold` or `italic` state here.
- The `NeovimScreen` class manages the state of the screen (basically taking the `redraw` events, and updating our in-memory grid of the screen state). The cell interface here is the data we store: https://github.com/onivim/oni/blob/18a7bff99f9cc9e0164e40b6274d3ff134d10b26/browser/src/Screen.ts#L39 We're missing `bold` and `italic` here, so it would need to be added - once we have that, we should be able to call `getCell` and get the `bold` and `italic` state for a cell, along with the stuff we already have.
- Finally, once we've updated our screen state to have the `bold` and `italic` info, we'd need to update our renderer to know to add bold / italic: https://github.com/onivim/oni/blob/18a7bff99f9cc9e0164e40b6274d3ff134d10b26/browser/src/Renderer/CanvasRenderer.ts#L243

Hope that helps, let me know if you have any questions!

**Comment by superquest** [comment]
I've tried to produce a `highlight_set` notification with a `highlightInfo.bold` or `highlightInfo.italic` flag by editing a markdown file with content like `# this` and `_this_`. 

Such content is bolded and italicized in terminal Neovim, but no `bold` or `italic` flags show up in the `highlight_set` notification. Strange given that `:help ui-event-highlight_set` definitely says it should be there.

**Comment by superquest** [comment]
[Neovim-qt does exactly what we're trying to do as well](https://github.com/equalsraf/neovim-qt/blob/0551ef29108ebcfad2f9bcaa8658317bf8ca886c/src/gui/shell.cpp#L249).

Well I'm stuck here. 

I'm going to go hard-code bold and italic values in `DefaultCell` and try to figure out the rendering.

**Comment by bryphe** [comment]
> I'm going to try to figure out the rendering given a bold / italic cell.

Cool, splitting it up like that sounds like a good strategy!

I'm seeing some `bold`'s come through here:
![image](https://user-images.githubusercontent.com/13532591/33095568-f91c676c-ceb8-11e7-899d-b89be396a198.png)
(in `Screen.ts` where it handles `Actions.SET_HIGHLIGHT`). Seems like we are just ignoring them though, and not ever setting `this._currentHighlight.bold` or `this._currentHighlight.italic` - I think wiring it up there is the first step. Then, it seems like the `Actions.PutAction` section doesn't care about it - we'll want to send those values through when we set the cell.
