### ISSUE TITLE
Dev tools says "No supported language" for "javascript.jsx"

### ISSUE THREAD

**Issue by Metamist** [onivim/oni#882]
It seems that all my `.js` files are opened as `javascript.jsx` language (says so in the status bar). This causes autocomplete to not work at all, and I can't figure out how to switch to `javascript` language.
`set syntax=javascript` does not do anything except change colors.

Edit: Seems like `set filetype=javascript` works to get autocomplete to work again, however the status bar does not update unless you switch to another tab and then back.
I do not want to use filetype javascript since I am working with `.jsx` files, not `.js` (however, all my `.js` files open as `javascript.jsx`, so `.js` files does not get autocompletion either), and the autocomplete should work the same for both.

**Comment by bryphe** [comment]
Hi @Metamist ,

Thanks for reporting the issue! 

I just tested this out and it seems that the filetype is reported as `javascript` with Oni in the out-of-the-box setup:
![image](https://user-images.githubusercontent.com/13532591/32519599-2cd1fab0-c3c2-11e7-98a4-fc9a420c400d.png)

A couple questions for clarification:
1) Do you happen to be using any additional plugins or a custom `init.vim`?
2) Is this on `master` or the `0.2.14` release? 

I think there are a few potential ways we could address this - I'm not sure if it is a common pattern to use `<language>.<extension>` in Vim in general, but if it is, we could use just the `<language>` piece for  language server integration. Another option would be to specify a mapping - like `javascript.jsx` should map to `javascript` language server.

**Comment by Metamist** [comment]
It was `vim-polyglot` that opened my `.js` files as `javascript.jsx`. Removing that fixed that issue, but the actual problem is *not* that it is using `javascript.jsx`. Without this plugin, `.js` and `.jsx` files are opened as filetype `javascript`.

*However*
`vim-jsx` is another plugin that vastly improves indents and highlighting for jsx files, and it does this by setting all `.jsx` files to `javascript.jsx` which is the indented feature. The *problem* is that Oni does not detect `javascript.jsx` as `javascript`, thus no autocomplete.

A simple fix would be, like you said, to simply add `javascript.jsx` to the autocompletion list, since I doubht there's a common pattern.

**Comment by bryphe** [comment]
I merged in #966, which extracts out the `javascript` and uses that to key off the language server - with that change, the javascript auto completion will kick in. So it should work correctly on `master` now 👍 

I'll close this, but feel free to reopen if it's still not working.
