### ISSUE TITLE
Malware included in Windows installer?

### ISSUE THREAD

**Issue by i-am-cjc** [onivim/oni#889]
Installed using the current windows installer and got a warning from Sophos that it contains Mal/EndPK-ZC in one of the node modules that are included in the file `C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-ripgrep\bin\rg.exe`

https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Mal~EncPk-ZC/detailed-analysis.aspx

**Comment by bryphe** [comment]
Thank you for catching this, @i-am-cjc ! I am investigating right now and removing the impacted Windows builds from the releases section. 

We leverage the `vscode-ripgrep` binary from this NPM module:  https://github.com/roblourens/vscode-ripgrep

It seems that it impacted both the `zip` and `installer` files, and does not appear that `vscode-ripgrep` itself when run via `npm install` has the issue.

I'm looking to see if this is somehow introduced on our build machine.

**Comment by bryphe** [comment]
Appears that this is being introduced during AppVeyor build  ☹️ 

When running `npm install vscode-ripgrep` locally, there is no issue. However, when run on AppVeyor, and producing the artifact, I see the malware present - I created this repo to test: https://github.com/bryphe/test-ripgrep-appveyor-build

I'll look into some alternative plans to produce Windows builds in the meantime, and will keep this issue updated. Thank you again for reporting this.

**Comment by bryphe** [comment]
Never mind, not appveyor's fault - it looks like there is actually malware in the package in `vscode-ripgrep`... logged a new issue tracking it there: https://github.com/roblourens/vscode-ripgrep/issues/6

It only affects the `ia32` and not `x64` dependency which is strange, but we build Oni for `x86` which is why we see the problem there...

**Comment by bryphe** [comment]
I've switched to use the dependency directly from https://github.com/BurntSushi/ripgrep, bypassing the artifact with the issue at vscode-ripgrep.

The artifacts produced by the latest build look good:
https://ci.appveyor.com/project/bryphe/oni/build/1.0.443/job/87v16v4e4hatx0ot

**Comment by i-am-cjc** [comment]
Thanks for the response to this. Apologies for being silent I was away from the internet for a while. Just installed the latest build and I am getting no reports from Sophos now.

**Comment by bryphe** [comment]
Excellent, thanks for the confirmation @i-am-cjc , and appreciate you finding this. This issue seemed to also impact VSCode's `vscode-ripgrep` dependency, and more info here: https://github.com/roblourens/vscode-ripgrep/issues/6

**Comment by letroll** [comment]
it's always here! In stable Windows installer

**Comment by bryphe** [comment]
Hi @letroll - could you please give more information?

- What virus scanner are you using? 
- What is it detecting?
- Which binary files are impacted?

It would be helpful to have a new issue to track it with those details.

Thank you!

**Comment by letroll** [comment]
I'm not sure it's a virus, but multiple instances of an executable "rg.exe" were launch and was taking all ram. And continue to reopen after killing them. After uninstalling onivim, no more instance of it run.

**Comment by bryphe** [comment]
Thanks for the details, @letroll!

Interesting, this sounds related to #1973  - `rg.exe` is our packaged `ripgrep` binary, which we use for search. Did you happen to use the `find in files` functionality? I wonder if there is a bug there which is spawning too many of those processes.
