### ISSUE TITLE
Benchmark & improve start-up perf

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#89]
One goal of this project is to provide IDE-like extension capabilities to Neovim _without compromises_ - especially without compromising performance.

One feature that is consistently appreciated with Vim is the startup time, relative to IDEs and relative to other editors like Emacs.

There are several opportunities to improve performance in our startup time. In addition, we should add performance metrics so it can be easily reported. 

All startup tasks should be made async as much as possible, including plugin load, to allow the user to interact with the editor as quickly as possible.

**Comment by extr0py** [comment]
Need to find exactly the bottlenecks, but this might be interesting to look at:
https://github.com/nolanlawson/optimize-js

It looks like on Chrome, wrapping in IIFEs can speed up parsing

**Comment by bryphe** [comment]
Remaining work here is tracked by #372 and #943
