### ISSUE TITLE
Doesn't run on Ubuntu

### ISSUE THREAD

**Issue by vnikk** [onivim/oni#900]
The window opens and closes immediately.
The run script in electron ./app/oni.sh contains "TODO Enable Linux"

**Comment by TalAmuyal** [comment]
I just tried 0.2.16 on Ubuntu 17.10 and it works for me.
Can you describe what actions you've taken? (I installed using `sudo dpkg -i Oni-0.2.16-amd64-linux.deb`)

**Comment by keforbes** [comment]
The `oni.sh` file is only intended to be used by Mac.  I think the command to launch on Linux is in `./cli/oni`.  Regardless, if you're compiling from source it's best to just run `sudo npm link` so the `oni` command will be added to your path.

**Comment by bryphe** [comment]
Do you have `nvim` installed and available in your path?

Unfortunately, we are not robust in the case where `nvim` is not found, and we will exit immediately as you describe. We need better error handling in that situation for sure!

**Comment by bryphe** [comment]
The issue with the app crashing on Linux if Neovim isn't installed has been addressed with PR #937, and is now available in [0.2.17](https://github.com/onivim/oni/releases/tag/v0.2.17). I'll close this out, but feel free to reopen if you're still seeing issues.
