### ISSUE TITLE
Question: How can i return from insert more?

### ISSUE THREAD

**Issue by IvRRimum** [onivim/oni#902]
In neovim i just could press ESC or CTRL+C. In oni, when i enter interactive sheel( :term ) i can't go back to normal mode.

I am on a mac os BTW.

Thanks!

**Comment by IvRRimum** [comment]
Is there a doc somewhere with your custom key's or something? Really love the work tho!

**Comment by IvRRimum** [comment]
https://vi.stackexchange.com/questions/4919/exit-from-terminal-mode-in-neovim

**Comment by bryphe** [comment]
Thanks for following up here, @IvRRimum ! I do agree this is confusing... I would like to add some defaults to Oni to help make this work better out-of-the-box. I'll reopen to track adding those defaults.

**Comment by bryphe** [comment]
With #915 we added `ESC` to exit terminal mode by default so it is less confusing. Thanks for the suggestion!
