### ISSUE TITLE
Windows, config.js, E212: Can't open file for writing: no such file or directory

### ISSUE THREAD

**Issue by sittim** [onivim/oni#903]
- Oni Version 0.2.16
- Winodws 10

1 - "File -> Preferences -> Edit Oni Config"
2 - add a configuration line
3- Enter `:w`, get the following error:  `E212: Can't open file for writing: no such file or directory:
![image](https://user-images.githubusercontent.com/8825037/32609213-e102b3c4-c52c-11e7-9e1f-1e59d34b2491.png)

When I execute `pwd`, I get the following: `C:\Program Files (x86)\Oni`

**Comment by keforbes** [comment]
I hit this on my Linux system because the `.oni` directory was missing.  After I manually created `.oni` in my home directory it could save `config.js`.  You could give that a try as a workaround.  If it works, we definitely need to fix this defect so `.oni` is always created first before attempting to save that file.

**Comment by sittim** [comment]
OK, so the ~ directory is in `C:\Users\"your user name\"  this is confusing in Windows.  Once `.oni` directory is created under the home folder, it works fine.  Furthermore, in windows, you cannot create a dotfile in the explorer.

**Comment by keforbes** [comment]
I'm glad you found a workaround but I still think this issue is worth fixing.  Re-opening.

**Comment by keforbes** [comment]
Just to re-enforce what @sittim said, creating a directory named `.oni` is difficult to do in Windows.  I believe the current Windows convention would be to create an `oni` directory in `AppData/Roaming`.  I'm pretty sure there's some `%AppData%` type variable we should be using but I'm not a Windows guy so everything I say on the subject should be validated. 😄

**Comment by CrossR** [comment]
By default on Windows, I think it should go in `%APPDATA%/oni`, as @keforbes has said.

To my knowledge its where this style of files goes, at least for both VS Code and Notepad++.

**Comment by CrossR** [comment]
Changing this is easy enough and I've got it in a branch, but I was wondering about what the Oni stance is on things like this, in what is basically a breaking(for lack of a better word) change.

The way I've done it means any other Windows Oni user would now need to move their config over from `C:\Users\CrossR\.oni\config.js` to `%APPDATA%\oni\config.js`.

Should we accept both or what?

**Comment by bryphe** [comment]
Awesome, thanks @keforbes and @CrossR for thinking about.

Yes, you're right, it seems like the standard on Windows is to be in `%APPDATA%`.

I put some thoughts about versioning + backwards compatibility here: #938 

We do have in our README that Oni is currently unstable and essentially that things may break, but we are also getting more users and I'd like to start looking at how we can have a better story for upgrade. This is one thing that's holding me from turning on auto-updates - it'd be incredibly annoying if we released updates all the time that just broke everyone 😄 

I think the config-location move would be a good test case / use case for #938 , so I'd like to use that as our first 'upgrader'. Let me know your thoughts, though.

The other change, to make the directory if it doesn't exist, would be great to have - I don't see any blocker for that. It's a major pain for the first-run experience - feels really broken.
