### ISSUE TITLE
Support input sequences

### ISSUE THREAD

**Issue by sittim** [onivim/oni#907]
How do I remap `jk` to `esc`.  I tried the following with no effect

```js
const activate = (oni) => {
    oni.input.bind("<jk>", "Esc")
};

module.exports = {
    activate,
    "editor.fontSize": "13px",
    "editor.completions.enabled": true
}
```

**Comment by keforbes** [comment]
Just set
```
"oni.loadInitVim": true
```
Then define all mappings as normal in your `init.vim`.

**Comment by bryphe** [comment]
Yes, unfortunately Oni doesn't support sequenced input at the moment (multiple inputs entered in a certain time, like `jk`) - this is something I'd like to support eventually, but using `init.vim` for right now is a good workaround.

**Comment by sittim** [comment]
Understand, but it does not need to support sequenced input, why not just pass the actual command to neovim?  This may require some though on how the mappings fit together, but maybe build a dedicated configuration such as `oni.input.nvimbind` that would trigger passing the command to neovim.

**Comment by bryphe** [comment]
> Understand, but it does not need to support sequenced input, why not just pass the actual command to neovim?

Thanks for thinking about this! This would be a reasonable approach in the short-term, where most of our input round-trips through Neovim, but wouldn't handle some of the future scenarios on the roadmap for Oni. In particular, there will be cases where it wouldn't make sense to round-trip commands through Neovim for some of the planned features we have (like an embedded browser split). We already have small pockets of these (like the quick open and command palette menu - none of that input goes through Neovim).

By handling the input in a consistent way, we can support some of these new paradigms without the complexity of having to think about "Should I use `oni.input.bind` or `oni.input.nvimbind` for this particular case?" 

If you want that functionality today, there's nothing stopping it - you could always write a function `nvimbind` using our editor API. This API lets you talk directly to neovim, like:
`Oni.editors.activeEditor.neovim.command("nnoremap jk :echo 'Hello'<CR>")`

But by supporting this in the Oni layer, we can set up the foundation to support this in general for our mission to "break free of terminal limitations" 😄

**Comment by sittim** [comment]
OK, makes sense, no I do not need the functionality today and temporary solutions usually spell trouble, so lets close it.
