### ISSUE TITLE
Interactive shell doesnt find brew and imagemagick packages

### ISSUE THREAD

**Issue by IvRRimum** [onivim/oni#919]
Hello,

When i run `:term` and then type `brew`, i get undefined. It works for a normal terminal.. Also imagemagick is not present in oni terminals env.

How to fix this?

Thanks!

**Comment by bryphe** [comment]
Hi @IvRRimum ,

I think this might be the same issue @Akin909 ran into in #839 (towards the bottom) - seems like potentially the `PATH` environment variable that Neovim inherits when it starts up doesn't have the full set of paths.

Just to confirm it is the same issue:
- How are you starting Oni? From a terminal or from finder?
- How does the output of `echo $PATH` compare in `:term` vs a normal terminal?

Thanks!

**Comment by bryphe** [comment]
This should be resolved by #924 (since that adds `/usr/local/bin` to the paths Oni recognizes by default). Thanks for the fix, @Akin909 !

**Comment by IvRRimum** [comment]
@bryphe So, if i download the newest release for mac. Will it work?

**Comment by bryphe** [comment]
I'm planning on pushing out a new release - 0.2.17 - on Wednesday. The fix will be picked up in that package. There's a couple more fixes I want to get in before getting the release out.

**Comment by IvRRimum** [comment]
@bryphe Great! Can you add the tab fix too, that would mean a lot! Thanks!
