### ISSUE TITLE
configuration in after folder is not recognized

### ISSUE THREAD

**Issue by ErickChacon** [onivim/oni#923]
A have certain configuration in the folder `.config/nvim/after` that is not being recognized by oni. Usually a have some extra syntax highlighting in this folder. Is there any reason why oni does not take into account this folder? How can I make use of oni taking into account this additional configuration in the folder `after`? 

My config.js is as follows:

```
const activate = (oni) => {
    console.log("config activated")
    oni.input.bind("<c-enter>", () => console.log("Control+Enter was pressed"))
}

const deactivate = () => {
    console.log("config deactivated")
}

module.exports = {
    activate,
    deactivate,
   "oni.useDefaultConfig": false, // default is true
   "oni.loadInitVim": true,
    "statusbar.enabled": true, // yes by default
    "editor.fontSize": "16px",
}
```

**Comment by bryphe** [comment]
Looks like we missed a comma when setting the runtime paths - here's what mine looked like:

![image](https://user-images.githubusercontent.com/13532591/32754891-91f8f528-c887-11e7-9096-e1aae96fec1b.png)

Looks like a quick fix - created PR #935

**Comment by bryphe** [comment]
Fixed by #935

**Comment by ErickChacon** [comment]
Great, thank you so much for the fix.

**Comment by bryphe** [comment]
FYI - [0.2.17](https://github.com/onivim/oni/releases/tag/v0.2.17) is out now
