### ISSUE TITLE
<C-t> on QuickOpen does not opens in new tab anymore

### ISSUE THREAD

**Issue by badosu** [onivim/oni#930]
It also makes the QuickOpen component unresponsive to further input.

This happened after upgrading from 0.2.14 -> 0.2.16.

**Comment by CrossR** [comment]
I've noticed this is because of the Symbol search keybind overlapping (both are Ctrl + T), and I've made a PR for it here so that the Symbol search only activates when the menu isn't open. #927

**Comment by bryphe** [comment]
Thanks @badosu for catching this, and @CrossR for the PR! I've brought it in - so the fix is now available on master.
