### ISSUE TITLE
Ctrl-T to open in new tab

### ISSUE THREAD

**Issue by rockneverdies55** [onivim/oni#949]
In the search dialog results, when I press `Ctrl T` it doesn't open the file in a new tab anymore with v 2.16.

With the new version I was so happy to see that I could now close the search dialog with `Ctrl {` without reaching out to `ESC`. However now I can't open the files in new tab which is almost always what I do when I do a search for a file.

Now I have to create a new tab wiht `:tabnew` and then make a search starting with `Ctrl P` to do the same thing.

**Comment by bryphe** [comment]
This is actually already fixed in master - @CrossR fixed this in #927 , and will be available in the next release (v0.2.17, which will be out today)

**Comment by bryphe** [comment]
0.2.17 is out here: https://github.com/onivim/oni/releases/tag/v0.2.17

Try it out and see if it fixes your issue.

**Comment by rockneverdies55** [comment]
You're the man, thanks for quickly releasing the new version.

Yes, the issue has disappeared.

**Comment by bryphe** [comment]
Awesome 😄 Thanks @CrossR for catching it and fixing it! I'll close this out.
