### ISSUE TITLE
Autocomplete oddities

### ISSUE THREAD

**Issue by badosu** [onivim/oni#956]
Suppose you have a word like `const` (on a js file), I'll denote the cursor with `_`.

In normal mode you are at `co_nst`, as soon you change it to insertion mode the menu pops up which is not something I would expect, so I type `ESC` and `ESC` to come back to normal mode. As soon as I try to get back into insertion mode the menu pops out of nowhere again, even outside of that word.

So maybe there are 2 bugs here, popping autocompletion without having inserted any character in the middle of a word, and also still thinking you are at the menu even after leaving it when coming back from normal mode.

**Comment by bryphe** [comment]
Definitely both bugs - thanks for isolating a repro!

I'm able to reproduce both those issues
