### ISSUE TITLE
Menu positioning on Autocomplete (C-n)

### ISSUE THREAD

**Issue by badosu** [onivim/oni#958]
I noticed that recently the menu is appearing in an odd position at the top of the screen. (Opened with `<C-n>`)

![screenshot from 2017-11-15 22-55-07](https://user-images.githubusercontent.com/347552/32868215-33d8ece6-ca58-11e7-859a-3088828a5697.png)

**Comment by bryphe** [comment]
Looks like a duplicate of #895
