### ISSUE TITLE
Scalable units are not based on fontSize

### ISSUE THREAD

**Issue by badosu** [onivim/oni#959]
This might be a good or bad thing, but I noticed this when I upgraded Oni on a machine that I use with a Hi-DPI display, the OS font sizes are usually small so that was my motivation to make the status and tab bar scalable.

With font size 24px:

![screenshot from 2017-11-15 23-08-41](https://user-images.githubusercontent.com/347552/32868647-5be3428e-ca5a-11e7-9d87-a847c411fd88.png)

With font size 48px:

![screenshot from 2017-11-15 23-09-03](https://user-images.githubusercontent.com/347552/32868680-72ffe008-ca5a-11e7-9dc1-addc83455e2f.png)

Examples chosen for emphasis (and not on the aforementioned display).

So, it seems they are inheriting the base font size from somewhere else than `fontSize`. That is fine by me, but breaks the purpose of why I developed the scalability for these elements.

If scaling with `fontSize` is not desirable perhaps we can at least offer configuration for the base font size these elements inherit from?

Statusbar font size is already configurable via `statusbar.fontSize`. If a respective one can be added for tabs then this is a non-issue, and the base font size configuration (or inheriting from editor font size) suggestions can be ignored.

Let me know your thoughts.

**Comment by CrossR** [comment]
To my knowledge there is as follows:

* Editor Font Size
* Status Bar Font Size
* UI font size

The last one seems to affect both tabs and the status bar, which I think covers what you want? Changing just `"ui.fontSize" : "48px"` made both my tab bar and status bar fonts huge.

Does that help?

Feels like as we add more and more config options, Oni is more and more in need of either a VS Code style search window through every setting and its default, or code completion style pop ups so you can just find the config options that way.

**Comment by badosu** [comment]
@CrossR Was nNot aware of ui fontSize, perhaps I should do my homework before putting issues. 

Thank you very much @CrossR!

**Comment by bryphe** [comment]
> Was not aware of ui fontSize, perhaps I should do my homework before putting issues.

Not you're fault @badosu - I agree with @CrossR 's comment here:

> Oni is more and more in need of either a VS Code style search window through every setting and its default, or code completion style pop ups so you can just find the config options that way.

Definitely need a way to make these more discoverable and intuitive!
