### ISSUE TITLE
Ctrl-w to delete word on the left of cursor

### ISSUE THREAD

**Issue by rockneverdies55** [onivim/oni#963]
Another muscle memory habit that I miss while using oni. While searching for files in search popup pressing `Ctrl-W` doesn't erase the word on the left of cursor. Would be fantastic if this binding could be added.

**Comment by bryphe** [comment]
Ah yes - I'd like to have that text input for the popup menu be driven by Neovim (it's not today), that way all the insert mode bindings or customizations would work.

In the interim, we could have a one-off binding for that in the popup menu, potentially.

**Comment by bryphe** [comment]
Fixed in master now with #1227
