### ISSUE TITLE
Expose options on `config.js`

### ISSUE THREAD

**Issue by badosu** [onivim/oni#976]
Since we don't have a preferences dialog, for the user to manage Oni's settings, currently the user has to consult documentation out of the application.

What do you think of exposing all (or a representative subset of) defaul configuration options on the initial `config.js`?

We could order and group them into:

- Semantic and hierarchical structure (top namespace)
- Chunks of relevance (`oni.fontSize` and `ui.fontSize` are more relevant together than `oni.audio.bellUrl`)

Adding comments perhaps?

Let me know your thougts.

**Comment by bryphe** [comment]
I like this idea a lot! I think it would make discovery of the configuration values much easier.

I'd be fine completely moving the `DefaultConfiguration.ts` to our out-of-box `config.js`. Discoverability of settings is certainly a problem today and this would help immensely.

**Comment by bryphe** [comment]
I believe this is addressed now by @rgehan 's fix in PR #1795 - thanks @rgehan 👍
