### ISSUE TITLE
Add tab index for absolute navigation

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#978]
At the moment it is hard to navigation between tabs with `{count}gt` when you have more than ~5 tabs. Even more harder when tabs are wrapped. The index from traditional vim should be added again to make this as easy as before.

![2017-11-18-111401_2058x1409_scrot](https://user-images.githubusercontent.com/163128/32979232-95eef402-cc51-11e7-9463-dc983fe6db38.png)

**Comment by bryphe** [comment]
Cool, I think this would make sense to add as a setting, like `tab.showIndex` - and it would have parallels for both buffers and tabs (in buffer mode, show the buffer index, and tab mode, show the tab index). I believe this should be pretty straightforward - we should already have both of these values available - just the matter of plumbing it through and gating it via configuration.
