### ISSUE TITLE
Implement notification UX

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#98]
Part of this wouldn't be fully baked until we get the Neovim PR to decouple the UI, however, we could still use the UI paradigm for alerts / existing errors in code

**Comment by jordwalke** [comment]
This other issue might be related:

https://github.com/extr0py/oni/issues/39

It seems much better than the Atom UI notifications feature.

**Comment by extr0py** [comment]
#365 makes progress towards this - I think it makes sense to keep open to track the alert / pop-up notification scenario, though.
