### ISSUE TITLE
Rename action is not undoable with one "undo" action

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#980]
When you hit `F2` to rename a string and you can't undo it by hit "undo" one time. Instead you must hit undo as much as renames occurred.

**Comment by bryphe** [comment]
Good catch @hoschi ! Yes, this is very annoying.. 

This is the codepath where we apply all of these edits:
https://github.com/onivim/oni/blob/af12e7e847b02f6b0f702cfb055f016b2ef9ec9f/browser/src/Services/Workspace.ts#L34

Ideally, this whole edit operation should be grouped into a single `undo` gesture.

Vim/Neovim support an `undojoin` command, we should be able to leverage that here.
