### ISSUE TITLE
Font size of completion popup should relate to `editor.fontSize`

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#981]
When I tune `editor.fontSize` up to match my bad eyes the completion popup stays at `13px`. This should get its own setting or use `editor.fontSize`.

`editor.fontSize:16px`
![2017-11-18-112952_1370x1384_scrot](https://user-images.githubusercontent.com/163128/32979361-143ce790-cc54-11e7-84a4-ec9bc6506a8b.png)

**Comment by CrossR** [comment]
Currently it uses ` "ui.fontsize"`, which also changes the tabs and status bar, but it does seem that it would make more sense to base it on the editor size, at least to me.

**Comment by badosu** [comment]
Well, a decision has to be made, if one wants to configure, for instance, smaller or bigger ui elements (tabs, statusbar), should the completion follow? Is it a ui or editor element?

**Comment by bryphe** [comment]
> Currently it uses "ui.fontsize", which also changes the tabs and status bar, but it does seem that it would make more sense to base it on the editor size, at least to me.

> By this line of reasoning it seems (to me) suitable as an editor setting as it uses the same visual span as the editor itself.

Agree with you both @badosu @CrossR 

The things that certainly make sense to use `ui.fontSize` and `ui.fontFamily` are things external to the editor view, like:
- File Explorer
- Status bar
- Notification pop ups
- Tabs

Right now, we also have this UX that is controlled by `ui.fontSize` and `ui.fontFamily`:
- Rename
- Context menu (completion, and later refactoring options)
- Tool tip (hover)

It would make sense to switch these back to using `editor.fontSize` and `editor.fontFamily`. I like the general litmus test of if it's in the same visual span / layer as the editor, it should use that setting.
