### ISSUE TITLE
Language integration doesn't work with 0.2.17

### ISSUE THREAD

**Issue by hoschi** [onivim/oni#988]
It always says "No content available"
![2017-11-20-112755_1542x1409_scrot](https://user-images.githubusercontent.com/163128/33013964-fda6edd0-cde5-11e7-9d3a-7af014638436.png)

**Comment by bryphe** [comment]
The 'No content available' is actually expected (we are pretty aggressive in calling `textDocument/hover`, and there are cases - like here, where the mouse is on `"`, we'd expect there to be no content). It might be worth downgrading this message to avoid confusion.

However, is other functionality broken too? Like completion? 

A few things that should for sure work here:
- Start typing `window` on a new line, you should get completions
- Hover on `electron_1` - does a hover popup show?

**Comment by hoschi** [comment]
@bryphe Syntax highlight is broken as you can see in screenshot. Only the vim built in syntax parts have colors. I thought that was the content of the response :grinning:

**Comment by hoschi** [comment]
b64f415ce05244a9bf2063880602d813833ece8c is the last working version

**Comment by bryphe** [comment]
Ah ok, got it, apologies, I was focused on the console logs 😄 

I'm working on a revised implementation of syntax highlighting here: #848 , with the goal of having parity with VSCode.

As part of the LSP refactor, I pulled out the syntax highlighting for a few reasons:
- It was hacky implementation that just tried to infer based on the `textDocument/symbol` LSP - didn't really handle all cases (like nested tokens, or tokens in different scopes)..
- It's not actually part of the language server protocol, so it didn't fit well when I refactored the code
- It was slow for large files

Sorry that was poorly communicated. We can use this to track the 'revised' syntax highlighting, leveraging TextMate themes, coming in #848

**Comment by badosu** [comment]
@hoschi 0.2.18 was released, can you check is this is fixed?

**Comment by hoschi** [comment]
@badosu hm "kind of" :grin: 
When I enable the experiment syntax highlight looked good for me, but tested just a single file. Problem for me is that it doesn't work with vim colorschemes so I switched back to my working Oni version till #1050 is fixed.

If the experiment part is ok and intended you can close this imo.

**Comment by hoschi** [comment]
works with experimental syntax highlighting
